import {
  REACT_APP_AIR_PROD_BASE_URL,
  REACT_APP_BASE_API_URL,
  REACT_APP_FARMER_IMPACT_BASE_URL,
  REACT_APP_IMPACT_BACKUP_BASE_URL,
  REACT_APP_KNOWLEDGE_HUB_URL,
  REACT_APP_MAPBOX_ACCESS_TOKEN,
  REACT_APP_YOUR_VCCA_PDF_LINK,
  REACT_APP_SENTRY_DSN,
  REACT_APP_ENVIRONMENT,
  REACT_APP_DEEP_LINK_URL,
} from '@env';

export const API_BASE_URL = REACT_APP_BASE_API_URL;
export const AIR_PROD_BASE_URL = REACT_APP_AIR_PROD_BASE_URL;
export const MAPBOX_ACCESS_TOKEN = REACT_APP_MAPBOX_ACCESS_TOKEN;
export const IMPACT_BACKUP_BASE_URL = REACT_APP_IMPACT_BACKUP_BASE_URL;
export const FARMER_IMPACT_BASE_URL = REACT_APP_FARMER_IMPACT_BASE_URL;
export const KNOWLEDGE_HUB_URL = REACT_APP_KNOWLEDGE_HUB_URL;
export const YOUR_VCCA_PDF_LINK = REACT_APP_YOUR_VCCA_PDF_LINK;
export const SENTRY_DSN = REACT_APP_SENTRY_DSN;
export const ENVIRONMENT = REACT_APP_ENVIRONMENT;
export const DEEP_LINK_URL = REACT_APP_DEEP_LINK_URL;
