import { ERoles } from '#types/global';
import { APP_LOCALES, TranslationLocales } from '#i18n/constants';

type Faq = {
  id: number;
  title: string;
  role: ERoles[];
  text: string;
};

export const FAQ_CONTENT: Record<TranslationLocales, Faq[]> = {
  [APP_LOCALES.ENGLISH]: [
    {
      id: 1,
      title: 'Why should I use the app?',
      role: [ERoles.AUTH],
      text: 'The app is designed to support cold room providers in their day-to-day operations at the cold room. The app features a digital inventory, remote monitoring of the items in storage and room temperature (if sensors are available), and information about the number of days a given item in storage is still good for. It also includes the Knowledge Hub, which provides commodity-specific recommendations on optimal storage temperature and storage life. Additionally, cooling users can use the app to find nearby cooling units, to monitor the produce they have brought to cold storage, get informed about good storing practices, and get recommendations about the best time and place to sell.',
    },
    {
      id: 2,
      title: 'Who can use the app?',
      role: [ERoles.AUTH],
      text: "The app can be used by employees and operators of cold storage companies as well as by potential cooling users around the world. Throughout the app, there are three user roles: (i) Registered employee: part of the cold room provider management team. A person that is responsible for setting up and managing the room, is in charge of overlooking the operators activities on the ground, without being physically present at the location. For example: a company CEO, CFO, etc. (ii) Operator: an employee physically present at the cold room and managing its check-in, check-out operations. This person is in direct contact with the cold room users, and reports to a company registered employee. (iii) Cooling users: the cold room users (can be farmers, traders, retailers, etc). Cooling users who have a smartphone can log in on the app as users. If they don't have a smartphone, operators do the cooling users' operations on their behalf.",
    },
    {
      id: 3,
      title: 'How can I sign up as a Registered employee?',
      role: [ERoles.AUTH],
      text: "If you are the first employee from your company to sign up, you can click on the 'Sign up as a company' button and follow the steps to register your company and yourself (including personal details and password). Once you have successfully signed up, you can log in as a Registered employee in the app and send a SMS invitation to other registered employees to join your company.",
    },
    {
      id: 4,
      title: 'How can I sign up as an Operator?',
      role: [ERoles.AUTH],
      text: 'To sign up, you need to be invited by a Registered employee. You will receive an SMS with an activation link, from where you can set up your personal details and password.',
    },
    {
      id: 5,
      title: 'How can I sign up as a Cooling user?',
      role: [ERoles.AUTH],
      text: "Cooling users with smartphones can register as app users clicking on 'Sign up as a cooling user' in the homepage and providing their personal details and password. Cooling users who don't have a smartphone can be added to the app by the operators. This operation is needed to initiate a check-in for those cooling users. Cooling users need to provide a phone number, which the operator will use to contact the cooling users in case of need. No password is required in this case.",
    },
    {
      id: 6,
      title: 'I cannot complete the registration as a user. What should I do?',
      role: [ERoles.AUTH],
      text: 'To complete the registration, please make sure that the following conditions are satisfied: (i) You are entering a phone number with the correct country code (e.g. +91 for India); (ii) The phone number you provided has not been used to register any other user; (iii) The password you are entering contains minimum 8 characters, and at least: one uppercase letter, one lowercase letter, and one number; (iv) The passwords you are entering are the same - you can click on the eye symbol to reveal the passwords and check they are equal.',
    },
    {
      id: 7,
      title: "I don't have a phone but want to use the app. What should I do?",
      role: [ERoles.AUTH],
      text: "If you are a registered employee or an operator, you need to provide a valid phone number to sign up. A smartphone is needed to correctly use the app. If you are a cooling user and don't have a phone, we also advise you to provide a valid phone number, so that the operator can contact you in case of need. You can give the phone number of a family member or a friend if you don't have your own. If this is not possible, the operator can still store the produce in the room by selecting 'User without phone' as the cooling user at check-in.",
    },
    {
      id: 8,
      title: 'Which details are needed for logging in as a Registered employee?',
      role: [ERoles.AUTH],
      text: 'Registered employees can log in with email or phone number, and their password.',
    },
    {
      id: 9,
      title: 'Which details are needed for logging in as an Operator?',
      role: [ERoles.AUTH],
      text: 'Operators can log in with their phone number and password.',
    },
    {
      id: 10,
      title: 'Which details are needed for logging in as a Cooling user?',
      role: [ERoles.AUTH],
      text: "Cooling users with smartphone can log in with their phone number and password. Cooling users who don't have a smartphone do not need to log in: the operator can do the operations on their behalf.",
    },
    {
      id: 12,
      title: "I haven't received any invitation per SMS. What should I do?",
      role: [ERoles.AUTH],
      text: 'Registered employees and operators can be invited to join the app by a registered employee of the same company. If the registered employee has invited you, but you have not received any SMS, please contact the registered employee directly. Common causes are: (i) Wrong number typed (note that a country calling code is needed); (ii) You have already accepted an invitation linked to that number. A phone number can only be used for one user. Cooling users with a smartphone can join the app without invitation. Cooling users without a smartphone can be registered in the app by operators.',
    },
    {
      id: 11,
      title: 'I have lost my password. What should I do?',
      role: [ERoles.AUTH],
      text: "If you have lost your password, you can restore your account by clicking on 'Forgot password' at sign in, enter your phone number, and you will receive an SMS with a link to set a new password.",
    },
    {
      id: 36,
      title: 'What is the Knowledge Hub?',
      role: [ERoles.AUTH],
      text: 'The Knowledge Hub is a page that can be reached by clicking on the Menu on the top left. It contains useful information about best storage practices for different commodities, including optimal temperature and approximate storage time under this temperature.',
    },
    {
      id: 13,
      title: 'How can I edit my profile?',
      role: [ERoles.EMPLOYEE],
      text: "By clicking on 'Menu' -> 'Account details', you can see your profile and edit the details (first and last name, phone number, email, and gender). Here you can also change the app language. To change the details of your company, locations, and cooling units, navigate to 'Menu' -> 'Management', and then select the menu item you wish to change.",
    },
    {
      id: 14,
      title: 'How can I edit my profile?',
      role: [ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "By clicking on 'Menu' -> 'Account details', you can see your profile and edit the details (first and last name, phone number, and gender). Here you can also change the app language.",
    },
    {
      id: 15,
      title: 'How can I assign operators to cooling units?',
      role: [ERoles.EMPLOYEE],
      text: "There are three ways to link an operator to a cooling unit. You can assign a cooling unit (or more than one) to an operator when you are sending him/her the invitation. Otherwise, you can modify the cooling units associated with a given operator by navigating to 'Management' -> 'Operators', selecting the operator, and then clicking on 'Select a cooling unit'. Finally, when creating a cooling unit in 'Management' -> 'Cooling units', you can also assign operators to it. Remember to save your changes before exiting!",
    },
    {
      id: 16,
      title:
        'A cooling user arrives at the cold room but has no phone. Can I still register him/her?',
      role: [ERoles.OPERATOR],
      text: "Yes, you can start a check in for that person using the cooling user named 'User without a phone'. As multiple people might use this account for check in, make sure to add a name tag to the crates in the room to identify the owner of each crate.",
    },
    {
      id: 18,
      title: 'How do I register my company?',
      role: [ERoles.EMPLOYEE],
      text: "To register your company, on the welcome screen select 'Sign up as company' and fill in the required information. Enter a password then click 'Sign up' and you are ready to go!",
    },
    {
      id: 19,
      title: 'How do I register a new location for my company?',
      role: [ERoles.EMPLOYEE],
      text: "Each cooling unit needs to be created at a location (and multiple cooling units can be created for the same location). To add a new location for your company, in the menu select 'Management' > 'Locations'. Click on the '+' on the top right corner to add a new location. Fill in the required information. Click 'add' to confirm.",
    },
    {
      id: 20,
      title: 'How do I register a new cooling unit for my company?',
      role: [ERoles.EMPLOYEE],
      text: "To register a new cooling unit for your company, you need to have at least one location created. Then, in the menu select 'Management' > 'Cooling units'. Click on the '+' on the top right corner to add a new cooling unit. Fill in the required information. Click 'add' to confirm.",
    },
    {
      id: 21,
      title: 'How do I invite other Registered employees from my company to register for the app?',
      role: [ERoles.EMPLOYEE],
      text: "To invite other Registered employees for your company, in the menu select 'Management' > ERoles.EMPLOYEE. Click on the '+' on the top right corner to add the telephone number of the employee you want to invite. Click 'Invite' to confirm: your colleague will receive an SMS with a link that guides him/her directly to the sign up screen. In addition, you will also receive an email with the invitation link. Please forward this to the operator in case he/she did not receive it via SMS.",
    },
    {
      id: 22,
      title: 'How do I invite cold storage operators to register for the app?',
      role: [ERoles.EMPLOYEE],
      text: "To send an invitation to operators for your cooling units, in the menu select 'Management' > 'Operators'. Click on the '+' on the top right corner to add the telephone number of the operator you want to invite. Click 'Invite' to confirm: the operator will receive a message with a link that guides him/her directly to the sign up screen. In addition, you will also receive an email with the invitation link. Please forward this to the operator in case he/she did not receive it via SMS.",
    },
    {
      id: 23,
      title: 'How do I monitor the temperature of a cooling unit?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "To monitor the temperature of a specific cooling unit click on the 'Cooling Units' button on the bottom right corner, navigate to 'Room conditions', and select the unit of interest from the dropdown. In this panel, you will see a graph with the temperature over time - you can scroll to see older data points. If you have sensors connected to the app, you will be able to see the actual room temperature here. Else, the graph will show the temperatures that you have manually set within the app.",
    },
    {
      id: 64,
      title: 'How do I monitor the temperature of a cooling unit?',
      role: [ERoles.COOLING_USER],
      text: "To monitor the temperature of a specific cooling unit click on the 'Cooling Units' button on the bottom right corner, navigate to 'Room conditions', and select the cooling unit of interest from the dropdown. In this panel, you will see a graph with the temperature over time - you can scroll to see older data points. If the room has sensors connected to the app, you will be able to see the actual room temperature here. Else, the graph will show the temperatures that the room operator has manually set within the app.",
    },
    {
      id: 24,
      title: 'How do I monitor the occupancy of a cooling unit?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "To manage the occupancy of a specific cooling unit click on the 'Cooling Units' icon at the bottom of the screen, navigate to 'Planner', and select the unit of interest from the dropdown. Here you can see the current occupancy (top) and the predicted occupancy for the next 7 days (bottom). The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate.",
    },
    {
      id: 65,
      title: 'How do I monitor the occupancy of a cooling unit?',
      role: [ERoles.COOLING_USER],
      text: "To monitor the occupancy of a specific cooling unit click on the 'Cooling Units' icon at the bottom of the screen, navigate to 'Planner', and select the cooling unit of interest from the dropdown. Here you can see the current occupancy (top) and the predicted occupancy for the next 7 days (bottom). The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate.",
    },
    {
      id: 25,
      title: 'How can I see which items are stored in a room?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "Click on the 'Dashboard' icon at the bottom of the screen and select the cooling unit of interest from the dropdown to see the list of all stored items in a cooling unit.",
    },
    {
      id: 26,
      title: 'How can I see past check-in and check-outs of a cooling unit?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "To see past movements of a cooling unit click on the 'History' icon: past check-ins (icons with green crate) and check-outs (icons with orange crate) with transaction details are displayed. If a specific check-out transaction is of interest the search function can assist you in finding it!",
    },
    {
      id: 28,
      title: 'What are the main tasks the operator can do in the app?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: 'The operator can: register new cooling users, initiate check-ins, monitor items in storage and room occupancy, initiate check-outs, and monitor the temperature of the cooling unit he/she is responsible for.',
    },
    {
      id: 29,
      title: 'How can I register new cooling users?',
      role: [ERoles.OPERATOR],
      text: "To register a new cooling user, in the Menu navigate to 'Management' > 'Cooling Users'. Click on the '+' on the top right corner and choose whether to add an already registered user with a code, or add the user details. A cooling user who has a smartphone and has already registered in Coldtivate has a unique code, which he/she can find under 'Menu' -> 'Account details'. If the user has no smartphone, or is not registered yet, you can invite the user by adding the name, gender and telephone number. If the user does not have his/her own number, the number of another person (e.g. friends, relatives) can be used. Click 'Save changes' to confirm. To complete the registration, you need to fill in a short survey by asking a few questions to the cooling user. The survey can also be completed at a later point by navigating to 'Management' -> 'Cooling Users' -> 'Survey'.",
    },
    {
      id: 30,
      title:
        'The cooling user has no time to answer the survey questions at registration. What should I do?',
      role: [ERoles.OPERATOR],
      text: "You can skip the survey questions by clicking 'Complete later'. In this case, you will be prompted to complete the survey the first time you are creating a check in for that cooling user. It is recommended to take the time and answer the survey questions thoroughly: in this way the user can get a more tailored experience with the Coldtivate app!",
    },
    {
      id: 88,
      title:
        "An operator is asking me for a code to add me to the company's list of cooling users. Where can I find the code?",
      role: [ERoles.COOLING_USER],
      text: "When you signed up in Coldtivate, you haev recived an unique identifier in form of a code. This code can be used by an operator to add you to the company's list of cooling users, which is needed for the operators to check-in your crates. The code can be found under 'Menu' -> 'Account Details'.",
    },
    {
      id: 66,
      title: 'I have no time to answer the survey questions at sign up. What should I do?',
      role: [ERoles.COOLING_USER],
      text: "You can skip the survey questions by clicking 'Complete later'. You will find the survey as part of your Account Details and can complete it anytime. However, It is recommended to take the time to answer the survey questions thoroughly when you start using the room: in this way you can get a more tailored experience with the Coldtivate app!",
    },
    {
      id: 67,
      title: 'How can I store something in a room?',
      role: [ERoles.COOLING_USER],
      text: "To complete your first check-in, use the map available in the 'Cooling Unit' tab to search for nearby cold rooms, and then bring your crates to the room. The cold room operator can help you understand how the room works, how you are going to be charged, and what are the benefits of using cold storage.",
    },
    {
      id: 31,
      title: 'How can I initiate a check in?',
      role: [ERoles.OPERATOR],
      text: 'To initiate a check-in, navigate to the Dashboard and click on the Activity Manager button on the lower right, and then click on the green button.',
    },
    {
      id: 32,
      title: 'How can I initiate a check out?',
      role: [ERoles.OPERATOR],
      text: "There are two ways to initiate a check out, both starting in the Dashboard page. You can click on the Activity Manager button on the lower right, and then click on the red button. In this way, you can select for which cooling user (and in which cooling unit) you want to start the check out, and can check out his/her crates from multiple check ins. Alternatively, you can click on 'See details' for an item you see in the Dashboard (make sure to be in the correct cooling unit), and click on 'Check out'. In this case, you can only check-out crates from that storage item.",
    },
    {
      id: 33,
      title: 'How do I connect the sensors in the room with the app?',
      role: [ERoles.EMPLOYEE],
      text: 'In order to connect a sensor to a cooling unit, the sensor needs to have an API setup. The API should use a username and password which are sent through a POST request of Content-Type: application/json. The response should include an accessToken, which can be used for another POST request. The POST request needs to include in the url the room-identifier, the type of value (temperature, humidity), and the token as a header with the key Authorization. The response should be the last recorded temperature in this room, in the format {date: dateTimeStamp, value: numerical}. The temperature should be in Celsius. At the moment, we are supporting the Ecozen and UbiBot sensors APIs. If you have another type of sensors you would like to integrate with Coldtivate, please reach out to app@yourvcca.org.',
    },
    {
      id: 68,
      title: 'How do I connect the sensors in the room with the app?',
      role: [ERoles.OPERATOR],
      text: 'If there are temperature sensors in the room that can be connected to the Coldtivate app, please communicate with your responsible. Only user with a Registered employee role can link sensors to cooling units created in Coldtivate.',
    },
    {
      id: 34,
      title: 'How can I set the temperature of the cooling unit?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "To set the temperature of the cooling unit, please follow the procedure defined by your company. The app can be used to monitor, but not to update, the temperature in the cold room. However, if the app is not linked to sensors, it is important that you update the set temperature in the app. You can do so by clicking 'Enter temperature' inside the 'Cooling Units' > 'Room conditions' panel. Updating the temperature here will allow you to visualize the temperature evolution in the app and will enable accurate predictions on the remaining days the commodity in storage will be good for. If the app is linked to sensors, the option of changing the temperature in the app will be disabled, and the app will periodically extract this information from the sensors.",
    },
    {
      id: 35,
      title: 'How to contact a cooling user for the post check-out market survey?',
      role: [ERoles.OPERATOR],
      text: "In the 'History' tab you can see the list of the latest check-outs. You should contact each cooling user who did a check out to fill in the market survey, which can be accessed by clicking on the three dots next to the check out and selecting 'Fill in market survey'. By clicking on 'See details', you can check which commodity was in storage and the phone number of the user in case you want to contact him/her by phone. Else, you can wait until the next time the user comes to the cold room to store other produce. A red dot will identify the check outs in the History list for which the market survey has not been completed yet. You will be reminded about the check outs that need your attention in the notification panel 2 days after the check out date.",
    },
    {
      id: 69,
      title: 'What is the post check-out market survey and why should I fill it in?',
      role: [ERoles.COOLING_USER],
      text: "The market survey can be accessed by clicking on the three dots next to each check out in the 'History' tab and selecting 'Fill in market survey'. The survey is very short and asks for information about the selling price of the produce you had previously stored in the room, as well as about how much of it got spoiled. This information will be treated as confidential and solely used by the Coldtivate team to evaluate the impact of using cold storage. A red dot will identify the check outs for which the market survey has not been completed yet. You will be reminded about the check outs that need your attention in the notification panel 2 days after the check out date.",
    },
    {
      id: 37,
      title: 'How do I read the information of one item in the Dashboard?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "Bold in the middle is the ID of the storage item. The picture and the name below the ID represent the crop in storage. The number next to the basket icons tells you the number of crates inside the cooling unit. The number of days at the top right corner are the predicted remaining storage days (= days until the time to pick up). 'See detail' at the top right corner is a link to the detailed view of the storage item. Below, the name of the cooling user is displayed. The number of days at the bottom right shows how many days so far have they been stored inside the cooling unit. The price indicates the daily price for the whole storage item, i.e. the total price for all crates.",
    },
    {
      id: 38,
      title: 'What is the time to pick up?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'The time to pick up is the suggested number of days left for the cooling user to pick up a commodity. Afterward, the commodity would start to lose its marketability. A time to pick up equal to zero indicates that the user should come to collect the item in storage immediately and has up to 2 days to sell it to the market. It can be seen in the Dashboard (upper right) and in the detailed view for each storage item.',
    },
    {
      id: 39,
      title: 'How is the time to pick up calculated? By which factors is it influenced?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'Fresh vegetables and fruits are perishable, and how they lose their freshness after harvest is largely based on temperature. The time to pick up is, therefore, calculated based on the temperature of the corresponding cooling unit, and on the initial quality of the product when it is brought to the cooling unit. The parameters used in this calculation are unique to each commodity. You can have some insights on how perishability differs among different commodities in the Knowledge Hub.',
    },
    {
      id: 40,
      title: 'The time to pick up is 0 days but the produce is still looking good. Why?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'The time to pick up is the predicted value. Thus, it is possible that a cooling user can check out and still manage to sell well a storage item with time to pick up equal to 0 days. However, be aware that some quality loss is invisible to human eyes, and it is still a good practice to follow the indication given by the time to pick up as much as you can. The time to pick up prediction is especially accurate if the app is linked to temperature sensors. If you don’t have them in place, we advise you to install them in your cooling units. Please refer to the question ‘How do I connect the sensors in the room with the app’ for more information about the setup.',
    },
    {
      id: 41,
      title: 'The time to pick up is more than 0 days but the produce is almost spoiled. Why?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: 'The time to pick up is a predicted value. Thus, rare cases may occur, where the produce gets spoiled while the time to pick up is larger than 0. As quality decay of fresh produce largely depends on temperature, temperature data helps the prediction to be more accurate. For example, the issue may arise when there are no temperature sensors linked to the app, and the operator has set the wrong temperature in the room. If you don’t have temperature sensors in place, we advise you to install them in your cooling units. Please refer to the question ‘How do I connect the sensors in the room with the app’ for more information about the setup.',
    },
    {
      id: 70,
      title: 'The time to pick up is more than 0 days but the produce is almost spoiled. Why?',
      role: [ERoles.COOLING_USER],
      text: 'The time to pick up is a predicted value. Thus, rare cases may occur, where the produce gets spoiled while the time to pick up is larger than 0. As quality decay of fresh produce largely depends on temperature, temperature data helps the prediction to be more accurate. For example, the issue may arise when there are no temperature sensors linked to the app, and the operator has not regularly updated the temperature of the room in the app. Please notify the operator of the room in case this happens.',
    },
    {
      id: 42,
      title:
        'The room occupancy for one of the next days is red (less than 20%). What is this based on? Should I get worried?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: 'The occupancy is shown as red when more than 80% of the cooling unit capacity is utilized. The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate. As such, the red room occupancy is just a sign that the room is getting full. You do not need to worry but can take action accordingly. For example, consider contacting cooling users whose commodity in storage has the lowest time to pick up to advise them to check out soon. You can see an ordered list of the most urgent items to check out under ‘Dashboard’ when you order by time to pick up.',
    },
    {
      id: 43,
      title:
        'A cooling user is bringing to the room a commodity that is not on the list. Can I still check that in?',
      role: [ERoles.OPERATOR],
      text: "Sure, in this case you can start a check in selecting 'Other' from the commodity list.",
    },
    {
      id: 44,
      title:
        'In the Dashboard, each item has a colored bar. What does the color of the bar represent?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'The color represents the remaining days before the time to pick up. You will see the bar in red when it is less than 2 days, in yellow when less than 7 days, and green when more than 7 days. These values are specific for each storage item and are recalculated multiple times per day based on the temperature in the cooling unit. When no model for calculation is available, the color of the bar would be gray.',
    },
    {
      id: 45,
      title:
        'I have successfully completed a check in but cannot yet see the items in the dashboard. Why?',
      role: [ERoles.OPERATOR],
      text: 'The dashboard can take a moment to update. Also please verify that you are looking in the correct cooling unit. If you keep observing the issue, please report it to app@yourvcca.org.',
    },
    {
      id: 46,
      title:
        'I have successfully completed a check out but can still see the items in the dashboard. Why?',
      role: [ERoles.OPERATOR],
      text: 'The dashboard can take a moment to update. Also please verify that the items you checked-out were the correct ones, and that you are looking in the correct cooling unit. If you keep observing the issue, please report it to app@yourvcca.org.',
    },
    {
      id: 47,
      title: 'How can I check that the temperature sensor is working fine?',
      role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
      text: "After a registered employee has enabled a sensor connection to a given cooling unit, the button for manual temperature input in the 'Cooling Units' > 'Room conditions' panel will be grayed-out. The sensor data is fetched every 1 hour, so if the sensor is working properly you should see the temperature plot with new points every hour.",
    },
    {
      id: 48,
      title: 'I got a notification that the sensor is not working. What should I do?',
      role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
      text: "The notification is sent after not receiving data from the sensor for more than 12 hours, and it means the set temperature in the 'Cooling Units' > 'Room conditions' panel is now being used. The app will try to reconnect to the sensor every 1 hour, thus we advise to wait a few hours in case this is a connectivity issue. If there is no new sensor data for several hours or days, the problem might be on the hardware side, for example, the sensor might have run out of battery.",
    },
    {
      id: 49,
      title: 'How can the time to pick up be calculated if there are no sensors?',
      role: [ERoles.EMPLOYEE],
      text: 'When no sensors are connected to the app, the model to calculate the time to pick up relies on the temperature set by the Operator. That is also the reason why the Operator is prompted to input a new set temperature at every new check in and check out. For the model to be accurate, it is crucial that the temperature is up-to-date. Please instruct the operators at your cooling unit about this important step.',
    },
    {
      id: 50,
      title: 'Every time I start a check-in, I get a temperature alert popup. Why?',
      role: [ERoles.OPERATOR],
      text: 'This pop up is a reminder for you to inform the app about the correct set temperature of the cooling room in case no sensors are in place (or if they are not working properly). You should check whether the value indicated in the popup is the same as the one you can read in the control panel at the room. If this is not the case, you should update the temperature. Else, you can confirm and continue with the check in. Having an updated set temperature is very important for the model that calculates the time to pick up to be accurate.',
    },
    {
      id: 51,
      title: 'Every time I complete a check-out, I get a temperature alert popup. Why?',
      role: [ERoles.OPERATOR],
      text: "The temperature of a cooling unit should be set depending on what commodities are in storage, because different commodities have different optimal temperatures (you can see an overview in the Knowledge Hub). The popup appearing after a check out has been completed shows a summary of the commodities that are left in the room and informs you about the optimal temperature for each of them. In this way, you can make an informed decision about whether the temperature in the room should be changed. You can also find this information by going to 'Cooling units' -> 'Crates info'.",
    },
    {
      id: 52,
      title:
        'Why do I need to ask a cooling user to fill in a questionnaire before he/she can check in the first crate?',
      role: [ERoles.OPERATOR],
      text: 'The team developing the app is collecting some basic information about the cooling users when they first start using the room as baseline data that will be compared with the data acquired by the app. The sole intent is to improve the app design and cold room utilization.',
    },
    {
      id: 71,
      title: 'Why do I need to fill in a questionnaire when I register on the app?',
      role: [ERoles.COOLING_USER],
      text: 'The team developing the app is collecting some basic information about the cooling users when they first start using the room as baseline data that will be compared with the data acquired by the app. The sole intent is to improve the app design and cold room utilization.',
    },
    {
      id: 53,
      title: 'Why do I need to ask cooling users about the selling price of each storage item?',
      role: [ERoles.OPERATOR],
      text: 'You will be asked to contact a cooling user who has recently checked out some produce from the room and ask about where and for which price they have sold the item that was stored in the room. This information will help the team developing the app to validate and improve the accuracy of the market prices forecasts provided.',
    },
    {
      id: 54,
      title: "I don't understand parts of the app. Who should I contact?",
      role: [ERoles.EMPLOYEE],
      text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If you would like to get in contact with the app support team, please send an email to app@yourvcca.org.',
    },
    {
      id: 55,
      title: "I don't understand parts of the app. Who should I contact?",
      role: [ERoles.OPERATOR],
      text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If your question is still unanswered, please contact the Registered employee you are reporting to.',
    },
    {
      id: 73,
      title: "I don't understand parts of the app. Who should I contact?",
      role: [ERoles.COOLING_USER],
      text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If your question is still unanswered, please contact the operator of a cold room, or write to app@yourvcca.org',
    },
    {
      id: 56,
      title: 'I found a bug in the app. Who should I contact?',
      role: [ERoles.EMPLOYEE],
      text: 'Please make sure you have the latest version of the app installed. If the problem persists, please notify the app support team by sending an email to app@yourvcca.org or by filling in the feedback form: https://forms.gle/ceohKHT2QCcE3rFs5 .',
    },
    {
      id: 57,
      title: 'Something is not working properly in the app. Who should I contact?',
      role: [ERoles.OPERATOR],
      text: 'Please make sure you have the latest version of the app installed. If the problem persists, please contact the Registered employee you are reporting to and / or notify the app support team by sending an email to app@yourvcca.org or by filling in the feedback form: https://forms.gle/2gKVzZjkJSPqEAan9 .',
    },
    {
      id: 74,
      title: 'Something is not working properly in the app. Who should I contact?',
      role: [ERoles.COOLING_USER],
      text: 'Please make sure you have the latest version of the app installed. If the problem persists, please contact the operator of a cold room and / or notify the app support team by sending an email to app@yourvcca.org.',
    },
    {
      id: 58,
      title: 'I want to provide feedback about my experience with the app. Who should I contact?',
      role: [ERoles.EMPLOYEE],
      text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org or submit your feedback via the form: https://forms.gle/ceohKHT2QCcE3rFs5 .',
    },
    {
      id: 86,
      title: 'I want to provide feedback about my experience with the app. Who should I contact?',
      role: [ERoles.OPERATOR],
      text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org or submit your feedback via the form: https://forms.gle/2gKVzZjkJSPqEAan9.',
    },
    {
      id: 87,
      title: 'I want to provide feedback about my experience with the app. Who should I contact?',
      role: [ERoles.COOLING_USER],
      text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org.',
    },
    {
      id: 17,
      title: 'I am in an area where there is low internet connection: Can I still use the app?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'Currently, only the Knowledge Hub section is available offline. Additional parts of the app will soon be accessible even without an internet connection.',
    },
    {
      id: 60,
      title: "Which prices are displayed when clicking on the 'Market prices' icon?",
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'In this tab, you can see the market price predictions either in a plot or in a table format. The Price Trend page allows for visualizing the last month of data and the 14-days forecast for a specific market and commodity (in India) or a monthly forecast per state (in Nigeria). The Price Ranking page allows to visualize all market prices forecasts ordered from highest to lowest, and with the posibility to filter by date, state, district and market (in India).',
    },
    {
      id: 61,
      title: "Why are some states and markets missing in the 'Market prices' section?",
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'Due to data availability, the model has only been implemented for a few commodities in some selected states in India and Nigeria. The Market Prices tab only lists market, commodities and states for which a forecast is available.',
    },
    {
      id: 62,
      title: 'How are the future market prices calculated?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'A machine learning model is trained on historical market price data and other data such as currency conversion rate and petrol price, to make forecasts of future market prices.',
    },
    {
      id: 75,
      title: 'I would like to delete my account. What should I do?',
      role: [ERoles.EMPLOYEE],
      text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you are the last Registered Employee of the company, this action will delete the company. If there are pending checkins, you will not be able to delete your account until all the crates have been checked-out in the app by one of your operators.",
    },
    {
      id: 76,
      title: 'I would like to delete my account. What should I do?',
      role: [ERoles.OPERATOR],
      text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you are the last Operator assigned to one of the rooms where there are open check-ins, you cannot delete your account until a registered employee assigns another operator to the room, or all crates have been checked-out in the app.",
    },
    {
      id: 77,
      title: 'I would like to delete my account. What should I do?',
      role: [ERoles.COOLING_USER],
      text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you have open check-ins in any of the rooms, you can not delete your account until all crates are checked-out from the rooms. Please make sure to collect your crates at the room! In case you think there are pending crates in the app that you have already removed, please communicate with the room's operator to sort it out.",
    },
    {
      id: 78,
      title: 'How can I delete a cooling unit or a location?',
      role: [ERoles.EMPLOYEE],
      text: "You can delete cooling units and locations going to 'Menu' -> 'Management' -> 'Cooling Units' / 'Locations' and clicking Delete. You will only be able to do so if there are no pending check-ins in the rooms. Else, please communicate to the operators to complete the check-outs before you attempt to delete the rooms and locations.",
    },
    {
      id: 79,
      title: 'How can I delete another registered employee or an operator from my company?',
      role: [ERoles.EMPLOYEE],
      text: "You are not allowed to delete other users from the app. However, you can unassign operators from your rooms by navigating to 'Menu' -> 'Management' -> 'Operators'. If you still want to enitrely remove the user so that they don't have access to your company, please write an email to app@yourvcca.org and explain why this is needed.",
    },
    {
      id: 80,
      title: 'How can I delete a cooling user from the list?',
      role: [ERoles.OPERATOR],
      text: "To delete a cooling user from the list, navigate to 'Management' -> 'Cooling Users', click on the cooling user name and then the button 'Delete'. Please note that only users with no pending check-ins can be deleted! If there are pending check-ins, please contact the user to pick up the produce. Note that this action cannot be reversed! If the user has a smartphone, this operation will remove him/her from your list, but the user will still be able to use Coldtivate. If the user has no smartphone, this operation deletes his/her account and frees the associated phone number.",
    },
    {
      id: 81,
      title: 'Where can I monitor whether the operators have used the app recently?',
      role: [ERoles.EMPLOYEE],
      text: "To check the last time the operators and other registered employees have logged in into the app, you can navigate to 'Menu' -> 'Management' -> ERoles.OPERATOR / ERoles.EMPLOYEE. The date and time you see next to the name are the last login date and time.",
    },
    {
      id: 82,
      title: 'Where can I monitor the revenue generated by each room and other usage statistics?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "You can navigate to 'Menu' -> 'Management' -> 'Revenue Analysis', select the cooling units and the time interval of interest, and you will see the total revenue associated with the check-out from these rooms. You can also filter by cooling user, payment method, and crop. To visualise summary statistics of your check-ins per room (as number of users, total number of crates, etc), you can navigate to 'Menu' -> 'Management' -> 'Usage Analysis'. Also here you can filter by date, cooling user, and crop. Finally, to monitor the total number of crates, weight, and optimal temperatures for the crops currently in the room, you can navigate to 'Cooling units' -> 'Crates info'.",
    },
    {
      id: 83,
      title:
        'How can I find out who is the contact person for a cooling unit where my produce is stored?',
      role: [ERoles.COOLING_USER],
      text: 'By clicking on an item in the dashboard, you can see the name and the contact number of the operator who did the check in for you. You can copy the number to clipboard and contact the operator per phone or sms.',
    },
    {
      id: 84,
      title: 'I have received a notification. What should I do?',
      role: [ERoles.COOLING_USER],
      text: "You might receive two type of notifications: first, the app can inform you about the fact that some of the crates you have stored are about to get spolied. We advise you to collect the crates from the room as fast as possible. Another notification you might receive is to remind you to complete the post check-out market survey. The check-outs for which the market survey has not be filled in are marked by a red dot in the 'History' tab. The survey is very quick to complete and asks you about the price at which the produce you had in storage was sold, and whether any part of the produce was spoiled after check-out. This information is very valuable for the Coldtivate team to monitor the benefit of using cold rooms compared to storing the produce outside.",
    },
    {
      id: 85,
      title: 'What is displayed on the map of cooling units?',
      role: [ERoles.COOLING_USER],
      text: 'On the map you can visualize your location (you will be asked for permission for Coldtivate to access your location), hte location of the cooling units around you, and some information about the units (single or multicommodity, company, pricing).',
    },
  ],
  hi: [
    {
      id: 1,
      title: 'मुझे ऐप का उपयोग क्यों करना चाहिए?',
      role: [ERoles.AUTH],
      text: 'ये ऐप शीत कक्ष प्रदाताओं को शीत कक्ष में उनके दिन-प्रतिदिन के कार्यों में सहायता करने के लिए बनाया गया है । ऐप में एक डिजिटल भंडार,भंडारण में वस्तुओं की दूरस्थ निगरानी और कमरे का तापमान (यदि सेंसर उपलब्ध हैं), और कितने दिनों तक भंडारण में वस्तुऐं अच्छी रहेंगी, इसके बारे में सुचना प्रप्त की जा शक्ति है । इसमें ज्ञान केंद्र भी शामिल है, जो इष्टतम भंडारण तापमान और भंडारण जीवन पर वस्तु-विशिष्ट अनुशंसाए प्रदान करता है। इस ऐप का अगला संस्करण तैयार किया जा रहा है, जिसका उपयोग, कूलिंग उपयोगकर्ता अपने द्वारा कोल्ड स्टोरेज में लाए गए उत्पाद की निगरानी के लिए कर सकते हैं, अच्छी भंडारण तारिको के बारे में सूचित कर सकते हैं, और बेचने के लिए सर्वोत्तम समय और स्थान और ठंडे कमरे के स्थानों और संभावित लाभ के बारे में जानकारी प्राप्त कर सकते हैं।',
    },
    {
      id: 2,
      title: 'ऐप का उपयोग कौन कर सकता है?',
      role: [ERoles.AUTH],
      text: 'ऐप का इस्तेमाल दुनिया भर की कोल्ड स्टोरेज कंपनियों के कर्मचारी और उपयोगकर्ता कर सकते हैं। अगले संस्करण में, शीत कक्ष उपयोगकर्ता भी ऐप में साइन इन कर सकेंगे। पूरे ऐप में, तीन उपयोगकर्ता भूमिकाएँ हैं: (i) पंजीकृत कर्मचारी: कोल्ड रूम प्रदाता प्रबंधन टीम का हिस्सा। एक व्यक्ति जो भंडारण की स्थापना और प्रबंधन के लिए जिम्मेदार है, वह स्थान पर भौतिक रूप से उपस्थित हुए बिना, जमीन पर ऑपरेटरों की गतिविधियों को देखने का प्रभारी है। उदाहरण के लिए: एक कंपनी के सीईओ, सीएफओ, आदि। (ii) परिचालक: एक कर्मचारी जो शीत कक्ष में शारीरिक रूप से उपस्थित होता है और उसके चेक-इन, चेक-आउट संचालन का प्रबंधन करता है। यह व्यक्ति कोल्ड रूम के उपयोगकर्ताओं के सीधे संपर्क में रहता है, और कंपनी के पंजीकृत कर्मचारी को रिपोर्ट करता है। (iii) कूलिंग उपयोगकर्ता: कोल्ड रूम उपयोगकर्ता (किसान, व्यापारी, खुदरा विक्रेता, आदि हो सकते हैं)। ऐप के इस संस्करण के लिए, कोल्ड रूम उपयोगकर्ताओं की ओर से सभी संचालन परिचालक करेगा, लेकिन अगले संस्करण में कूलिंग उपयोगकर्ता  स्मार्टफोन से उपयोगकर्ता  के तौर पर लॉग इन कर सकेंगे।',
    },
    {
      id: 3,
      title: 'मैं एक पंजीकृत कर्मचारी के रूप में कैसे साइन अप कर सकता हूं?',
      role: [ERoles.AUTH],
      text: 'यदि आप साइन अप करने वाले अपनी कंपनी के पहले कर्मचारी हैं, तो आप “एक कंपनी के रूप में साइन अप करें” बटन पर क्लिक कर सकते हैं और अपनी कंपनी और खुद को पंजीकृत करने के लिए निम्न लिखित चरणों का पालन कर सकते हैं (व्यक्तिगत विवरण और पासवर्ड सहित)। एक बार जब आप सफलतापूर्वक साइन अप कर लेते हैं, तो आप ऐप में एक पंजीकृत कर्मचारी के रूप में लॉग इन कर सकते हैं और अन्य पंजीकृत कर्मचारियों को अपनी कंपनी में शामिल होने के लिए एक एसएमएस आमंत्रण भेज सकते हैं।',
    },
    {
      id: 4,
      title: 'मैं एक परिचालक के रूप में कैसे साइन अप कर सकता हूं?',
      role: [ERoles.AUTH],
      text: 'साइन अप करने के लिए,आपको एक पंजीकृत कर्मचारी द्वारा आमंत्रित किया जाना चाहिए। आपको एक सक्रियण लिंक के साथ एक एसएमएस प्राप्त होगा,जहां से आप अपना व्यक्तिगत विवरण और पासवर्ड निर्धारित कर सकते हैं।',
    },
    {
      id: 5,
      title: 'मैं कूलिंग उपयोगकर्ता के रूप में कैसे साइन अप कर सकता हूं?',
      role: [ERoles.AUTH],
      text: 'ऐप के इस संस्करण में, परिचालक, कूलिंग उपयोगकर्ता प्रोफाइल बना सकते हैं, जो चेक-इन शुरू करने के लिए आवश्यक हैं। कूलिंग उपयोगकर्ता को एक फोन नंबर देना होगा, जिसका इस्तेमाल परिचालक जरूरत पड़ने पर कूलिंग उपयोगकर्ता से संपर्क करने के लिए करेगा। कोई पासवर्ड की आवश्यकता नहीं है। ऐप के भविष्य के संस्करण में, स्मार्टफोन के साथ कूलिंग उपयोगकर्ता ऐप उपयोगकर्ताओं के रूप में साइन अप करने में सक्षम होंगे।',
    },
    {
      id: 6,
      title: 'मैं एक उपयोगकर्ता के रूप में पंजीकरण पूरा नहीं कर पा रहा हु । मुझे क्या करना चाहिए?',
      role: [ERoles.AUTH],
      text: 'पंजीकरण पूरा करने के लिए, कृपया सुनिश्चित करें कि निम्नलिखित शर्तें पूरी होती हैं: (i) आप सही देश कोड के साथ एक फोन नंबर दर्ज कर रहे हैं (उदाहरण के लिए भारत के लिए +91); (ii) आपके द्वारा प्रदान किया गया फ़ोन नंबर किसी अन्य उपयोगकर्ता को पंजीकृत करने के लिए उपयोग नहीं किया गया है; (iii) आपके द्वारा दर्ज किए जा रहे पासवर्ड में कम से कम 8 वर्ण हैं, और कम से कम: एक बड़ा अक्षर, एक छोटा अक्षर, एक संख्या और एक विशेष वर्ण है ; (iv) आप जो पासवर्ड दर्ज कर रहे हैं वे बराबर हैं - आप पासवर्ड प्रकट करने के लिए आंखों के प्रतीक पर क्लिक कर सकते हैं और जांच सकते हैं कि वे बराबर हैं या नहीं।',
    },
    {
      id: 7,
      title: 'मेरे पास फोन नहीं है लेकिन मैं ऐप का इस्तेमाल करना चाहता हूं। मुझे क्या करना चाहिए?',
      role: [ERoles.AUTH],
      text: "यदि आप एक पंजीकृत कर्मचारी या परिचालक हैं,तो आपको साइन अप करने के लिए एक वैध फ़ोन नंबर प्रदान करना होगा। ऐप को सही तरीके से इस्तेमाल करने के लिए स्मार्टफोन की जरूरत होती है। यदि आप कूलिंग उपयोगकर्ता हैं और आपके पास फोन नहीं है,तो हम आपको एक वैध फोन नंबर प्रदान करने की भी सलाह देते हैं, ताकि जरूरत पड़ने पर परिचालक आपसे संपर्क कर सके। यदि आपके पास अपना फोन नंबर नहीं है तो आप परिवार के किसी सदस्य या मित्र का फोन नंबर दे सकते हैं। ऐप के इस संस्करण में, आप 'बिना फ़ोन के उपयोगकर्ता' के रूप में चेक इन करके बिना फ़ोन नंबर के भी भंडारण में उत्पाद रख सकते है।",
    },
    {
      id: 8,
      title: 'एक पंजीकृत कर्मचारी के रूप में लॉग इन करने के लिए कौन से विवरण की आवश्यकता है?',
      role: [ERoles.AUTH],
      text: 'पंजीकृत कर्मचारी ईमेल या फोन नंबर और उनके पासवर्ड से लॉग इन कर सकते हैं।',
    },
    {
      id: 9,
      title: 'परिचालक के रूप में लॉग इन करने के लिए कौन से विवरण की आवश्यकता है?',
      role: [ERoles.AUTH],
      text: 'परिचालक अपने फोन नंबर और पासवर्ड से लॉग इन कर सकते हैं।',
    },
    {
      id: 10,
      title: 'कूलिंग उपयोगकर्ता के रूप में लॉग इन करने के लिए किन विवरणों की आवश्यकता है?',
      role: [ERoles.AUTH],
      text: 'ऐप के इस संस्करण में कूलिंग उपयोगकर्ता को लॉग इन करने की आवश्यकता नहीं है। बाद के संस्करण में कूलिंग उपयोगकर्ता अपने फोन नंबर और पासवर्ड से लॉग इन कर सकेंगे।',
    },
    {
      id: 12,
      title: 'मुझे एसएमएस में कोई आमंत्रण नहीं मिला है। मुझे क्या करना चाहिए?',
      role: [ERoles.AUTH],
      text: 'पंजीकृत कर्मचारियों और परिचालक को उसी कंपनी के पंजीकृत कर्मचारी द्वारा ऐप में शामिल होने के लिए आमंत्रित किया जा सकता है। यदि पंजीकृत कर्मचारी ने आपको आमंत्रित किया है, लेकिन आपको कोई एसएमएस प्राप्त नहीं हुआ है, तो कृपया सीधे पंजीकृत कर्मचारी से संपर्क करें। सामान्य कारण हैं: (i) गलत नंबर टाइप किया गया (ध्यान दें कि एक देश का कॉलिंग कोड की आवश्यकता है); (ii) आप पहले ही उस नंबर से जुड़े निमंत्रण को स्वीकार कर चुके हैं। एक फ़ोन नंबर का उपयोग केवल एक उपयोगकर्ता के लिए किया जा सकता है।',
    },
    {
      id: 11,
      title: 'मैं अपना पासवर्ड भूल गया। मुझे क्या करना चाहिए?',
      role: [ERoles.AUTH],
      text: "यदि आपने अपना पासवर्ड खो दिया है, तो आप साइन इन करते समय 'पासवर्ड भूल गए' पर क्लिक करके अपना खाता पुनर्स्थापित कर सकते हैं, अपना फ़ोन नंबर दर्ज करें, और आपको एक नया पासवर्ड सेट करने के लिए एक लिंक के साथ एक एसएमएस प्राप्त होगा।",
    },
    {
      id: 36,
      title: 'ज्ञान केंद्र क्या है?',
      role: [ERoles.AUTH],
      text: "स्टोरेज मैनेजर' के 'इतिहास' टैब में आप नवीनतम चेक-आउट की सूची देख सकते हैं। आपको बाजार सर्वेक्षण को भरने के लिए चेक आउट करने वाले प्रत्येक कूलिंग उपयोगकर्ता से संपर्क करना चाहिए, जिसे चेक आउट के आगे तीन बिंदुओं पर क्लिक करके और 'बाजार सर्वेक्षण में भरें' का चयन करके पहुँचा जा सकता है। 'विवरण देखें' पर क्लिक करके, आप जांच सकते हैं कि कौन सी वस्तु भंडारण में थी और यदि आप उससे फोन पर संपर्क करना चाहते हैं तो उपयोगकर्ता का फोन नंबर। अन्यथा, आप तब तक प्रतीक्षा कर सकते हैं जब तक उपयोगकर्ता अगली बार अन्य उत्पादों को स्टोर करने के लिए ठंडे कमरे में नहीं आता। एक लाल बिंदु इतिहास सूची में चेक आउट की पहचान करेगा जिसके लिए बाजार सर्वेक्षण अभी तक पूरा नहीं हुआ है। चेक आउट की तारीख के 2 दिन बाद अधिसूचना पैनल में आपको उन चेक आउट के बारे में याद दिलाया जाएगा जिन पर आपको ध्यान देने की आवश्यकता है।",
    },
    {
      id: 13,
      title: 'मैं अपनी प्रोफ़ाइल कैसे संपादित कर सकता हूँ?',
      role: [ERoles.EMPLOYEE],
      text: "मेनू' -> 'खाता विवरण' पर क्लिक करके, आप अपनी प्रोफ़ाइल देख सकते हैं और विवरण संपादित कर सकते हैं (प्रथम और अंतिम नाम, फ़ोन नंबर, ईमेल और लिंग)। यहां आप ऐप की भाषा भी बदल सकते हैं । अपनी कंपनी, स्थानों और कूलिंग इकाइयों का विवरण बदलने के लिए, 'मेनू' -> 'प्रबंधन' पर जाए, और फिर उस मेनू आइटम का चयन करें जिसे आप बदलना चाहते हैं।",
    },
    {
      id: 14,
      title: 'मैं अपनी प्रोफ़ाइल कैसे संपादित कर सकता हूँ?',
      role: [ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "मेनू' -> 'खाता विवरण' पर क्लिक करके, आप अपनी प्रोफ़ाइल देख सकते हैं और विवरण संपादित कर सकते हैं (प्रथम और अंतिम नाम, फ़ोन नंबर, ईमेल और लिंग)। यहां आप ऐप की भाषा भी बदल सकते हैं ।",
    },
    {
      id: 15,
      title: 'मैं परिचालक को कूलिंग इकाइयों के लिए कैसे नियुक्त कर सकता हूं?',
      role: [ERoles.EMPLOYEE],
      text: "एक परिचालक को शीतलन इकाई से जोड़ने के तीन तरीके हैं। जब आप किसी ऑपरेटर को आमंत्रण भेज रहे हों तो आप उसे एक कूलिंग यूनिट (या एक से अधिक) नियुक्त कर सकते हैं। अन्यथा, आप किसी दिए गए ऑपरेटर से जुड़ी कूलिंग इकाइयों को 'प्रबंधन' -> 'ऑपरेटर' पर नेविगेट करके, ऑपरेटर का चयन करके और फिर 'कूलिंग यूनिट का चयन करें' पर क्लिक करके संशोधित कर सकते हैं। अंत में, 'मैनेजमेंट' -> 'कूलिंग यूनिट्स' में कूलिंग यूनिट बनाते समय, आप इसे ऑपरेटरों को भी असाइन कर सकते हैं। बाहर निकलने से पहले अपने परिवर्तनों को सहेजना याद रखें!",
    },
    {
      id: 16,
      title:
        'एक कूलिंग उपयोगकर्ता कोल्ड रूम में आता है लेकिन उसके पास फोन नहीं है। क्या मैं अब भी उसका पंजीकरण करा सकता हूँ?',
      role: [ERoles.OPERATOR],
      text: "हां, आप 'एक फोन के बिना उपयोगकर्ता' नाम के कूलिंग उपयोगकर्ता का इस्तेमाल करके उस व्यक्ति के लिए चेक इन शुरू कर सकते हैं। क्यूं की कई लोग चेक इन के लिए इस खाते का उपयोग कर सकते हैं, इसलिए प्रत्येक टोकरे के मालिक की पहचान करने के लिए कमरे के क्रेट में एक नाम टैग जोड़ना सुनिश्चित करें।",
    },
    {
      id: 18,
      title: 'मैं अपनी कंपनी को कैसे पंजीकृत करूं?',
      role: [ERoles.EMPLOYEE],
      text: "अपनी कंपनी को पंजीकृत करने के लिए, स्वागत स्क्रीन पर 'कंपनी के रूप में साइन अप करें' चुनें और आवश्यक जानकारी भरें। एक पासवर्ड दर्ज करें फिर 'साइन अप' पर क्लिक करें और अब आप अगले चरण के लिए तैयार हैं!",
    },
    {
      id: 19,
      title: 'मैं अपनी कंपनी के लिए एक नया स्थान कैसे पंजीकृत करूं?',
      role: [ERoles.EMPLOYEE],
      text: "प्रत्येक कूलिंग इकाई को एक स्थान पर बनाने की आवश्यकता होती है (और एक ही स्थान के लिए कई कूलिंग इकाइयाँ बनाई जा सकती हैं)। अपनी कंपनी के लिए एक नया स्थान जोड़ने के लिए, मेनू में 'प्रबंधन' > 'स्थान' चुनें। नया स्थान जोड़ने के लिए ऊपरी दाएं कोने पर '+' पर क्लिक करें। आवश्यक जानकारी भरें। पुष्टि करने के लिए 'जोड़ें' पर क्लिक करें।",
    },
    {
      id: 20,
      title: 'मैं अपनी कंपनी के लिए एक नई कूलिंग इकाई कैसे पंजीकृत करूं?',
      role: [ERoles.EMPLOYEE],
      text: "अपनी कंपनी के लिए एक नई कूलिंग इकाई पंजीकृत करने के लिए, आपको कम से कम एक स्थान बनाना होगा। फिर, मेनू में 'प्रबंधन' > 'कूलिंग इकाइयाँ' चुनें। नई कूलिंग इकाई जोड़ने के लिए ऊपरी दाएं कोने पर '+' पर क्लिक करें। आवश्यक जानकारी भरें। पुष्टि करने के लिए 'जोड़ें' पर क्लिक करें।",
    },
    {
      id: 21,
      title:
        'मैं अपनी कंपनी के अन्य पंजीकृत कर्मचारियों को ऐप के लिए पंजीकरण करने के लिए कैसे आमंत्रित करूं?',
      role: [ERoles.EMPLOYEE],
      text: "अपनी कंपनी के लिए अन्य पंजीकृत कर्मचारियों को आमंत्रित करने के लिए, मेनू में 'प्रबंधन' > 'पंजीकृत कर्मचारी' चुनें । जिस कर्मचारी को आप आमंत्रित करना चाहते हैं उसका मोबाइल नंबर जोड़ने के लिए ऊपरी दाएं कोने पर '+' पर क्लिक करें। पुष्टि करने के लिए 'आमंत्रित करें' पर क्लिक करें: आपके सहकर्मी को एक लिंक के साथ एक एसएमएस प्राप्त होगा जो उसे सीधे साइन अप स्क्रीन पर ले जाएगा।",
    },
    {
      id: 22,
      title: 'मैं ऐप के लिए पंजीकरण करने के लिए शीत भंडारण परिचालक को कैसे आमंत्रित करूं?',
      role: [ERoles.EMPLOYEE],
      text: "अपनी कूलिंग इकाइयों के लिए परिचालक को आमंत्रण भेजने के लिए, मेनू में 'प्रबंधन' > 'परिचालकर' चुनें । जिस परिचालक को आप आमंत्रित करना चाहते हैं उसका टेलीफोन नंबर जोड़ने के लिए ऊपरी दाएं कोने पर '+' पर क्लिक करें। पुष्टि करने के लिए 'आमंत्रित करें' पर क्लिक करें: ऑपरेटर को एक लिंक के साथ एक संदेश प्राप्त होगा जो उसे सीधे साइन अप स्क्रीन पर ले जाएगा।",
    },
    {
      id: 23,
      title: 'मैं कूलिंग इकाई के तापमान की निगरानी कैसे करूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "एक विशिष्ट शीतलन इकाई के तापमान की निगरानी के लिए नीचे दाएं कोने पर 'कूलिंग यूनिट्स' बटन पर क्लिक करें, 'कमरे की स्थिति' पर नेविगेट करें, और ड्रॉपडाउन से रुचि की इकाई का चयन करें। इस पैनल में, आप समय के साथ तापमान के साथ एक ग्राफ देखेंगे - आप पुराने डेटा बिंदुओं को देखने के लिए स्क्रॉल कर सकते हैं। यदि आपके पास ऐप से जुड़े सेंसर हैं, तो आप यहां वास्तविक कमरे का तापमान देख पाएंगे। अन्यथा, ग्राफ़ उन तापमानों को दिखाएगा जिन्हें आपने ऐप के भीतर मैन्युअल रूप से सेट किया है।",
    },
    {
      id: 64,
      title: 'मैं कूलिंग इकाई के तापमान की निगरानी कैसे करूं?',
      role: [ERoles.COOLING_USER],
      text: "किसी विशिष्ट कूलिंग यूनिट के तापमान की निगरानी के लिए नीचे दाएं कोने पर 'कूलिंग यूनिट्स' बटन पर क्लिक करें, 'रूम कंडीशंस' पर नेविगेट करें, और ड्रॉपडाउन से कूलिंग यूनिट का चयन करें। इस पैनल में, आपको समय के साथ तापमान के साथ एक ग्राफ़ दिखाई देगा - आप पुराने डेटा बिंदुओं को देखने के लिए स्क्रॉल कर सकते हैं। अगर कमरे में ऐप से जुड़े सेंसर हैं, तो आप यहां वास्तविक कमरे का तापमान देख पाएंगे। अन्यथा, ग्राफ़ तापमान दिखाएगा जो रूम ऑपरेटर ने ऐप के भीतर मैन्युअल रूप से सेट किया है।",
    },
    {
      id: 24,
      title: 'मैं कूलिंग इकाई के अधिभोग की निगरानी कैसे करूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "किसी विशिष्ट शीतलन इकाई के अधिभोग को प्रबंधित करने के लिए स्क्रीन के नीचे 'कूलिंग यूनिट्स' आइकन पर क्लिक करें, 'प्लानर' पर नेविगेट करें, और ड्रॉपडाउन से रुचि की इकाई का चयन करें। यहां आप वर्तमान अधिभोग (शीर्ष) और अगले 7 दिनों (नीचे) के लिए अनुमानित अधिभोग देख सकते हैं। भावी अधिभोग के बारे में जानकारी उन दिनों की संख्या पर आधारित होती है, जब प्रत्येक उपयोगकर्ता चेक-इन के समय भंडारण में नियोजित दिनों के रूप में घोषित करता है। सावधान रहें कि यह केवल एक अनुमान है और गलत भी हो सकता है।",
    },
    {
      id: 65,
      title: 'मैं कूलिंग इकाई के अधिभोग की निगरानी कैसे करूं?',
      role: [ERoles.COOLING_USER],
      text: "किसी विशिष्ट कूलिंग यूनिट के अधिभोग की निगरानी के लिए स्क्रीन के नीचे 'कूलिंग यूनिट्स' आइकन पर क्लिक करें, 'प्लानर' पर नेविगेट करें, और ड्रॉपडाउन से कूलिंग यूनिट का चयन करें। यहां आप वर्तमान अधिभोग (शीर्ष) और अगले 7 दिनों के लिए अनुमानित अधिभोग (नीचे) देख सकते हैं। भविष्य के अधिभोग के बारे में जानकारी प्रत्येक उपयोगकर्ता द्वारा चेक-इन पर भंडारण में नियोजित दिनों के रूप में घोषित दिनों की संख्या पर आधारित है। सावधान रहें कि यह केवल एक अनुमान है और गलत हो सकता है।",
    },
    {
      id: 25,
      title: 'मैं कैसे देख सकता हूँ कि कौन-सी वस्तुएँ एक कमरे में संग्रहीत हैं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "स्क्रीन के नीचे 'डैशबोर्ड' आइकन पर क्लिक करें और कूलिंग यूनिट में सभी संग्रहीत वस्तुओं की सूची देखने के लिए ड्रॉपडाउन से ब्याज की शीतलन इकाई का चयन करें।",
    },
    {
      id: 26,
      title: 'मैं कूलिंग इकाई के पिछले चेक-इन और चेक-आउट कैसे देख सकता हूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "कूलिंग यूनिट के पिछले चेक-आउट देखने के लिए 'इतिहास' आइकन पर क्लिक करें: पिछले चेक-इन और लेन-देन विवरण के साथ चेक-आउट प्रदर्शित होते हैं। यदि कोई विशिष्ट चेक-आउट लेन-देन रुचि का है, तो खोज फ़ंक्शन इसे खोजने में आपकी सहायता कर सकता है!",
    },
    {
      id: 28,
      title: 'ऐप में परिचालक कौन से मुख्य कार्य कर सकता है?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: 'परिचालक: नए कूलिंग उपयोगकर्ताओं को पंजीकृत कर सकता है, चेक-इन शुरू कर सकता है, भंडारण और कमरे में रहने वाली वस्तुओं की निगरानी कर सकता है, चेक-आउट शुरू कर सकता है और कूलिंग इकाई के तापमान की निगरानी कर सकता है जिसके लिए वह जिम्मेदार है।',
    },
    {
      id: 29,
      title: 'मैं नए कूलिंग उपयोगकर्ता कैसे पंजीकृत कर सकता हूं?',
      role: [ERoles.OPERATOR],
      text: "एक नया कूलिंग उपयोगकर्ता पंजीकृत करने के लिए, मेनू में 'प्रबंधन'> 'कूलिंग उपयोगकर्ता' पर नेविगेट करें। आप जिस कूलिंग यूजर को आमंत्रित करना चाहते हैं उसका नाम, लिंग और मोबाइल नंबर जोड़ने के लिए ऊपरी दाएं कोने पर '+' पर क्लिक करें। यदि उपयोगकर्ता के पास अपना नंबर नहीं है, तो किसी अन्य व्यक्ति (जैसे मित्र, रिश्तेदार) की संख्या का उपयोग किया जा सकता है। अंत में, 'माता-पिता का नाम' क्षेत्र भरें (इस क्षेत्र का उपयोग समान नाम वाले उपयोगकर्ताओं के बीच अंतर करने के लिए किया जाता है)। पुष्टि करने के लिए 'परिवर्तन सहेजें' पर क्लिक करें। पंजीकरण पूरा करने के लिए, आपको कूलिंग उपयोगकर्ता से कुछ प्रश्न पूछकर एक संक्षिप्त सर्वेक्षण भरना होगा।",
    },
    {
      id: 30,
      title:
        'कूलिंग उपयोगकर्ता के पास पंजीकरण के समय, सर्वेक्षण के सवालों के जवाब देने का समय नहीं है। मुझे क्या करना चाहिए?',
      role: [ERoles.OPERATOR],
      text: "आप 'बाद में पूर्ण करें' पर क्लिक करके सर्वेक्षण प्रश्नों को छोड़ सकते हैं। इस मामले में, जब आप पहली बार उस कूलिंग उपयोगकर्ता के लिए चेक इन बना रहे हैं, तो आपको सर्वेक्षण पूरा करने के लिए प्रेरित किया जाएगा। समय निकालकर सर्वेक्षण के सवालों का अच्छी तरह से जवाब देने की सलाह दी जाती है: इस तरह से उपयोगकर्ता कोल्डटीवेट ऐप के साथ अधिक अनुकूल अनुभव प्राप्त कर सकता है!",
    },
    {
      id: 88,
      title:
        'एक ऑपरेटर मुझसे कंपनी की कूलिंग उपयोगकर्ताओं की सूची में मुझे जोड़ने के लिए एक कोड मांग रहा है। मुझे कोड कहां मिल सकता है?',
      role: [ERoles.COOLING_USER],
      text: "जब आप Coldtivate में साइन अप करते हैं, तो आपको एक कोड के रूप में एक अद्वितीय पहचानकर्ता प्राप्त होता है। इस कोड का उपयोग एक ऑपरेटर द्वारा आपको कंपनी की कूलिंग उपयोगकर्ताओं की सूची में जोड़ने के लिए किया जा सकता है, जो ऑपरेटरों को आपके क्रेट में चेक-इन करने के लिए आवश्यक है। कोड 'मेनू' -> 'खाता विवरण' के अंतर्गत पाया जा सकता है।",
    },
    {
      id: 66,
      title: 'मेरे पास साइन अप पर सर्वेक्षण के सवालों का जवाब देने का समय नहीं है। इक्या करु',
      role: [ERoles.COOLING_USER],
      text: "आप 'बाद में पूर्ण करें' पर क्लिक करके सर्वेक्षण के प्रश्नों को छोड़ सकते हैं। आप सर्वेक्षण को अपने खाता विवरण के हिस्से के रूप में पाएंगे और इसे कभी भी पूरा कर सकते हैं। हालांकि, जब आप कमरे का उपयोग करना शुरू करते हैं तो सर्वेक्षण के सवालों का पूरी तरह से जवाब देने के लिए समय निकालने की सिफारिश की जाती है: इस तरह आप कोल्डिवेट ऐप के साथ अधिक अनुरूप अनुभव प्राप्त कर सकते हैं!",
    },
    {
      id: 67,
      title: 'मैं कमरे में कुछ कैसे स्टोर कर सकता हूं?',
      role: [ERoles.COOLING_USER],
      text: "अपना पहला चेक-इन पूरा करने के लिए, 'कूलिंग यूनिट' टैब में उपलब्ध मानचित्र का उपयोग करके आस-पास के ठंडे कमरे खोजें, और फिर अपने क्रेट को कमरे में लाएँ। कोल्ड रूम ऑपरेटर आपको यह समझने में मदद कर सकता है कि कमरा कैसे काम करता है, आपसे कैसे शुल्क लिया जाएगा और कोल्ड स्टोरेज का उपयोग करने के क्या फायदे हैं।",
    },
    {
      id: 31,
      title: 'मैं चेक इन कैसे शुरू कर सकता हूं?',
      role: [ERoles.OPERATOR],
      text: 'चेक-इन आरंभ करने के लिए, डैशबोर्ड पर नेविगेट करें और नीचे दाईं ओर स्थित गतिविधि प्रबंधक बटन पर क्लिक करें, और फिर हरे बटन पर क्लिक करें।',
    },
    {
      id: 32,
      title: 'मैं चेक आउट कैसे शुरू कर सकता हूं?',
      role: [ERoles.OPERATOR],
      text: "चेक आउट शुरू करने के दो तरीके हैं, दोनों ही डैशबोर्ड पेज से शुरू हो रहे हैं। आप नीचे दाईं ओर स्थित गतिविधि प्रबंधक बटन पर क्लिक कर सकते हैं और फिर लाल बटन पर क्लिक कर सकते हैं। इस तरह, आप चुन सकते हैं कि आप किस कूलिंग उपयोगकर्ता (और किस कूलिंग यूनिट में) के लिए चेक आउट शुरू करना चाहते हैं, और कई चेक इन से उसके क्रेट देख सकते हैं। वैकल्पिक रूप से, आप डैशबोर्ड में दिखाई देने वाले आइटम के लिए 'विवरण देखें' पर क्लिक कर सकते हैं (सुनिश्चित करें कि वह सही कूलिंग यूनिट में है), और 'चेक आउट' पर क्लिक करें। इस मामले में, आप केवल उस स्टोरेज आइटम से क्रेट चेक-आउट कर सकते हैं।",
    },
    {
      id: 33,
      title: 'मैं ऐप के साथ कमरे में सेंसर कैसे कनेक्ट करूं?',
      role: [ERoles.EMPLOYEE],
      text: 'सेंसर को कूलिंग इकाई से जोड़ने के लिए, सेंसर में एपीआई सेटअप होना चाहिए। एपीआई को उपयोगकर्ता नाम और पासवर्ड का उपयोग करना चाहिए जो सामग्री-प्रकार के POST अनुरोध के माध्यम से भेजे जाते हैं: एप्लिकेशन/जेसन। प्रतिक्रिया में एक एक्सेस टोकन शामिल होना चाहिए, जिसका उपयोग किसी अन्य पोस्ट अनुरोध के लिए किया जा सकता है। POST अनुरोध को url में कक्ष-पहचानकर्ता, मान का प्रकार (तापमान, आर्द्रता), और टोकन को प्रमुख प्राधिकरण के साथ शीर्षक के रूप में शामिल करने की आवश्यकता है। प्रतिक्रिया इस कमरे में दर्ज किया गया अंतिम तापमान होना चाहिए, प्रारूप में {दिनांक: दिनांक समय टिकट, मान: संख्यात्मक}। तापमान सेल्सियस में होना चाहिए। फिलहाल, केवल इकोज़ेन एपीआई समर्थित है; हालांकि, ऐप टीम अन्य एपीआई सेटअप के लिए समर्थन का विस्तार करने के लिए काम कर रही है।',
    },
    {
      id: 68,
      title: 'मैं ऐप के साथ कमरे में सेंसर कैसे कनेक्ट करूं?',
      role: [ERoles.OPERATOR],
      text: 'यदि कमरे में तापमान संवेदक हैं जो Coldtivate ऐप से जुड़े हो सकते हैं, तो कृपया अपने जिम्मेदार से संपर्क करें। केवल एक पंजीकृत कर्मचारी भूमिका वाला उपयोगकर्ता सेंसर को कोल्डिवेट में बनाई गई कूलिंग इकाइयों से जोड़ सकता है।',
    },
    {
      id: 34,
      title: 'मैं कूलिंग इकाई का तापमान कैसे निर्धारित कर सकता हूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "शीतलन इकाई का तापमान निर्धारित करने के लिए, कृपया अपनी कंपनी द्वारा परिभाषित प्रक्रिया का पालन करें। ऐप का उपयोग निगरानी के लिए किया जा सकता है, लेकिन ठंडे कमरे में तापमान को अपडेट करने के लिए नहीं। हालाँकि, यदि ऐप सेंसर से लिंक नहीं है, तो यह महत्वपूर्ण है कि आप ऐप में सेट तापमान को अपडेट करें। आप 'कूलिंग यूनिट्स'> 'कमरे की स्थिति' पैनल के अंदर 'तापमान दर्ज करें' पर क्लिक करके ऐसा कर सकते हैं। यहां तापमान को अपडेट करने से आप ऐप में तापमान के विकास की कल्पना कर सकेंगे और शेष दिनों में सटीक भविष्यवाणी करने में सक्षम होंगे कि भंडारण में वस्तु के लिए अच्छा होगा। यदि ऐप सेंसर से जुड़ा हुआ है, तो ऐप में तापमान बदलने का विकल्प अक्षम हो जाएगा, और ऐप समय-समय पर सेंसर से यह जानकारी निकालेगा।",
    },
    {
      id: 35,
      title: 'चेक-आउट के बाद, बाजार सर्वेक्षण के बारे में कूलिंग उपयोगकर्ता से कैसे संपर्क करें?',
      role: [ERoles.OPERATOR],
      text: "इतिहास' टैब में आप नवीनतम चेक-आउट की सूची देख सकते हैं। आपको बाज़ार सर्वेक्षण भरने के लिए चेक आउट करने वाले प्रत्येक कूलिंग उपयोगकर्ता से संपर्क करना चाहिए, जिसे चेक आउट के आगे तीन बिंदुओं पर क्लिक करके और 'फ़िल इन मार्केट सर्वे' का चयन करके एक्सेस किया जा सकता है। 'विवरण देखें' पर क्लिक करके, आप देख सकते हैं कि कौन सी वस्तु भंडारण में थी और यदि आप उपयोगकर्ता से फोन पर संपर्क करना चाहते हैं तो उसका फोन नंबर। अन्यथा, आप तब तक प्रतीक्षा कर सकते हैं जब तक उपयोगकर्ता अगली बार अन्य उत्पाद को स्टोर करने के लिए कोल्ड रूम में नहीं आता। एक लाल बिंदु इतिहास सूची में चेक आउट की पहचान करेगा जिसके लिए बाजार सर्वेक्षण अभी पूरा नहीं हुआ है। चेक आउट दिनांक के 2 दिन बाद आपको सूचना पैनल में उन चेक आउट के बारे में याद दिलाया जाएगा जिन पर आपको ध्यान देने की आवश्यकता है।",
    },
    {
      id: 69,
      title: 'पोस्ट चेक-आउट मार्केट सर्वे क्या है और मुझे इसे क्यों भरना चाहिए?',
      role: [ERoles.COOLING_USER],
      text: "इतिहास' टैब में प्रत्येक चेक आउट के आगे तीन बिंदुओं पर क्लिक करके और 'बाजार सर्वेक्षण भरें' का चयन करके बाजार सर्वेक्षण तक पहुंचा जा सकता है। सर्वेक्षण बहुत छोटा होता है और आपके द्वारा पहले कमरे में रखे उत्पाद के बिक्री मूल्य के बारे में जानकारी माँगता है, साथ ही साथ यह भी कि यह कितना खराब हो गया। इस जानकारी को गोपनीय माना जाएगा और केवल Coldtivate टीम द्वारा कोल्ड स्टोरेज के उपयोग के प्रभाव का मूल्यांकन करने के लिए उपयोग किया जाएगा। एक लाल बिंदु उन चेक आउट की पहचान करेगा जिनके लिए अभी तक बाजार सर्वेक्षण पूरा नहीं हुआ है। चेक आउट दिनांक के 2 दिन बाद आपको सूचना पैनल में उन चेक आउट के बारे में याद दिलाया जाएगा जिन पर आपको ध्यान देने की आवश्यकता है।",
    },
    {
      id: 37,
      title: 'मैं डैशबोर्ड में एक आइटम की जानकारी कैसे पढ़ सकता हूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "बीच में बोल्ड अक्षर मैँ स्टोरेज आइटम की आईडी है। आईडी के नीचे की तस्वीर और नाम भंडारण में फसल का प्रतिनिधित्व करते हैं। बास्केट आइकॉन के आगे की संख्या आपको कूलिंग यूनिट के अंदर क्रेटों की संख्या बताती है। ऊपरी दाएं कोने में दिनों की संख्या अनुमानित शेष संग्रहण दिन (= लेने के समय तक दिन) हैं। ऊपरी दाएं कोने पर 'विवरण देखें' स्टोरेज आइटम के विस्तृत दृश्य का लिंक है। नीचे, कूलिंग उपयोगकर्ता का नाम प्रदर्शित किया गया है। नीचे दाईं ओर दिनों की संख्या दर्शाती है कि अब तक उन्हें कूलिंग यूनिट के अंदर कितने दिनों तक संग्रहीत किया गया है। मूल्य पूरे भंडारण आइटम के लिए दैनिक मूल्य को इंगित करता है, अर्थात सभी क्रेटों के लिए कुल मूल्य।",
    },
    {
      id: 38,
      title: 'सामान लेने का समय क्या है?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'कूलिंग यूजर के लिए वस्तु लेने के लिए बचे हुए दिनों की संख्या का समय सुझाया गया है। बाद में, वस्तु अपनी मार्केटिंग क्षमता खोना शुरू कर देगी। शून्य के बराबर लेने का समय इंगित करता है कि उपयोगकर्ता को तुरंत भंडारण में आइटम एकत्र करने के लिए आना चाहिए और इसे बाजार में बेचने के लिए 2 दिनों तक का समय है। इसे डैशबोर्ड (ऊपरी दाएं) और प्रत्येक स्टोरेज आइटम के विस्तृत दृश्य में देखा जा सकता है।',
    },
    {
      id: 39,
      title: 'लेने के समय की गणना कैसे की जाती है? यह किन कारकों से प्रभावित होता है?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'ताजी सब्जियां और फल खराब हो जाते हैं और कटाई के बाद वे अपनी ताजगी कैसे खो देते हैं यह काफी हद तक तापमान पर आधारित होता है। इसलिए, लेने का समय की गणना संबंधित कूलिंग इकाई के तापमान और कूलिंग इकाई में लाए जाने पर उत्पाद की प्रारंभिक गुणवत्ता के आधार पर की जाती है। इस गणना में प्रयुक्त मापदंडों प्रत्येक वस्तु के लिए अद्वितीय हैं। ज्ञान केंद्र में आप इस बारे में कुछ अंतर्दृष्टि प्राप्त कर सकते हैं कि विभिन्न वस्तुओं के बीच खराब होने की क्षमता कैसे भिन्न होती है।',
    },
    {
      id: 40,
      title: 'लेने का समय "0" दिन है लेकिन उपज अभी भी अच्छी दिख रही है। क्यों?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: "लेने का समय अनुमानित मूल्य है। इस प्रकार, यह संभव है कि एक कूलिंग उपयोगकर्ता 0 दिनों के बराबर लेने के लिए समय के साथ एक भंडारण आइटम की चेक आउट कर सकता है और अभी भी उचित रूप से से बेचने का प्रबंधन कर सकता है। हालांकि, इस बात से अवगत रहें कि कुछ गुणवत्ता हानि मानव आंखों के लिए अदृश्य है, और यह अभी भी एक अच्छा अभ्यास है कि जितना हो सके उतना समय लेने के लिए दिए गए संकेत का पालन करें। यदि ऐप तापमान सेंसर से जुड़ा है तो, लेने का समय कापूर्वानुमान विशेष रूप से सटीक है। यदि आपके पास वे नहीं हैं, तो हम आपको उन्हें अपनी कूलिंग इकाइयों में स्थापित करने की सलाह देते हैं। सेटअप के बारे में अधिक जानकारी के लिए कृपया प्रश्न 'मैं कमरे में सेंसर को ऐप से कैसे कनेक्ट करूं' का संदर्भ लें।",
    },
    {
      id: 41,
      title: 'लेने का समय ">0" दिन है लेकिन उपज लगभग खराब हो गई है। क्यों?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "लेने का समय एक अनुमानित मूल्य है। इस प्रकार, दुर्लभ मामले हो सकते हैं, जहां उपज खराब हो जाती है जबकि लेने का समय 0 से बड़ा होता है। ताजा उपज की गुणवत्ता में गिरावट काफी हद तक तापमान पर निर्भर करती है, तापमान डेटा भविष्यवाणी को अधिक सटीक बनाने में मदद करता है। उदाहरण के लिए, समस्या तब उत्पन्न हो सकती है जब ऐप से कोई तापमान सेंसर लिंक न हो, और ऑपरेटर ने कमरे में गलत तापमान सेट कर दिया हो। यदि आपके पास तापमान सेंसर नहीं हैं, तो हम आपको उन्हें अपनी शीतलन इकाइयों में स्थापित करने की सलाह देते हैं। सेटअप के बारे में अधिक जानकारी के लिए कृपया प्रश्न 'मैं कमरे में सेंसर को ऐप से कैसे कनेक्ट करूं' का संदर्भ लें।",
    },
    {
      id: 70,
      title: 'लेने का समय ">0" दिन है लेकिन उपज लगभग खराब हो गई है। क्यों?',
      role: [ERoles.COOLING_USER],
      text: 'लेने का समय एक अनुमानित मूल्य है। इस प्रकार, दुर्लभ मामले हो सकते हैं, जहां उत्पादन खराब हो जाता है, जबकि लेने का समय 0 से बड़ा होता है। चूंकि ताजा उपज का गुणवत्ता क्षय काफी हद तक तापमान पर निर्भर करता है, तापमान डेटा भविष्यवाणी को अधिक सटीक बनाने में मदद करता है। उदाहरण के लिए, समस्या तब उत्पन्न हो सकती है जब ऐप से कोई तापमान सेंसर जुड़ा न हो, और ऑपरेटर ने ऐप में कमरे के तापमान को नियमित रूप से अपडेट नहीं किया हो। ऐसा होने की स्थिति में कृपया रूम के संचालक को सूचित करें।',
    },
    {
      id: 42,
      title:
        'अगले दिनों के लिए कमरे में रहने की जगह लाल है (<20%)। यह किस पर आधारित है? क्या मुझे चिंतित होना चाहिए?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "जब शीतलन इकाई की क्षमता का 80% से अधिक उपयोग किया जाता है, तो अधिभोग को लाल रंग में दिखाया जाता है। भावी अधिभोग के बारे में जानकारी उन दिनों की संख्या पर आधारित होती है, जब प्रत्येक उपयोगकर्ता चेक-इन के समय भंडारण में नियोजित दिनों के रूप में घोषित करता है। सावधान रहें कि यह केवल एक अनुमान है और गलत भी हो सकता है। जैसे, लाल कमरे का अधिभोग सिर्फ एक संकेत है कि कमरा भर रहा है। आपको चिंता करने की जरूरत नहीं है लेकिन आप अपने हिसाब से कार्रवाई कर सकते हैं। उदाहरण के लिए, उन कूलिंग उपयोगकर्ताओं से संपर्क करने पर विचार करें, जिनके पास भंडारण में सामान लेने के लिए सबसे कम समय है, ताकि उन्हें जल्द ही चेक आउट करने की सलाह दी जा सके। जब आप लेने के लिए समय के अनुसार ऑर्डर करते हैं तो आप 'डैशबोर्ड' के तहत चेक आउट करने के लिए सबसे जरूरी वस्तुओं की एक ऑर्डर की गई सूची देख सकते हैं।",
    },
    {
      id: 43,
      title:
        'एक कूलिंग उपयोगकर्ता कमरे में एक ऐसी वस्तु ला रहा है जो सूची में नहीं है। क्या मैं अभी भी चेक इन कर सकता हूं?',
      role: [ERoles.OPERATOR],
      text: "ज़रूर, इस मामले में आप वस्तु सूची से 'अन्य' का चयन करके एक चेक इन शुरू कर सकते हैं।",
    },
    {
      id: 44,
      title: 'डैशबोर्ड में, प्रत्येक आइटम में एक रंगीन बार होता है। बार का रंग क्या दर्शाता है?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'रंग लेने के समय से पहले शेष दिनों का प्रतिनिधित्व करता है। आप बार को 2 दिनों से कम समय में लाल रंग में, 7 दिनों से कम समय में पीले रंग में और 7 दिनों से अधिक समय में हरे रंग में देखेंगे। ये मान प्रत्येक भंडारण वस्तु के लिए विशिष्ट हैं और कूलिंग इकाई में तापमान के आधार पर प्रति दिन कई बार पुनर्गणना की जाती है। जब गणना के लिए कोई मॉडल उपलब्ध नहीं है, तो बार का रंग ग्रे होगा।',
    },
    {
      id: 45,
      title:
        'मैंने सफलतापूर्वक एक चेक इन पूरा कर लिया है लेकिन अभी भी डैशबोर्ड में आइटम देख सकता हूं। क्यों?',
      role: [ERoles.OPERATOR],
      text: 'डैशबोर्ड को अपडेट होने में कुछ समय लग सकता है। कृपया यह भी सत्यापित करें कि आप सही कूलिंग इकाई देख रहे हैं। यदि आप अभी भी समस्या का सामना कर रहे हैं, तो कृपया इसकी रिपोर्ट app@yourvcca.org पर करें।',
    },
    {
      id: 46,
      title:
        'मैंने सफलतापूर्वक चेक आउट पूरा कर लिया है लेकिन फिर भी मैं डैशबोर्ड में आइटम देख सकता हूं। क्यों?',
      role: [ERoles.OPERATOR],
      text: 'डैशबोर्ड को अपडेट होने में कुछ समय लग सकता है। कृपया यह भी सत्यापित करें कि आपके द्वारा चेक-आउट किए गए आइटम सही थे, और यह कि आप सही कूलिंग इकाई देख रहे हैं। यदि आप अभी भी समस्या का सामना कर रहे हैं, तो कृपया इसकी रिपोर्ट app@yourvcca.org पर करें।',
    },
    {
      id: 47,
      title: 'मैं कैसे जांच सकता हूं कि तापमान सेंसर ठीक काम कर रहा है?',
      role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
      text: "एक पंजीकृत कर्मचारी द्वारा दी गई कूलिंग यूनिट में सेंसर कनेक्शन को सक्षम करने के बाद, 'कूलिंग यूनिट्स'> 'रूम कंडीशंस' पैनल में मैनुअल तापमान इनपुट के लिए बटन ग्रे-आउट हो जाएगा। सेंसर डेटा हर 1 घंटे में प्राप्त किया जाता है, इसलिए यदि सेंसर ठीक से काम कर रहा है तो आपको हर घंटे नए बिंदुओं के साथ तापमान प्लॉट देखना चाहिए।",
    },
    {
      id: 48,
      title: 'मुझे एक सूचना मिली कि सेंसर काम नहीं कर रहा है। मुझे क्या करना चाहिए?',
      role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
      text: "12 घंटे से अधिक समय तक सेंसर से डेटा प्राप्त नहीं करने के बाद अधिसूचना भेजी जाती है, और इसका मतलब है कि 'कूलिंग यूनिट्स'> 'रूम कंडीशंस' पैनल में सेट तापमान का अब उपयोग किया जा रहा है। ऐप हर 1 घंटे में सेंसर को फिर से कनेक्ट करने का प्रयास करेगा, इस प्रकार हम कुछ घंटों तक प्रतीक्षा करने की सलाह देते हैं यदि यह एक कनेक्टिविटी समस्या है। यदि कई घंटों या दिनों के लिए कोई नया सेंसर डेटा नहीं है, तो समस्या हार्डवेयर पक्ष में हो सकती है, उदाहरण के लिए, सेंसर की बैटरी समाप्त हो सकती है।",
    },
    {
      id: 49,
      title: 'अगर सेंसर नहीं हैं तो चीजों को लेने के लिए समय की गणना कैसे की जा सकती है?',
      role: [ERoles.EMPLOYEE],
      text: 'जब ऐप से कोई सेंसर कनेक्ट नहीं होता है, तो मॉडल लेने के लिए समय की गणना करने के लिए ऑपरेटर द्वारा निर्धारित तापमान पर निर्भर करता है। यही कारण है कि ऑपरेटर को प्रत्येक नए चेक इन और चेक आउट पर एक नया सेट तापमान इनपुट करने के लिए प्रेरित किया जाता है। मॉडल के सटीक होने के लिए, यह महत्वपूर्ण है कि तापमान अप-टू-डेट हो। कृपया इस महत्वपूर्ण कदम के बारे में अपनी कूलिंग इकाई के ऑपरेटरों को निर्देश दें।',
    },
    {
      id: 50,
      title: 'हर बार जब मैं चेक-इन शुरू करता हूं, तो मुझे तापमान अलर्ट पॉपअप मिलता है। क्यों?',
      role: [ERoles.OPERATOR],
      text: 'यदि कोई सेंसर नहीं है (या यदि वे ठीक से काम नहीं कर रहे हैं) तो यह पॉप अप आपके लिए कूलिंग रूम के सही सेट तापमान के बारे में ऐप को सूचित करने के लिए एक अनुस्मारक है। आपको जांचना चाहिए कि क्या पॉपअप में दर्शाया गया मान वही है जो आप कमरे के नियंत्रण कक्ष में पढ़ सकते हैं। यदि ऐसा नहीं है, तो आपको तापमान को अपडेट करना चाहिए। अन्यथा, आप चेक इन की पुष्टि कर सकते हैं और जारी रख सकते हैं। एक अद्यतन सेट तापमान होना मॉडल के लिए बहुत महत्वपूर्ण है जो गणना कर सके कितने दिनों मैं सामान निकलना है ।',
    },
    {
      id: 51,
      title: 'हर बार जब मैं चेक-आउट पूरा करता हूं, तो मुझे तापमान अलर्ट पॉपअप मिलता है। क्यों?',
      role: [ERoles.OPERATOR],
      text: 'एक कूलिंग इकाई का तापमान इस आधार पर निर्धारित किया जाना चाहिए कि कौन सी वस्तुएं भंडारण में हैं, क्योंकि विभिन्न वस्तुओं के अलग-अलग इष्टतम तापमान होते हैं (आप ज्ञान केंद्र में एक अवलोकन देख सकते हैं)। चेक आउट पूरा होने के बाद दिखाई देने वाला पॉपअप कमरे में छोड़ी गई वस्तुओं का सारांश दिखाता है और आपको उनमें से प्रत्येक के लिए इष्टतम तापमान के बारे में सूचित करता है। इस तरह, आप इस बारे में एक सूचित निर्णय ले सकते हैं कि क्या कमरे के तापमान को बदलना चाहिए।',
    },
    {
      id: 52,
      title:
        'कूलिंग उपयोगकर्ता को पहले टोकरा में चेक इन करने से पहले मुझे एक प्रश्नावली भरने के लिए कहने की आवश्यकता क्यों है?',
      role: [ERoles.OPERATOR],
      text: 'ऐप को विकसित करने वाली टीम कूलिंग उपयोगकर्ताओं के बारे में कुछ बुनियादी जानकारी एकत्र कर रही है, जब वे पहली बार कमरे को बेसलाइन डेटा के रूप में उपयोग करना शुरू करते हैं, जिसकी तुलना ऐप द्वारा प्राप्त डेटा से की जाएगी। हमारा एकमात्र इरादा ऐप डिज़ाइन और ठंडे भंडारण के उपयोग में सुधार करना है।',
    },
    {
      id: 71,
      title: 'जब मैं ऐप पर पंजीकरण करता हूं तो मुझे प्रश्नावली भरने की आवश्यकता क्यों है?',
      role: [ERoles.COOLING_USER],
      text: 'ऐप को विकसित करने वाली टीम कूलिंग उपयोगकर्ताओं के बारे में कुछ बुनियादी जानकारी एकत्र कर रही है, जब वे पहली बार कमरे को बेसलाइन डेटा के रूप में उपयोग करना शुरू करते हैं, जिसकी तुलना ऐप द्वारा प्राप्त डेटा से की जाएगी। हमारा एकमात्र इरादा ऐप डिज़ाइन और ठंडे भंडारण के उपयोग में सुधार करना है।',
    },
    {
      id: 53,
      title:
        'मुझे कूलिंग उपयोगकर्ताओं से प्रत्येक संग्रहण वस्तु के विक्रय मूल्य के बारे में पूछने की आवश्यकता क्यों है?',
      role: [ERoles.OPERATOR],
      text: 'आपको एक कूलिंग उपयोगकर्ता से संपर्क करने के लिए कहा जाएगा, जिसने हाल ही में कमरे से कुछ उत्पाद की चेक आउट की है और यह पूछना है कि उन्होंने कमरे में संग्रहीत वस्तु को कहाँ और किस कीमत पर बेचा है। यह जानकारी प्रदान की गई बाजार कीमतों के पूर्वानुमानों की सटीकता को मान्य और सुधारने के लिए ऐप विकसित करने वाली टीम की मदद करेगी।',
    },
    {
      id: 54,
      title: 'मुझे ऐप के कुछ हिस्सों की समझ नहीं है। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.EMPLOYEE],
      text: 'ट्यूटोरियल और अक्सर पूछे जाने वाले प्रश्न अनुभाग की जाँच करना सुनिश्चित करें, क्योंकि उनमें ऐप के बारे में उपयोगी जानकारी होती है जो आपके प्रश्नों को स्पष्ट करने में मदद कर सकती है। अगर आप ऐप सपोर्ट टीम से संपर्क करना चाहते हैं, तो कृपया app@yourvcca.org पर एक ईमेल भेजें।',
    },
    {
      id: 55,
      title: 'मुझे ऐप के कुछ हिस्सों की समझ नहीं है। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.OPERATOR],
      text: 'ट्यूटोरियल और अक्सर पूछे जाने वाले प्रश्न अनुभाग की जाँच करना सुनिश्चित करें, क्योंकि उनमें ऐप के बारे में उपयोगी जानकारी होती है जो आपके प्रश्नों को स्पष्ट करने में मदद कर सकती है। यदि आपका प्रश्न अभी भी अनुत्तरित है, तो कृपया उस पंजीकृत कर्मचारी से संपर्क करें जिसे आप रिपोर्ट कर रहे हैं।',
    },
    {
      id: 73,
      title: 'मुझे ऐप के कुछ हिस्सों की समझ नहीं है। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.COOLING_USER],
      text: 'ट्यूटोरियल और अक्सर पूछे जाने वाले प्रश्न अनुभाग की जाँच करना सुनिश्चित करें, क्योंकि उनमें ऐप के बारे में उपयोगी जानकारी होती है जो आपके प्रश्नों को स्पष्ट करने में मदद कर सकती है। यदि आपका प्रश्न अभी भी अनुत्तरित है, तो कृपया कोल्ड रूम के संचालक से संपर्क करें, या app@yourvcca.org पर लिखें',
    },
    {
      id: 56,
      title: 'मुझे ऐप में एक गलती मिला। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.EMPLOYEE],
      text: 'कृपया app@yourvcca.org पर एक ईमेल भेजकर ऐप सपोर्ट टीम को सूचित करें।',
    },
    {
      id: 57,
      title: 'कुछ चीजें ऐप में ठीक से काम नहीं कर रहा है। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.OPERATOR],
      text: 'कृपया उस पंजीकृत कर्मचारी से संपर्क करें जिसे आप रिपोर्ट कर रहे हैं और/या app@yourvcca.org पर एक ईमेल भेजकर ऐप सहायता टीम को सूचित करें।',
    },
    {
      id: 74,
      title: 'कुछ चीजें ऐप में ठीक से काम नहीं कर रहा है। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.COOLING_USER],
      text: 'कृपया सुनिश्चित करें कि आपके पास ऐप का नवीनतम संस्करण इंस्टॉल है। यदि समस्या बनी रहती है, तो कृपया कोल्ड रूम के संचालक से संपर्क करें और / या app@yourvcca.org पर एक ईमेल भेजकर ऐप सपोर्ट टीम को सूचित करें।',
    },
    {
      id: 58,
      title:
        'मैं ऐप के साथ अपने अनुभव के बारे में प्रतिक्रिया देना चाहता हूं। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.EMPLOYEE],
      text: 'ऐप सपोर्ट टीम इस ऐप का उपयोग करने के आपके अनुभव के बारे में सुनना पसंद करेगी और आपकी प्रतिक्रिया का स्वागत करती है, कृपया app@yourvcca.org पर एक ईमेल भेजें।',
    },
    {
      id: 86,
      title:
        'मैं ऐप के साथ अपने अनुभव के बारे में प्रतिक्रिया देना चाहता हूं। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.OPERATOR],
      text: 'ऐप सपोर्ट टीम इस ऐप का उपयोग करने के आपके अनुभव के बारे में सुनना पसंद करेगी और आपकी प्रतिक्रिया का स्वागत करती है, कृपया app@yourvcca.org पर एक ईमेल भेजें।',
    },
    {
      id: 87,
      title:
        'मैं ऐप के साथ अपने अनुभव के बारे में प्रतिक्रिया देना चाहता हूं। मुझे किससे संपर्क करना चाहिए?',
      role: [ERoles.COOLING_USER],
      text: 'ऐप सपोर्ट टीम इस ऐप का उपयोग करने के आपके अनुभव के बारे में सुनना पसंद करेगी और आपकी प्रतिक्रिया का स्वागत करती है, कृपया app@yourvcca.org पर एक ईमेल भेजें।',
    },
    {
      id: 17,
      title:
        'मैं ऐसे क्षेत्र में हूं जहां इंटरनेट कनेक्शन कम है: क्या मैं अब भी ऐप का उपयोग कर सकता हूं?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'वर्तमान में, केवल नॉलेज हब अनुभाग ऑफ़लाइन उपलब्ध है। ऐप के अतिरिक्त हिस्से जल्द ही बिना इंटरनेट कनेक्शन के भी एक्सेस किए जायेंगे।',
    },
    {
      id: 60,
      title: "बाजार मूल्य' आइकन पर क्लिक करने पर कौन से मूल्य प्रदर्शित होते हैं?",
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'आपको एक स्क्रीन पर ले जाया जाता है जहां आप बाजार मूल्य की भविष्यवाणी या तो प्लॉट या टेबल फॉर्मेट में देख सकते हैं। प्राइस ट्रेंड पेज पिछले महीने के डेटा और एक विशिष्ट बाजार और कमोडिटी के लिए 14 दिनों के पूर्वानुमान की कल्पना करने की अनुमति देता है। मूल्य रैंकिंग पृष्ठ उच्चतम से निम्नतम तक सभी बाजार मूल्य पूर्वानुमानों की कल्पना करने की अनुमति देता है, और राज्य, जिले, एक विशिष्ट बाजार और पूर्वानुमान विंडो द्वारा फ़िल्टर करने की संभावना के साथ।',
    },
    {
      id: 61,
      title: "बाजार मूल्य' खंड में कुछ राज्य और बाजार क्यों गायब हैं?",
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'डेटा उपलब्धता के कारण, मॉडल को कुछ चुनिंदा भारतीय राज्यों में केवल कुछ वस्तुओं के लिए लागू किया गया है। प्रोजेक्ट टीम नाइजीरिया और अन्य देशों में ऐप के बाद के संस्करणों में मॉडल उपलब्ध कराने के लिए काम कर रही है।',
    },
    {
      id: 62,
      title: 'भावी बाजार कीमतों की गणना कैसे की जाती है?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
      text: 'एक मशीन लर्निंग मॉडल को ऐतिहासिक बाजार मूल्य डेटा और अन्य डेटा जैसे मुद्रा रूपांतरण दर और पेट्रोल की कीमत पर प्रशिक्षित किया जाता है, ताकि भविष्य की बाजार कीमतों का पूर्वानुमान लगाया जा सके।',
    },
    {
      id: 75,
      title: 'मैं अपना खाता हटाना चाहता हूं। इक्या करु',
      role: [ERoles.EMPLOYEE],
      text: "अपने खाते को हटाने के लिए आप 'मेनू' -> 'खाता विवरण' पर नेविगेट कर सकते हैं और हटाएं पर क्लिक कर सकते हैं। कृपया सावधान रहें, यह क्रिया पूर्ववत नहीं की जा सकती! यदि आप कंपनी के अंतिम पंजीकृत कर्मचारी हैं, तो यह कार्रवाई कंपनी को हटा देगी। यदि लंबित चेकइन हैं, तो आप अपने खाते को तब तक नहीं हटा पाएंगे जब तक कि आपके किसी एक ऑपरेटर द्वारा ऐप में सभी क्रेट चेक-आउट नहीं कर दिए जाते।",
    },
    {
      id: 76,
      title: 'मैं अपना खाता हटाना चाहता हूं। इक्या करु',
      role: [ERoles.OPERATOR],
      text: "अपने खाते को हटाने के लिए आप 'मेनू' -> 'खाता विवरण' पर नेविगेट कर सकते हैं और हटाएं पर क्लिक कर सकते हैं। कृपया सावधान रहें, यह क्रिया पूर्ववत नहीं की जा सकती! यदि आप उन कमरों में से किसी एक को निर्दिष्ट अंतिम ऑपरेटर हैं, जहां खुले चेक-इन हैं, तो आप अपना खाता तब तक नहीं हटा सकते जब तक कि कोई पंजीकृत कर्मचारी कमरे के लिए कोई अन्य ऑपरेटर निर्दिष्ट नहीं करता है, या ऐप में सभी क्रेट चेक-आउट नहीं कर दिए जाते हैं।",
    },
    {
      id: 77,
      title: 'मैं अपना खाता हटाना चाहता हूं। इक्या करु',
      role: [ERoles.COOLING_USER],
      text: "अपने खाते को हटाने के लिए आप 'मेनू' -> 'खाता विवरण' पर नेविगेट कर सकते हैं और हटाएं पर क्लिक कर सकते हैं। कृपया सावधान रहें, यह क्रिया पूर्ववत नहीं की जा सकती! यदि आपके पास किसी भी कमरे में खुला चेक-इन है, तो आप अपना खाता तब तक नहीं हटा सकते जब तक कि सभी क्रेट कमरों से चेक-आउट नहीं हो जाते। कृपया कमरे में अपने टोकरे इकट्ठा करना सुनिश्चित करें! यदि आपको लगता है कि ऐप में लंबित क्रेट हैं जिन्हें आपने पहले ही हटा दिया है, तो कृपया इसे हल करने के लिए कमरे के संचालक से संपर्क करें।",
    },
    {
      id: 78,
      title: 'मैं कूलिंग यूनिट या स्थान को कैसे हटा सकता हूँ?',
      role: [ERoles.EMPLOYEE],
      text: "आप 'मेन्यू' -> 'मैनेजमेंट' -> 'कूलिंग यूनिट' / 'लोकेशन' में जाकर 'डिलीट' पर क्लिक करके कूलिंग यूनिट्स और लोकेशन्स को डिलीट कर सकते हैं। आप ऐसा तभी कर पाएंगे जब कमरों में कोई चेक-इन लंबित न हो। अन्यथा, कृपया कमरे और स्थानों को हटाने का प्रयास करने से पहले ऑपरेटरों को चेक-आउट पूरा करने के लिए सूचित करें।",
    },
    {
      id: 79,
      title: 'मैं अपनी कंपनी से किसी अन्य पंजीकृत कर्मचारी या ऑपरेटर को कैसे हटा सकता हूँ?',
      role: [ERoles.EMPLOYEE],
      text: "आपको ऐप से अन्य उपयोगकर्ताओं को हटाने की अनुमति नहीं है। हालांकि, आप 'मेन्यू' -> 'प्रबंधन' -> 'ऑपरेटर्स' पर नेविगेट करके अपने कमरों से ऑपरेटरों को अनअसाइन कर सकते हैं। यदि आप अभी भी उपयोगकर्ता को पूरी तरह से हटाना चाहते हैं ताकि उनकी आपकी कंपनी तक पहुंच न हो, तो कृपया app@yourvcca.org पर एक ईमेल लिखें और बताएं कि इसकी आवश्यकता क्यों है।",
    },
    {
      id: 80,
      title: 'मैं सूची से कूलिंग उपयोगकर्ता को कैसे हटा सकता हूँ?',
      role: [ERoles.OPERATOR],
      text: "कूलिंग यूजर को सूची से हटाने के लिए, 'मैनेजमेंट' -> 'कूलिंग यूजर्स' पर नेविगेट करें, कूलिंग यूजर नेम पर क्लिक करें और फिर 'डिलीट' बटन पर क्लिक करें। कृपया ध्यान दें कि केवल उन उपयोगकर्ताओं को हटाया जा सकता है जिनके पास कोई चेक-इन लंबित नहीं है! यदि चेक-इन लंबित हैं, तो कृपया उत्पाद लेने के लिए उपयोगकर्ता से संपर्क करें। ध्यान दें कि इस क्रिया को पूर्ववत नहीं किया जा सकता है! यदि उपयोगकर्ता के पास स्मार्टफोन है, तो यह ऑपरेशन उसे आपकी सूची से हटा देगा, लेकिन उपयोगकर्ता अभी भी कोल्ड्टिवेट का उपयोग करने में सक्षम होगा। यदि उपयोगकर्ता के पास स्मार्टफोन नहीं है, तो यह ऑपरेशन उसके खाते को हटा देता है और संबंधित फोन नंबर को मुक्त कर देता है।",
    },
    {
      id: 81,
      title: 'मैं कहां निगरानी रख सकता हूं कि ऑपरेटरों ने हाल ही में ऐप का उपयोग किया है या नहीं?',
      role: [ERoles.EMPLOYEE],
      text: "आखिरी बार ऑपरेटरों और अन्य पंजीकृत कर्मचारियों ने ऐप में लॉग इन किया है, यह देखने के लिए, आप 'मेनू' -> 'प्रबंधन' -> 'ऑपरेटर' / 'पंजीकृत कर्मचारी' पर नेविगेट कर सकते हैं। नाम के आगे आप जो दिनांक और समय देखते हैं, वह अंतिम लॉगिन दिनांक और समय है।",
    },
    {
      id: 82,
      title:
        'मैं प्रत्येक कमरे और अन्य उपयोग के आँकड़ों से उत्पन्न राजस्व की निगरानी कहाँ कर सकता हूँ?',
      role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
      text: "आप 'मेनू' -> 'प्रबंधन' -> 'राजस्व विश्लेषण' पर नेविगेट कर सकते हैं, शीतलन इकाइयों और ब्याज के समय अंतराल का चयन कर सकते हैं, और आप इन कमरों से चेक-आउट से जुड़े कुल राजस्व देखेंगे। आप कूलिंग यूजर, पेमेंट मेथड और क्रॉप के हिसाब से भी फिल्टर कर सकते हैं। प्रति कमरा अपने चेक-इन के सारांश आंकड़ों की कल्पना करने के लिए (उपयोगकर्ताओं की संख्या, क्रेट की कुल संख्या, आदि के रूप में), आप 'मेनू' -> 'प्रबंधन' -> 'उपयोग विश्लेषण' पर नेविगेट कर सकते हैं। साथ ही यहां आप तारीख, कूलिंग यूजर और क्रॉप के हिसाब से फिल्टर कर सकते हैं। अंत में, क्रेट की कुल संख्या, वज़न, और कमरे में वर्तमान में फ़सलों के इष्टतम तापमान पर नज़र रखने के लिए, आप 'कूलिंग यूनिट' -> 'क्रेट्स की जानकारी' पर नेविगेट कर सकते हैं।",
    },
    {
      id: 83,
      title:
        'मैं कैसे पता लगा सकता हूं कि कूलिंग यूनिट के लिए संपर्क व्यक्ति कौन है जहां मेरी उपज संग्रहीत है?',
      role: [ERoles.COOLING_USER],
      text: 'डैशबोर्ड में किसी आइटम पर क्लिक करके, आप उस ऑपरेटर का नाम और संपर्क नंबर देख सकते हैं जिसने आपके लिए चेक इन किया था। आप नंबर को क्लिपबोर्ड पर कॉपी कर सकते हैं और ऑपरेटर से प्रति फोन या एसएमएस पर संपर्क कर सकते हैं।',
    },
    {
      id: 84,
      title: 'मुझे एक सूचना मिली है। इक्या करु',
      role: [ERoles.COOLING_USER],
      text: "आपको दो प्रकार की सूचनाएँ प्राप्त हो सकती हैं: पहला, ऐप आपको इस तथ्य के बारे में सूचित कर सकता है कि आपके द्वारा संग्रहित कुछ क्रेट खराब होने वाले हैं। हम आपको सलाह देते हैं कि जितनी जल्दी हो सके कमरे से टोकरा इकट्ठा करें। एक अन्य सूचना जो आपको प्राप्त हो सकती है वह आपको चेक-आउट के बाद के बाजार सर्वेक्षण को पूरा करने के लिए याद दिलाने के लिए है। जिन चेक-आउट के लिए बाजार सर्वेक्षण नहीं भरा गया है, उन्हें 'इतिहास' टैब में एक लाल बिंदु द्वारा चिह्नित किया गया है। सर्वेक्षण बहुत जल्दी पूरा हो जाता है और आपसे उस कीमत के बारे में पूछता है जिस पर आपके भंडारण में रखी गई उपज बेची गई थी, और क्या चेक-आउट के बाद उत्पाद का कोई हिस्सा खराब हो गया था। यह जानकारी कोल्ड्टिवेट टीम के लिए उत्पाद को बाहर स्टोर करने की तुलना में ठंडे कमरे के उपयोग के लाभ की निगरानी करने के लिए बहुत मूल्यवान है।",
    },
    {
      id: 85,
      title: 'शीतलन इकाइयों के मानचित्र पर क्या प्रदर्शित होता है?',
      role: [ERoles.COOLING_USER],
      text: 'मानचित्र पर आप अपने स्थान की कल्पना कर सकते हैं (आपसे आपके स्थान तक पहुँचने के लिए Coldtivate की अनुमति मांगी जाएगी), आपके आस-पास की शीतलन इकाइयों का स्थान, और इकाइयों के बारे में कुछ जानकारी (एकल या बहु-वस्तु, कंपनी, मूल्य निर्धारण)।',
    },
  ],
  [APP_LOCALES.ORIYA]: [],
  [APP_LOCALES.GUJARATI]: [],
  [APP_LOCALES.FRENCH]: [],
  [APP_LOCALES.PORTUGUESE]: [],
};
