import { ERoles } from '#types/global';

export const FAQ_CONTENT = [
  {
    id: 1,
    title: 'Why should I use the app?',
    role: [ERoles.AUTH],
    text: 'The app is designed to support cold room providers in their day-to-day operations at the cold room. The app features a digital inventory, remote monitoring of the items in storage and room temperature (if sensors are available), and information about the number of days a given item in storage is still good for. It also includes the Knowledge Hub, which provides commodity-specific recommendations on optimal storage temperature and storage life. Additionally, cooling users can use the app to find nearby cooling units, to monitor the produce they have brought to cold storage, get informed about good storing practices, and get recommendations about the best time and place to sell.',
  },
  {
    id: 2,
    title: 'Who can use the app?',
    role: [ERoles.AUTH],
    text: "The app can be used by employees and operators of cold storage companies as well as by potential cooling users around the world. Throughout the app, there are three user roles: (i) Registered employee: part of the cold room provider management team. A person that is responsible for setting up and managing the room, is in charge of overlooking the operators activities on the ground, without being physically present at the location. For example: a company CEO, CFO, etc. (ii) Operator: an employee physically present at the cold room and managing its check-in, check-out operations. This person is in direct contact with the cold room users, and reports to a company registered employee. (iii) Cooling users: the cold room users (can be farmers, traders, retailers, etc). Cooling users who have a smartphone can log in on the app as users. If they don't have a smartphone, operators do the cooling users' operations on their behalf.",
  },
  {
    id: 3,
    title: 'How can I sign up as a Registered employee?',
    role: [ERoles.AUTH],
    text: "If you are the first employee from your company to sign up, you can click on the 'Sign up as a company' button and follow the steps to register your company and yourself (including personal details and password). Once you have successfully signed up, you can log in as a Registered employee in the app and send a SMS invitation to other registered employees to join your company.",
  },
  {
    id: 4,
    title: 'How can I sign up as an Operator?',
    role: [ERoles.AUTH],
    text: 'To sign up, you need to be invited by a Registered employee. You will receive an SMS with an activation link, from where you can set up your personal details and password.',
  },
  {
    id: 5,
    title: 'How can I sign up as a Cooling user?',
    role: [ERoles.AUTH],
    text: "Cooling users with smartphones can register as app users clicking on 'Sign up as a cooling user' in the homepage and providing their personal details and password. Cooling users who don't have a smartphone can be added to the app by the operators. This operation is needed to initiate a check-in for those cooling users. Cooling users need to provide a phone number, which the operator will use to contact the cooling users in case of need. No password is required in this case.",
  },
  {
    id: 6,
    title: 'I cannot complete the registration as a user. What should I do?',
    role: [ERoles.AUTH],
    text: 'To complete the registration, please make sure that the following conditions are satisfied: (i) You are entering a phone number with the correct country code (e.g. +91 for India); (ii) The phone number you provided has not been used to register any other user; (iii) The password you are entering contains minimum 8 characters, and at least: one uppercase letter, one lowercase letter, and one number; (iv) The passwords you are entering are the same - you can click on the eye symbol to reveal the passwords and check they are equal.',
  },
  {
    id: 7,
    title: "I don't have a phone but want to use the app. What should I do?",
    role: [ERoles.AUTH],
    text: "If you are a registered employee or an operator, you need to provide a valid phone number to sign up. A smartphone is needed to correctly use the app. If you are a cooling user and don't have a phone, we also advise you to provide a valid phone number, so that the operator can contact you in case of need. You can give the phone number of a family member or a friend if you don't have your own. If this is not possible, the operator can still store the produce in the room by selecting 'User without phone' as the cooling user at check-in.",
  },
  {
    id: 8,
    title: 'Which details are needed for logging in as a Registered employee?',
    role: [ERoles.AUTH],
    text: 'Registered employees can log in with email or phone number, and their password.',
  },
  {
    id: 9,
    title: 'Which details are needed for logging in as an Operator?',
    role: [ERoles.AUTH],
    text: 'Operators can log in with their phone number and password.',
  },
  {
    id: 10,
    title: 'Which details are needed for logging in as a Cooling user?',
    role: [ERoles.AUTH],
    text: "Cooling users with smartphone can log in with their phone number and password. Cooling users who don't have a smartphone do not need to log in: the operator can do the operations on their behalf.",
  },
  {
    id: 12,
    title: "I haven't received any invitation per SMS. What should I do?",
    role: [ERoles.AUTH],
    text: 'Registered employees and operators can be invited to join the app by a registered employee of the same company. If the registered employee has invited you, but you have not received any SMS, please contact the registered employee directly. Common causes are: (i) Wrong number typed (note that a country calling code is needed); (ii) You have already accepted an invitation linked to that number. A phone number can only be used for one user. Cooling users with a smartphone can join the app without invitation. Cooling users without a smartphone can be registered in the app by operators.',
  },
  {
    id: 11,
    title: 'I have lost my password. What should I do?',
    role: [ERoles.AUTH],
    text: "If you have lost your password, you can restore your account by clicking on 'Forgot password' at sign in, enter your phone number, and you will receive an SMS with a link to set a new password.",
  },
  {
    id: 36,
    title: 'What is the Knowledge Hub?',
    role: [ERoles.AUTH],
    text: 'The Knowledge Hub is a page that can be reached by clicking on the Menu on the top left. It contains useful information about best storage practices for different commodities, including optimal temperature and approximate storage time under this temperature.',
  },
  {
    id: 13,
    title: 'How can I edit my profile?',
    role: [ERoles.EMPLOYEE],
    text: "By clicking on 'Menu' -> 'Account details', you can see your profile and edit the details (first and last name, phone number, email, and gender). Here you can also change the app language. To change the details of your company, locations, and cooling units, navigate to 'Menu' -> 'Management', and then select the menu item you wish to change.",
  },
  {
    id: 14,
    title: 'How can I edit my profile?',
    role: [ERoles.OPERATOR, ERoles.COOLING_USER],
    text: "By clicking on 'Menu' -> 'Account details', you can see your profile and edit the details (first and last name, phone number, and gender). Here you can also change the app language.",
  },
  {
    id: 15,
    title: 'How can I assign operators to cooling units?',
    role: [ERoles.EMPLOYEE],
    text: "There are three ways to link an operator to a cooling unit. You can assign a cooling unit (or more than one) to an operator when you are sending him/her the invitation. Otherwise, you can modify the cooling units associated with a given operator by navigating to 'Management' -> 'Operators', selecting the operator, and then clicking on 'Select a cooling unit'. Finally, when creating a cooling unit in 'Management' -> 'Cooling units', you can also assign operators to it. Remember to save your changes before exiting!",
  },
  {
    id: 16,
    title:
      'A cooling user arrives at the cold room but has no phone. Can I still register him/her?',
    role: [ERoles.OPERATOR],
    text: "Yes, you can start a check in for that person using the cooling user named 'User without a phone'. As multiple people might use this account for check in, make sure to add a name tag to the crates in the room to identify the owner of each crate.",
  },
  {
    id: 18,
    title: 'How do I register my company?',
    role: [ERoles.EMPLOYEE],
    text: "To register your company, on the welcome screen select 'Sign up as company' and fill in the required information. Enter a password then click 'Sign up' and you are ready to go!",
  },
  {
    id: 19,
    title: 'How do I register a new location for my company?',
    role: [ERoles.EMPLOYEE],
    text: "Each cooling unit needs to be created at a location (and multiple cooling units can be created for the same location). To add a new location for your company, in the menu select 'Management' > 'Locations'. Click on the '+' on the top right corner to add a new location. Fill in the required information. Click 'add' to confirm.",
  },
  {
    id: 20,
    title: 'How do I register a new cooling unit for my company?',
    role: [ERoles.EMPLOYEE],
    text: "To register a new cooling unit for your company, you need to have at least one location created. Then, in the menu select 'Management' > 'Cooling units'. Click on the '+' on the top right corner to add a new cooling unit. Fill in the required information. Click 'add' to confirm.",
  },
  {
    id: 21,
    title: 'How do I invite other Registered employees from my company to register for the app?',
    role: [ERoles.EMPLOYEE],
    text: "To invite other Registered employees for your company, in the menu select 'Management' > ERoles.EMPLOYEE. Click on the '+' on the top right corner to add the telephone number of the employee you want to invite. Click 'Invite' to confirm: your colleague will receive an SMS with a link that guides him/her directly to the sign up screen. In addition, you will also receive an email with the invitation link. Please forward this to the operator in case he/she did not receive it via SMS.",
  },
  {
    id: 22,
    title: 'How do I invite cold storage operators to register for the app?',
    role: [ERoles.EMPLOYEE],
    text: "To send an invitation to operators for your cooling units, in the menu select 'Management' > 'Operators'. Click on the '+' on the top right corner to add the telephone number of the operator you want to invite. Click 'Invite' to confirm: the operator will receive a message with a link that guides him/her directly to the sign up screen. In addition, you will also receive an email with the invitation link. Please forward this to the operator in case he/she did not receive it via SMS.",
  },
  {
    id: 23,
    title: 'How do I monitor the temperature of a cooling unit?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: "To monitor the temperature of a specific cooling unit click on the 'Cooling Units' button on the bottom right corner, navigate to 'Room conditions', and select the unit of interest from the dropdown. In this panel, you will see a graph with the temperature over time - you can scroll to see older data points. If you have sensors connected to the app, you will be able to see the actual room temperature here. Else, the graph will show the temperatures that you have manually set within the app.",
  },
  {
    id: 64,
    title: 'How do I monitor the temperature of a cooling unit?',
    role: [ERoles.COOLING_USER],
    text: "To monitor the temperature of a specific cooling unit click on the 'Cooling Units' button on the bottom right corner, navigate to 'Room conditions', and select the cooling unit of interest from the dropdown. In this panel, you will see a graph with the temperature over time - you can scroll to see older data points. If the room has sensors connected to the app, you will be able to see the actual room temperature here. Else, the graph will show the temperatures that the room operator has manually set within the app.",
  },
  {
    id: 24,
    title: 'How do I monitor the occupancy of a cooling unit?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: "To manage the occupancy of a specific cooling unit click on the 'Cooling Units' icon at the bottom of the screen, navigate to 'Planner', and select the unit of interest from the dropdown. Here you can see the current occupancy (top) and the predicted occupancy for the next 7 days (bottom). The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate.",
  },
  {
    id: 65,
    title: 'How do I monitor the occupancy of a cooling unit?',
    role: [ERoles.COOLING_USER],
    text: "To monitor the occupancy of a specific cooling unit click on the 'Cooling Units' icon at the bottom of the screen, navigate to 'Planner', and select the cooling unit of interest from the dropdown. Here you can see the current occupancy (top) and the predicted occupancy for the next 7 days (bottom). The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate.",
  },
  {
    id: 25,
    title: 'How can I see which items are stored in a room?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: "Click on the 'Dashboard' icon at the bottom of the screen and select the cooling unit of interest from the dropdown to see the list of all stored items in a cooling unit.",
  },
  {
    id: 26,
    title: 'How can I see past check-in and check-outs of a cooling unit?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: "To see past movements of a cooling unit click on the 'History' icon: past check-ins (icons with green crate) and check-outs (icons with orange crate) with transaction details are displayed. If a specific check-out transaction is of interest the search function can assist you in finding it!",
  },
  {
    id: 28,
    title: 'What are the main tasks the operator can do in the app?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: 'The operator can: register new cooling users, initiate check-ins, monitor items in storage and room occupancy, initiate check-outs, and monitor the temperature of the cooling unit he/she is responsible for.',
  },
  {
    id: 29,
    title: 'How can I register new cooling users?',
    role: [ERoles.OPERATOR],
    text: "To register a new cooling user, in the Menu navigate to 'Management' > 'Cooling Users'. Click on the '+' on the top right corner and choose whether to add an already registered user with a code, or add the user details. A cooling user who has a smartphone and has already registered in Coldtivate has a unique code, which he/she can find under 'Menu' -> 'Account details'. If the user has no smartphone, or is not registered yet, you can invite the user by adding the name, gender and telephone number. If the user does not have his/her own number, the number of another person (e.g. friends, relatives) can be used. Click 'Save changes' to confirm. To complete the registration, you need to fill in a short survey by asking a few questions to the cooling user. The survey can also be completed at a later point by navigating to 'Management' -> 'Cooling Users' -> 'Survey'.",
  },
  {
    id: 30,
    title:
      'The cooling user has no time to answer the survey questions at registration. What should I do?',
    role: [ERoles.OPERATOR],
    text: "You can skip the survey questions by clicking 'Complete later'. In this case, you will be prompted to complete the survey the first time you are creating a check in for that cooling user. It is recommended to take the time and answer the survey questions thoroughly: in this way the user can get a more tailored experience with the Coldtivate app!",
  },
  {
    id: 88,
    title:
      "An operator is asking me for a code to add me to the company's list of cooling users. Where can I find the code?",
    role: [ERoles.COOLING_USER],
    text: "When you signed up in Coldtivate, you haev recived an unique identifier in form of a code. This code can be used by an operator to add you to the company's list of cooling users, which is needed for the operators to check-in your crates. The code can be found under 'Menu' -> 'Account Details'.",
  },
  {
    id: 66,
    title: 'I have no time to answer the survey questions at sign up. What should I do?',
    role: [ERoles.COOLING_USER],
    text: "You can skip the survey questions by clicking 'Complete later'. You will find the survey as part of your Account Details and can complete it anytime. However, It is recommended to take the time to answer the survey questions thoroughly when you start using the room: in this way you can get a more tailored experience with the Coldtivate app!",
  },
  {
    id: 67,
    title: 'How can I store something in a room?',
    role: [ERoles.COOLING_USER],
    text: "To complete your first check-in, use the map available in the 'Cooling Unit' tab to search for nearby cold rooms, and then bring your crates to the room. The cold room operator can help you understand how the room works, how you are going to be charged, and what are the benefits of using cold storage.",
  },
  {
    id: 31,
    title: 'How can I initiate a check in?',
    role: [ERoles.OPERATOR],
    text: 'To initiate a check-in, navigate to the Dashboard and click on the Activity Manager button on the lower right, and then click on the green button.',
  },
  {
    id: 32,
    title: 'How can I initiate a check out?',
    role: [ERoles.OPERATOR],
    text: "There are two ways to initiate a check out, both starting in the Dashboard page. You can click on the Activity Manager button on the lower right, and then click on the red button. In this way, you can select for which cooling user (and in which cooling unit) you want to start the check out, and can check out his/her crates from multiple check ins. Alternatively, you can click on 'See details' for an item you see in the Dashboard (make sure to be in the correct cooling unit), and click on 'Check out'. In this case, you can only check-out crates from that storage item.",
  },
  {
    id: 33,
    title: 'How do I connect the sensors in the room with the app?',
    role: [ERoles.EMPLOYEE],
    text: 'In order to connect a sensor to a cooling unit, the sensor needs to have an API setup. The API should use a username and password which are sent through a POST request of Content-Type: application/json. The response should include an accessToken, which can be used for another POST request. The POST request needs to include in the url the room-identifier, the type of value (temperature, humidity), and the token as a header with the key Authorization. The response should be the last recorded temperature in this room, in the format {date: dateTimeStamp, value: numerical}. The temperature should be in Celsius. At the moment, we are supporting the Ecozen and UbiBot sensors APIs. If you have another type of sensors you would like to integrate with Coldtivate, please reach out to app@yourvcca.org.',
  },
  {
    id: 68,
    title: 'How do I connect the sensors in the room with the app?',
    role: [ERoles.OPERATOR],
    text: 'If there are temperature sensors in the room that can be connected to the Coldtivate app, please communicate with your responsible. Only user with a Registered employee role can link sensors to cooling units created in Coldtivate.',
  },
  {
    id: 34,
    title: 'How can I set the temperature of the cooling unit?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: "To set the temperature of the cooling unit, please follow the procedure defined by your company. The app can be used to monitor, but not to update, the temperature in the cold room. However, if the app is not linked to sensors, it is important that you update the set temperature in the app. You can do so by clicking 'Enter temperature' inside the 'Cooling Units' > 'Room conditions' panel. Updating the temperature here will allow you to visualize the temperature evolution in the app and will enable accurate predictions on the remaining days the commodity in storage will be good for. If the app is linked to sensors, the option of changing the temperature in the app will be disabled, and the app will periodically extract this information from the sensors.",
  },
  {
    id: 35,
    title: 'How to contact a cooling user for the post check-out market survey?',
    role: [ERoles.OPERATOR],
    text: "In the 'History' tab you can see the list of the latest check-outs. You should contact each cooling user who did a check out to fill in the market survey, which can be accessed by clicking on the three dots next to the check out and selecting 'Fill in market survey'. By clicking on 'See details', you can check which commodity was in storage and the phone number of the user in case you want to contact him/her by phone. Else, you can wait until the next time the user comes to the cold room to store other produce. A red dot will identify the check outs in the History list for which the market survey has not been completed yet. You will be reminded about the check outs that need your attention in the notification panel 2 days after the check out date.",
  },
  {
    id: 69,
    title: 'What is the post check-out market survey and why should I fill it in?',
    role: [ERoles.COOLING_USER],
    text: "The market survey can be accessed by clicking on the three dots next to each check out in the 'History' tab and selecting 'Fill in market survey'. The survey is very short and asks for information about the selling price of the produce you had previously stored in the room, as well as about how much of it got spoiled. This information will be treated as confidential and solely used by the Coldtivate team to evaluate the impact of using cold storage. A red dot will identify the check outs for which the market survey has not been completed yet. You will be reminded about the check outs that need your attention in the notification panel 2 days after the check out date.",
  },
  {
    id: 37,
    title: 'How do I read the information of one item in the Dashboard?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: "Bold in the middle is the ID of the storage item. The picture and the name below the ID represent the crop in storage. The number next to the basket icons tells you the number of crates inside the cooling unit. The number of days at the top right corner are the predicted remaining storage days (= days until the time to pick up). 'See detail' at the top right corner is a link to the detailed view of the storage item. Below, the name of the cooling user is displayed. The number of days at the bottom right shows how many days so far have they been stored inside the cooling unit. The price indicates the daily price for the whole storage item, i.e. the total price for all crates.",
  },
  {
    id: 38,
    title: 'What is the time to pick up?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'The time to pick up is the suggested number of days left for the cooling user to pick up a commodity. Afterward, the commodity would start to lose its marketability. A time to pick up equal to zero indicates that the user should come to collect the item in storage immediately and has up to 2 days to sell it to the market. It can be seen in the Dashboard (upper right) and in the detailed view for each storage item.',
  },
  {
    id: 39,
    title: 'How is the time to pick up calculated? By which factors is it influenced?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'Fresh vegetables and fruits are perishable, and how they lose their freshness after harvest is largely based on temperature. The time to pick up is, therefore, calculated based on the temperature of the corresponding cooling unit, and on the initial quality of the product when it is brought to the cooling unit. The parameters used in this calculation are unique to each commodity. You can have some insights on how perishability differs among different commodities in the Knowledge Hub.',
  },
  {
    id: 40,
    title: 'The time to pick up is 0 days but the produce is still looking good. Why?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'The time to pick up is the predicted value. Thus, it is possible that a cooling user can check out and still manage to sell well a storage item with time to pick up equal to 0 days. However, be aware that some quality loss is invisible to human eyes, and it is still a good practice to follow the indication given by the time to pick up as much as you can. The time to pick up prediction is especially accurate if the app is linked to temperature sensors. If you don’t have them in place, we advise you to install them in your cooling units. Please refer to the question ‘How do I connect the sensors in the room with the app’ for more information about the setup.',
  },
  {
    id: 41,
    title: 'The time to pick up is more than 0 days but the produce is almost spoiled. Why?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: 'The time to pick up is a predicted value. Thus, rare cases may occur, where the produce gets spoiled while the time to pick up is larger than 0. As quality decay of fresh produce largely depends on temperature, temperature data helps the prediction to be more accurate. For example, the issue may arise when there are no temperature sensors linked to the app, and the operator has set the wrong temperature in the room. If you don’t have temperature sensors in place, we advise you to install them in your cooling units. Please refer to the question ‘How do I connect the sensors in the room with the app’ for more information about the setup.',
  },
  {
    id: 70,
    title: 'The time to pick up is more than 0 days but the produce is almost spoiled. Why?',
    role: [ERoles.COOLING_USER],
    text: 'The time to pick up is a predicted value. Thus, rare cases may occur, where the produce gets spoiled while the time to pick up is larger than 0. As quality decay of fresh produce largely depends on temperature, temperature data helps the prediction to be more accurate. For example, the issue may arise when there are no temperature sensors linked to the app, and the operator has not regularly updated the temperature of the room in the app. Please notify the operator of the room in case this happens.',
  },
  {
    id: 42,
    title:
      'The room occupancy for one of the next days is red (less than 20%). What is this based on? Should I get worried?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: 'The occupancy is shown as red when more than 80% of the cooling unit capacity is utilized. The information about the future occupancy is based on the number of days each user declares as planned days in storage at check-in. Beware that this is just an estimate and might be inaccurate. As such, the red room occupancy is just a sign that the room is getting full. You do not need to worry but can take action accordingly. For example, consider contacting cooling users whose commodity in storage has the lowest time to pick up to advise them to check out soon. You can see an ordered list of the most urgent items to check out under ‘Dashboard’ when you order by time to pick up.',
  },
  {
    id: 43,
    title:
      'A cooling user is bringing to the room a commodity that is not on the list. Can I still check that in?',
    role: [ERoles.OPERATOR],
    text: "Sure, in this case you can start a check in selecting 'Other' from the commodity list.",
  },
  {
    id: 44,
    title:
      'In the Dashboard, each item has a colored bar. What does the color of the bar represent?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'The color represents the remaining days before the time to pick up. You will see the bar in red when it is less than 2 days, in yellow when less than 7 days, and green when more than 7 days. These values are specific for each storage item and are recalculated multiple times per day based on the temperature in the cooling unit. When no model for calculation is available, the color of the bar would be gray.',
  },
  {
    id: 45,
    title:
      'I have successfully completed a check in but cannot yet see the items in the dashboard. Why?',
    role: [ERoles.OPERATOR],
    text: 'The dashboard can take a moment to update. Also please verify that you are looking in the correct cooling unit. If you keep observing the issue, please report it to app@yourvcca.org.',
  },
  {
    id: 46,
    title:
      'I have successfully completed a check out but can still see the items in the dashboard. Why?',
    role: [ERoles.OPERATOR],
    text: 'The dashboard can take a moment to update. Also please verify that the items you checked-out were the correct ones, and that you are looking in the correct cooling unit. If you keep observing the issue, please report it to app@yourvcca.org.',
  },
  {
    id: 47,
    title: 'How can I check that the temperature sensor is working fine?',
    role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
    text: "After a registered employee has enabled a sensor connection to a given cooling unit, the button for manual temperature input in the 'Cooling Units' > 'Room conditions' panel will be grayed-out. The sensor data is fetched every 1 hour, so if the sensor is working properly you should see the temperature plot with new points every hour.",
  },
  {
    id: 48,
    title: 'I got a notification that the sensor is not working. What should I do?',
    role: [ERoles.OPERATOR, ERoles.EMPLOYEE],
    text: "The notification is sent after not receiving data from the sensor for more than 12 hours, and it means the set temperature in the 'Cooling Units' > 'Room conditions' panel is now being used. The app will try to reconnect to the sensor every 1 hour, thus we advise to wait a few hours in case this is a connectivity issue. If there is no new sensor data for several hours or days, the problem might be on the hardware side, for example, the sensor might have run out of battery.",
  },
  {
    id: 49,
    title: 'How can the time to pick up be calculated if there are no sensors?',
    role: [ERoles.EMPLOYEE],
    text: 'When no sensors are connected to the app, the model to calculate the time to pick up relies on the temperature set by the Operator. That is also the reason why the Operator is prompted to input a new set temperature at every new check in and check out. For the model to be accurate, it is crucial that the temperature is up-to-date. Please instruct the operators at your cooling unit about this important step.',
  },
  {
    id: 50,
    title: 'Every time I start a check-in, I get a temperature alert popup. Why?',
    role: [ERoles.OPERATOR],
    text: 'This pop up is a reminder for you to inform the app about the correct set temperature of the cooling room in case no sensors are in place (or if they are not working properly). You should check whether the value indicated in the popup is the same as the one you can read in the control panel at the room. If this is not the case, you should update the temperature. Else, you can confirm and continue with the check in. Having an updated set temperature is very important for the model that calculates the time to pick up to be accurate.',
  },
  {
    id: 51,
    title: 'Every time I complete a check-out, I get a temperature alert popup. Why?',
    role: [ERoles.OPERATOR],
    text: "The temperature of a cooling unit should be set depending on what commodities are in storage, because different commodities have different optimal temperatures (you can see an overview in the Knowledge Hub). The popup appearing after a check out has been completed shows a summary of the commodities that are left in the room and informs you about the optimal temperature for each of them. In this way, you can make an informed decision about whether the temperature in the room should be changed. You can also find this information by going to 'Cooling units' -> 'Crates info'.",
  },
  {
    id: 52,
    title:
      'Why do I need to ask a cooling user to fill in a questionnaire before he/she can check in the first crate?',
    role: [ERoles.OPERATOR],
    text: 'The team developing the app is collecting some basic information about the cooling users when they first start using the room as baseline data that will be compared with the data acquired by the app. The sole intent is to improve the app design and cold room utilization.',
  },
  {
    id: 71,
    title: 'Why do I need to fill in a questionnaire when I register on the app?',
    role: [ERoles.COOLING_USER],
    text: 'The team developing the app is collecting some basic information about the cooling users when they first start using the room as baseline data that will be compared with the data acquired by the app. The sole intent is to improve the app design and cold room utilization.',
  },
  {
    id: 53,
    title: 'Why do I need to ask cooling users about the selling price of each storage item?',
    role: [ERoles.OPERATOR],
    text: 'You will be asked to contact a cooling user who has recently checked out some produce from the room and ask about where and for which price they have sold the item that was stored in the room. This information will help the team developing the app to validate and improve the accuracy of the market prices forecasts provided.',
  },
  {
    id: 54,
    title: "I don't understand parts of the app. Who should I contact?",
    role: [ERoles.EMPLOYEE],
    text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If you would like to get in contact with the app support team, please send an email to app@yourvcca.org.',
  },
  {
    id: 55,
    title: "I don't understand parts of the app. Who should I contact?",
    role: [ERoles.OPERATOR],
    text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If your question is still unanswered, please contact the Registered employee you are reporting to.',
  },
  {
    id: 73,
    title: "I don't understand parts of the app. Who should I contact?",
    role: [ERoles.COOLING_USER],
    text: 'Make sure to check the tutorial and the FAQ section, as they contain useful information about the app which may help to clarify your questions. If your question is still unanswered, please contact the operator of a cold room, or write to app@yourvcca.org',
  },
  {
    id: 56,
    title: 'I found a bug in the app. Who should I contact?',
    role: [ERoles.EMPLOYEE],
    text: 'Please make sure you have the latest version of the app installed. If the problem persists, please notify the app support team by sending an email to app@yourvcca.org or by filling in the feedback form: https://forms.gle/ceohKHT2QCcE3rFs5 .',
  },
  {
    id: 57,
    title: 'Something is not working properly in the app. Who should I contact?',
    role: [ERoles.OPERATOR],
    text: 'Please make sure you have the latest version of the app installed. If the problem persists, please contact the Registered employee you are reporting to and / or notify the app support team by sending an email to app@yourvcca.org or by filling in the feedback form: https://forms.gle/2gKVzZjkJSPqEAan9 .',
  },
  {
    id: 74,
    title: 'Something is not working properly in the app. Who should I contact?',
    role: [ERoles.COOLING_USER],
    text: 'Please make sure you have the latest version of the app installed. If the problem persists, please contact the operator of a cold room and / or notify the app support team by sending an email to app@yourvcca.org.',
  },
  {
    id: 58,
    title: 'I want to provide feedback about my experience with the app. Who should I contact?',
    role: [ERoles.EMPLOYEE],
    text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org or submit your feedback via the form: https://forms.gle/ceohKHT2QCcE3rFs5 .',
  },
  {
    id: 86,
    title: 'I want to provide feedback about my experience with the app. Who should I contact?',
    role: [ERoles.OPERATOR],
    text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org or submit your feedback via the form: https://forms.gle/2gKVzZjkJSPqEAan9.',
  },
  {
    id: 87,
    title: 'I want to provide feedback about my experience with the app. Who should I contact?',
    role: [ERoles.COOLING_USER],
    text: 'The app support team would love to hear about your experience using this app and welcomes your feedback, please send an email to app@yourvcca.org.',
  },
  {
    id: 17,
    title: 'I am in an area where there is low internet connection: Can I still use the app?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'Currently, only the Knowledge Hub section is available offline. Additional parts of the app will soon be accessible even without an internet connection.',
  },
  {
    id: 60,
    title: "Which prices are displayed when clicking on the 'Market prices' icon?",
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'In this tab, you can see the market price predictions either in a plot or in a table format. The Price Trend page allows for visualizing the last month of data and the 14-days forecast for a specific market and commodity (in India) or a monthly forecast per state (in Nigeria). The Price Ranking page allows to visualize all market prices forecasts ordered from highest to lowest, and with the posibility to filter by date, state, district and market (in India).',
  },
  {
    id: 61,
    title: "Why are some states and markets missing in the 'Market prices' section?",
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'Due to data availability, the model has only been implemented for a few commodities in some selected states in India and Nigeria. The Market Prices tab only lists market, commodities and states for which a forecast is available.',
  },
  {
    id: 62,
    title: 'How are the future market prices calculated?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR, ERoles.COOLING_USER],
    text: 'A machine learning model is trained on historical market price data and other data such as currency conversion rate and petrol price, to make forecasts of future market prices.',
  },
  {
    id: 75,
    title: 'I would like to delete my account. What should I do?',
    role: [ERoles.EMPLOYEE],
    text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you are the last Registered Employee of the company, this action will delete the company. If there are pending checkins, you will not be able to delete your account until all the crates have been checked-out in the app by one of your operators.",
  },
  {
    id: 76,
    title: 'I would like to delete my account. What should I do?',
    role: [ERoles.OPERATOR],
    text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you are the last Operator assigned to one of the rooms where there are open check-ins, you cannot delete your account until a registered employee assigns another operator to the room, or all crates have been checked-out in the app.",
  },
  {
    id: 77,
    title: 'I would like to delete my account. What should I do?',
    role: [ERoles.COOLING_USER],
    text: "To delete your account you can navigate to 'Menu' -> 'Account Details', and click Delete. Please be careful, this action can not be reversed! If you have open check-ins in any of the rooms, you can not delete your account until all crates are checked-out from the rooms. Please make sure to collect your crates at the room! In case you think there are pending crates in the app that you have already removed, please communicate with the room's operator to sort it out.",
  },
  {
    id: 78,
    title: 'How can I delete a cooling unit or a location?',
    role: [ERoles.EMPLOYEE],
    text: "You can delete cooling units and locations going to 'Menu' -> 'Management' -> 'Cooling Units' / 'Locations' and clicking Delete. You will only be able to do so if there are no pending check-ins in the rooms. Else, please communicate to the operators to complete the check-outs before you attempt to delete the rooms and locations.",
  },
  {
    id: 79,
    title: 'How can I delete another registered employee or an operator from my company?',
    role: [ERoles.EMPLOYEE],
    text: "You are not allowed to delete other users from the app. However, you can unassign operators from your rooms by navigating to 'Menu' -> 'Management' -> 'Operators'. If you still want to enitrely remove the user so that they don't have access to your company, please write an email to app@yourvcca.org and explain why this is needed.",
  },
  {
    id: 80,
    title: 'How can I delete a cooling user from the list?',
    role: [ERoles.OPERATOR],
    text: "To delete a cooling user from the list, navigate to 'Management' -> 'Cooling Users', click on the cooling user name and then the button 'Delete'. Please note that only users with no pending check-ins can be deleted! If there are pending check-ins, please contact the user to pick up the produce. Note that this action cannot be reversed! If the user has a smartphone, this operation will remove him/her from your list, but the user will still be able to use Coldtivate. If the user has no smartphone, this operation deletes his/her account and frees the associated phone number.",
  },
  {
    id: 81,
    title: 'Where can I monitor whether the operators have used the app recently?',
    role: [ERoles.EMPLOYEE],
    text: "To check the last time the operators and other registered employees have logged in into the app, you can navigate to 'Menu' -> 'Management' -> ERoles.OPERATOR / ERoles.EMPLOYEE. The date and time you see next to the name are the last login date and time.",
  },
  {
    id: 82,
    title: 'Where can I monitor the revenue generated by each room and other usage statistics?',
    role: [ERoles.EMPLOYEE, ERoles.OPERATOR],
    text: "You can navigate to 'Menu' -> 'Management' -> 'Revenue Analysis', select the cooling units and the time interval of interest, and you will see the total revenue associated with the check-out from these rooms. You can also filter by cooling user, payment method, and crop. To visualise summary statistics of your check-ins per room (as number of users, total number of crates, etc), you can navigate to 'Menu' -> 'Management' -> 'Usage Analysis'. Also here you can filter by date, cooling user, and crop. Finally, to monitor the total number of crates, weight, and optimal temperatures for the crops currently in the room, you can navigate to 'Cooling units' -> 'Crates info'.",
  },
  {
    id: 83,
    title:
      'How can I find out who is the contact person for a cooling unit where my produce is stored?',
    role: [ERoles.COOLING_USER],
    text: 'By clicking on an item in the dashboard, you can see the name and the contact number of the operator who did the check in for you. You can copy the number to clipboard and contact the operator per phone or sms.',
  },
  {
    id: 84,
    title: 'I have received a notification. What should I do?',
    role: [ERoles.COOLING_USER],
    text: "You might receive two type of notifications: first, the app can inform you about the fact that some of the crates you have stored are about to get spolied. We advise you to collect the crates from the room as fast as possible. Another notification you might receive is to remind you to complete the post check-out market survey. The check-outs for which the market survey has not be filled in are marked by a red dot in the 'History' tab. The survey is very quick to complete and asks you about the price at which the produce you had in storage was sold, and whether any part of the produce was spoiled after check-out. This information is very valuable for the Coldtivate team to monitor the benefit of using cold rooms compared to storing the produce outside.",
  },
  {
    id: 85,
    title: 'What is displayed on the map of cooling units?',
    role: [ERoles.COOLING_USER],
    text: 'On the map you can visualize your location (you will be asked for permission for Coldtivate to access your location), hte location of the cooling units around you, and some information about the units (single or multicommodity, company, pricing).',
  },
];
