import { APP_LOCALES, TranslationLocales } from '#i18n/constants';

type MethodologyEntry = {
  title: string;
  text: string;
};

export const METHODOLOGY_CONTENT: Record<TranslationLocales, MethodologyEntry[]> = {
  [APP_LOCALES.ENGLISH]: [
    {
      title: 'Company name',
      text: 'The name of the company as it is registered in Coldtivate.',
    },
    {
      title: 'Total revenue',
      text: "The company's total revenue generated by collecting storage fees for the crates that have been checked-in in the Coldtivate app.",
    },
    {
      title: 'Total cooling capacity',
      text: 'The summed capacity of all cooling units registered in the app for your company.',
    },
    {
      title: 'No. of cooling units',
      text: 'The total number of cooling units registered in the app for your company.',
    },
    {
      title: 'Cooling unit type',
      text: 'Total number of cooling units that are located at the farm-gate, at the market, or are refrigerated trucks. The information is inserted by the registered employee that creates the cooling unit in the app.',
    },
    {
      title: 'Total number of registered employees',
      text: 'Number of users linked to your company that signed up as ‘Registered Employee’, i.e. members of the management team that are overseeing operations at the cooling units. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. This indicator is only present in the ‘Company’ view because registered employees are not linked to a single cooling unit, but to the whole company.',
    },
    {
      title: 'Total number of operators',
      text: 'Number of users linked to your company that signed up as ‘Operators’, i.e. employees physically present at the cooling units and interacting with cooling customers. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. In the ‘Aggregated’ and ‘Comparison’ views, only the operators assigned to the selected cooling units are considered.',
    },
    {
      title: 'Total number of distinct cooling users',
      text: 'Number of cooling customers across all cooling units of a company since joining the app. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. This indicator is only present in the ‘Company’ view. In the ‘Aggregated’ and ‘Comparison’ views, we instead report on the number of active cooling users.',
    },
    {
      title: 'Total number of active cooling users',
      text: 'Number of distinct users that have done a check-in or check-out operation in at least one of the cooling units in the selected time period. The gender split is calculated from the gender of the cooling users, as declared during registration. This indicator is only present in the ‘Aggregated’ and ‘Comparison’ views.',
    },
    {
      title: 'Type of cooling users',
      text: 'Cooling users that fill in the ‘Cooling user survey’ are asked to specify whether they identify themselves as ‘farmers’, or as ‘small vendors / traders / wholesalers’. This indicator shows the summary statistics for the subset of cooling users that have answered this question in the survey.',
    },
    {
      title: 'Total number of indirect beneficiaries',
      text: 'The number of indirect beneficiaries is calculated by multiplying the total number of cooling users by the average household size for the country where the company is located. In the ‘Company’ view, the ‘Total number of district cooling users’ is used, whereas in the ‘Aggregated’ and ‘Comparison’ views, the ‘Total number of active cooling users’ is used. The male - female split is calculated using the average gender ratio for the country of the company. The information about the average household size and gender ratio are extracted from https://population.un.org/Household/index.html#/countries/.',
    },
    {
      title: 'Check-in crop distribution (crates)',
      text: 'Number of crates that have been checked-in via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-in crates.',
    },
    {
      title: 'Check-out crop distribution (crates)',
      text: 'Number of crates that have been checked-out via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-out crates.',
    },
    {
      title: 'Check-in crop distribution (kg)',
      text: 'Total quantities, in kilograms, that have been checked-in via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-in crates.',
    },
    {
      title: 'Check-out crop distribution (kg)',
      text: 'Total quantities, in kilograms, that have been checked-out via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-out crates.',
    },
    {
      title: 'Average occupancy of cooling units',
      text: 'For each unit, the average daily occupancy is calculated as the number of crates stored in the unit divided by the total number of crates that can be stored in the unit, which is defined by the registered employee that creates the cooling unit in the app. This value is then averaged across all units for company and time period. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ views, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total crates',
      text: 'Total number of crates that have been checked-in and checked-out via the app. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total quantity (kg)',
      text: 'Total kilograms of produce that has been checked-in and checked-out via the app. The kilograms per crate are defined at time of check-in. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total operations',
      text: 'Total number of check-in and check-out operations that have been recorded via the app. Each operation can include the check-in or check-out of multiple crates of different commodities. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Food loss evolution',
      text: `Food loss evolution is expressed as a percentage to describe the average amount of food lost/saved per month for each user and crop type. To estimate this value, for each user and crop, baseline loss data (namely data collected from cooling users when they register on the app) is compared to postharvest loss data collected regularly as the user stores crops in the cooling unit. Baseline data is collected from the ‘Cooling User Survey’, where farmers and traders are asked questions about the weekly amount of food produced, sold, and lost that they experience (without cold storage) for each crop. As the farmers and traders use the cooling units, ‘Post-checkout’ surveys are conducted weekly for each type of crop that a user has stored in the room. In this survey, the user is asked about quantities sold and lost after cold storage. Data from post-checkout surveys is aggregated monthly to estimate what is the postharvest loss level experienced by each user and crop type as they use cold storage, and compared to the baseline. Data across crops and users of each cooling unit are averaged over time periods and cooling units to yield the percentages displayed on the Impact Dashboard. The food loss evolution is the percentage difference between the percentage lost in the ‘post-checkout’ surveys (i.e. while utilising cooling) and the percentage lost in baseline (i.e. before cold storage).`,
    },
    {
      title: 'Cooling user revenue evolution',
      text: `The revenue evolution for cooling users describes the average percentage change in the farmer revenue calculated comparing the revenue generated by selling produce stored in the cold room and by selling produce before the farmer starts using cold storage (‘baseline’ data). Baseline data is collected from the ‘Cooling User Survey’, where farmers and traders are asked questions about the amount and selling price of crops sold per week when they join the app, i.e. before they start using cold storage. As the farmers and traders use the cooling units, ‘Post-checkout’ surveys are conducted weekly for each type of crop that a user has stored in the room. In this survey, the user is asked about quantities sold and selling price after cold storage. Data from post-checkout surveys is aggregated monthly to estimate what is the total monthly revenue experienced by each user and crop type as they use cold storage, and this value is compared to the baseline. Data across crops and users of each cooling unit are averaged over time periods and cooling units to yield the values displayed on the Impact Dashboard. The revenue evolution is the percentage difference between the average revenue estimated from the ‘post-checkout’ surveys (i.e. while utilising cooling) and the average revenue estimated from the baseline (i.e. before cold storage).`,
    },
    {
      title: 'No. of surveys used to calculate food loss and revenue evolution',
      text: `The metrics on food loss and revenue evolution rely on the surveys that cooling users are asked to fill in as they are active on the app. To get a glimpse on the amount of data that is being aggregated to calculate these percentages, we count here the total number of ‘Post-checkout’ surveys filled by cooling users since company creation up until the current month, compared with the maximum possible number of surveys that could be filled for the company in the current month. The maximum number of surveys that could be filled is estimated using the total number of distinct crops checked for each cooling user since company creation.`,
    },
    {
      title: 'CO2 evolution',
      text: `The CO2 Emissions Daily Report featured on the Impact Dashboard is meticulously derived from a combination of real-time cold room storage analytics and robust Life Cycle Assessment (LCA) models provided by Eco-Invent. By integrating live check-in data from our application, we systematically track the volume of each type of produce stored in the cold rooms on a daily basis. This pertinent data, coupled with auxiliary parameters sourced from Eco-Invent's comprehensive LCA databases, is utilized to accurately recalculate the daily CO2 emissions attributable to each stored crop. The resultant insights are then elegantly visualized and made available for export via the Impact Dashboard, ensuring that our users have transparent and actionable environmental impact data at their fingertips.`,
    },
  ],
  [APP_LOCALES.HINDI]: [
    {
      title: 'कंपनी का नाम',
      text: 'कंपनी का नाम जैसा कि Coldtivate में पंजीकृत है।',
    },
    {
      title: 'कुल राजस्व',
      text: 'कंपनी का कुल राजस्व जो Coldtivate ऐप में चेक-इन की गई पेटियों के लिए भंडारण शुल्क एकत्र करके उत्पन्न होता है।',
    },
    {
      title: 'कुल शीतलन क्षमता',
      text: 'ऐप में आपकी कंपनी के लिए पंजीकृत सभी शीतलन इकाइयों की कुल क्षमता।',
    },
    {
      title: 'शीतलन इकाइयों की संख्या',
      text: 'ऐप में आपकी कंपनी के लिए पंजीकृत शीतलन इकाइयों की कुल संख्या।',
    },
    {
      title: 'शीतलन इकाई प्रकार',
      text: 'शीतलन इकाइयों की कुल संख्या जो खेत के दरवाजे पर, बाजार में या रेफ्रिजेरेटेड ट्रकों में स्थित हैं। यह जानकारी पंजीकृत कर्मचारी द्वारा डाली जाती है जो ऐप में शीतलन इकाई बनाता है।',
    },
    {
      title: 'कुल पंजीकृत कर्मचारियों की संख्या',
      text: "आपकी कंपनी से जुड़े उपयोगकर्ताओं की संख्या जिन्होंने 'पंजीकृत कर्मचारी' के रूप में साइन अप किया है, अर्थात प्रबंधन टीम के सदस्य जो शीतलन इकाइयों पर संचालन की देखरेख कर रहे हैं। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। यह सूचकांक केवल 'कंपनी' दृश्य में मौजूद है क्योंकि पंजीकृत कर्मचारी किसी एक शीतलन इकाई से नहीं, बल्कि पूरी कंपनी से जुड़े होते हैं।",
    },
    {
      title: 'कुल ऑपरेटरों की संख्या',
      text: "आपकी कंपनी से जुड़े उपयोगकर्ताओं की संख्या जिन्होंने 'ऑपरेटर' के रूप में साइन अप किया है, अर्थात वे कर्मचारी जो शीतलन इकाइयों पर शारीरिक रूप से उपस्थित होते हैं और शीतलन ग्राहकों के साथ बातचीत करते हैं। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। 'एकीकृत' और 'तुलना' दृश्य में, केवल चयनित शीतलन इकाइयों को सौंपे गए ऑपरेटरों को ही माना जाता है।",
    },
    {
      title: 'कुल विशिष्ट शीतलन उपयोगकर्ताओं की संख्या',
      text: "ऐप में शामिल होने के बाद कंपनी की सभी शीतलन इकाइयों में कुल शीतलन ग्राहकों की संख्या। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। यह सूचकांक केवल 'कंपनी' दृश्य में मौजूद है। 'एकीकृत' और 'तुलना' दृश्य में, हम सक्रिय शीतलन उपयोगकर्ताओं की संख्या की रिपोर्ट करते हैं।",
    },
    {
      title: 'कुल सक्रिय शीतलन उपयोगकर्ताओं की संख्या',
      text: "चयनित समय अवधि में कम से कम एक शीतलन इकाई में चेक-इन या चेक-आउट संचालन करने वाले विशिष्ट उपयोगकर्ताओं की संख्या। लिंग विभाजन पंजीकरण के समय घोषित शीतलन उपयोगकर्ताओं के लिंग से गणना की जाती है। यह सूचकांक केवल 'एकीकृत' और 'तुलना' दृश्य में मौजूद है।",
    },
    {
      title: 'शीतलन उपयोगकर्ताओं का प्रकार',
      text: "शीतलन उपयोगकर्ता जो 'शीतलन उपयोगकर्ता सर्वेक्षण' भरते हैं उनसे पूछा जाता है कि वे अपने आप को 'किसान' या 'छोटे विक्रेता / व्यापारी / थोक व्यापारी' के रूप में पहचानते हैं या नहीं। यह सूचकांक उन शीतलन उपयोगकर्ताओं के लिए संक्षिप्त सांख्यिकी दर्शाता है जिन्होंने इस प्रश्न का सर्वेक्षण में उत्तर दिया है।",
    },
    {
      title: 'कुल अप्रत्यक्ष लाभार्थियों की संख्या',
      text: "अप्रत्यक्ष लाभार्थियों की संख्या की गणना कुल शीतलन उपयोगकर्ताओं की संख्या को उस देश के औसत परिवार आकार से गुणा करके की जाती है जहां कंपनी स्थित है। 'कंपनी' दृश्य में, 'कुल विशिष्ट शीतलन उपयोगकर्ताओं' का उपयोग किया जाता है, जबकि 'एकीकृत' और 'तुलना' दृश्य में, 'कुल सक्रिय शीतलन उपयोगकर्ताओं' का उपयोग किया जाता है। पुरुष - महिला विभाजन कंपनी के देश के औसत लिंग अनुपात का उपयोग करके गणना की जाती है। औसत परिवार आकार और लिंग अनुपात की जानकारी https://population.un.org/Household/index.html#/countries/ से प्राप्त की जाती है।",
    },
    {
      title: 'चेक-इन फसल वितरण (पेटियाँ)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-इन की गई पेटियों की संख्या। वस्तुओं की सूची चेक-इन की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-आउट फसल वितरण (पेटियाँ)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-आउट की गई पेटियों की संख्या। वस्तुओं की सूची चेक-आउट की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-इन फसल वितरण (किलोग्राम)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-इन की गई कुल मात्रा, किलोग्राम में। वस्तुओं की सूची चेक-इन की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-आउट फसल वितरण (किलोग्राम)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-आउट की गई कुल मात्रा, किलोग्राम में। वस्तुओं की सूची चेक-आउट की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'शीतलन इकाइयों का औसत अधिभोग',
      text: "प्रत्येक इकाई के लिए, औसत दैनिक अधिभोग की गणना इकाई में संग्रहीत पेटियों की संख्या को इकाई में संग्रहीत की जा सकने वाली कुल पेटियों की संख्या से विभाजित करके की जाती है, जो ऐप में शीतलन इकाई बनाने वाले पंजीकृत कर्मचारी द्वारा परिभाषित होती है। यह मान तब सभी इकाइयों और समय अवधि के लिए कंपनी के लिए औसत निकाला जाता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल पेटियाँ',
      text: "ऐप के माध्यम से चेक-इन और चेक-आउट की गई कुल पेटियों की संख्या। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल मात्रा (किलोग्राम)',
      text: "ऐप के माध्यम से चेक-इन और चेक-आउट की गई कुल उपज के किलोग्राम। चेक-इन के समय पेटी के किलोग्राम को परिभाषित किया जाता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल संचालन',
      text: "ऐप के माध्यम से दर्ज किए गए कुल चेक-इन और चेक-आउट संचालन। प्रत्येक संचालन में विभिन्न वस्तुओं की कई पेटियों का चेक-इन या चेक-आउट शामिल हो सकता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'खाद्य हानि विकास',
      text: `खाद्य हानि विकास शीतलन उपयोगकर्ताओं द्वारा शीतलन इकाइयों का उपयोग करने से पहले की तुलना में शीतलन इकाइयों का उपयोग करने के बाद खोई गई फसल की औसत मात्रा का प्रतिशत परिवर्तन दर्शाता है। इसे समय अवधि, शीतलन इकाइयों के सेट, उपयोगकर्ता और फसल प्रकार के लिए प्रति माह खोए/बचाए गए खाद्य की औसत मात्रा को वर्णित किया जा सके। इस मान का अनुमान लगाने के लिए, प्रत्येक उपयोगकर्ता और फसल के लिए, बेसलाइन हानि डेटा (अर्थात् ऐप पर पंजीकरण के समय शीतलन उपयोगकर्ताओं से एकत्रित डेटा) की तुलना नियमित रूप से संग्रहीत फसलों के बाद की हानि डेटा से की जाती है। बेसलाइन डेटा 'शीतलन उपयोगकर्ता सर्वेक्षण' से एकत्रित किया जाता है, जहां किसानों और व्यापारियों से प्रत्येक फसल के लिए उत्पादित, बेची और खोई गई साप्ताहिक मात्रा के बारे में प्रश्न पूछे जाते हैं (बिना ठंडे भंडारण के)। जब किसान और व्यापारी शीतलन इकाइयों का उपयोग करते हैं, तो 'पोस्ट-चेकआउट' सर्वेक्षण प्रत्येक प्रकार की फसल के लिए साप्ताहिक रूप से किया जाता है जिसे उपयोगकर्ता ने कक्ष में संग्रहीत किया है। इस सर्वेक्षण में, उपयोगकर्ता से ठंडे भंडारण के बाद बेची और खोई गई मात्राओं के बारे में पूछा जाता है। पोस्ट-चेकआउट सर्वेक्षणों से डेटा को मासिक रूप से संकलित किया जाता है ताकि यह अनुमान लगाया जा सके कि ठंडे भंडारण का उपयोग करने के दौरान प्रत्येक उपयोगकर्ता और फसल प्रकार द्वारा क्या पोस्टहार्वेस्ट हानि स्तर का अनुभव किया गया है, और इसे बेसलाइन के साथ तुलना की जाती है। प्रत्येक समय अवधि और शीतलन इकाइयों के लिए फसलों और उपयोगकर्ताओं में डेटा का औसत निकालकर प्रभाव डैशबोर्ड पर प्रदर्शित प्रतिशत प्राप्त होते हैं। खाद्य हानि विकास वह प्रतिशत अंतर है जो 'पोस्ट-चेकआउट' सर्वेक्षणों (अर्थात् शीतलन का उपयोग करते समय) में खोए गए प्रतिशत और बेसलाइन (अर्थात् ठंडे भंडारण से पहले) में खोए गए प्रतिशत के बीच है।`,
    },
    {
      title: 'शीतलन उपयोगकर्ता राजस्व विकास',
      text: `शीतलन उपयोगकर्ताओं के लिए राजस्व विकास किसान राजस्व में औसत प्रतिशत परिवर्तन का वर्णन करता है जो ठंडे कमरे में संग्रहीत उत्पाद को बेचने से उत्पन्न राजस्व की तुलना में किया जाता है और किसान ठंडे भंडारण का उपयोग करने से पहले उत्पाद बेचने से उत्पन्न राजस्व ('बेसलाइन' डेटा) का तुलना करता है। बेसलाइन डेटा 'शीतलन उपयोगकर्ता सर्वेक्षण' से एकत्रित किया जाता है, जहां किसानों और व्यापारियों से ऐप में शामिल होने के समय प्रति सप्ताह बेचे जाने वाली फसलों की मात्रा और बिक्री मूल्य के बारे में प्रश्न पूछे जाते हैं, अर्थात् ठंडे भंडारण का उपयोग शुरू करने से पहले। जब किसान और व्यापारी शीतलन इकाइयों का उपयोग करते हैं, तो 'पोस्ट-चेकआउट' सर्वेक्षण प्रत्येक प्रकार की फसल के लिए साप्ताहिक रूप से किया जाता है जिसे उपयोगकर्ता ने कक्ष में संग्रहीत किया है। इस सर्वेक्षण में, उपयोगकर्ता से ठंडे भंडारण के बाद बेची गई मात्राओं और बिक्री मूल्य के बारे में पूछा जाता है। पोस्ट-चेकआउट सर्वेक्षणों से डेटा को मासिक रूप से संकलित किया जाता है ताकि यह अनुमान लगाया जा सके कि ठंडे भंडारण का उपयोग करने के दौरान प्रत्येक उपयोगकर्ता और फसल प्रकार द्वारा क्या मासिक राजस्व का अनुभव किया गया है, और इस मान को बेसलाइन के साथ तुलना की जाती है। प्रत्येक समय अवधि और शीतलन इकाइयों के लिए फसलों और उपयोगकर्ताओं में डेटा का औसत निकालकर प्रभाव डैशबोर्ड पर प्रदर्शित मान प्राप्त होते हैं। राजस्व विकास वह प्रतिशत अंतर है जो 'पोस्ट-चेकआउट' सर्वेक्षणों (अर्थात् शीतलन का उपयोग करते समय) से अनुमानित औसत राजस्व और बेसलाइन (अर्थात् ठंडे भंडारण से पहले) से अनुमानित औसत राजस्व के बीच है।`,
    },
    {
      title: 'खाद्य हानि और राजस्व विकास की गणना के लिए उपयोग किए गए सर्वेक्षणों की संख्या',
      text: `खाद्य हानि और राजस्व विकास पर मेट्रिक्स उन सर्वेक्षणों पर निर्भर करती हैं जिन्हें शीतलन उपयोगकर्ताओं से भरा जाता है क्योंकि वे ऐप पर सक्रिय होते हैं। इन प्रतिशतों की गणना के लिए संकलित किए जा रहे डेटा की झलक पाने के लिए, हम यहां कंपनी निर्माण के बाद से वर्तमान माह तक शीतलन उपयोगकर्ताओं द्वारा भरे गए कुल 'पोस्ट-चेकआउट' सर्वेक्षणों की गणना करते हैं, जिसे वर्तमान माह में कंपनी के लिए भरे जा सकने वाले अधिकतम संभावित सर्वेक्षणों की तुलना में दर्शाते हैं। अधिकतम संभावित सर्वेक्षणों की संख्या का अनुमान प्रत्येक शीतलन उपयोगकर्ता के लिए कंपनी निर्माण के बाद से जांचे गए विशिष्ट फसलों की कुल संख्या का उपयोग करके किया जाता है।`,
    },
    {
      title: 'CO2 विकास',
      text: `प्रभाव डैशबोर्ड पर प्रदर्शित CO2 उत्सर्जन दैनिक रिपोर्ट वास्तविक समय के ठंडे कक्ष भंडारण विश्लेषण और Eco-Invent द्वारा प्रदान किए गए मजबूत जीवन चक्र मूल्यांकन (LCA) मॉडलों के संयोजन से सावधानीपूर्वक व्युत्पन्न की जाती है। हमारे एप्लिकेशन से लाइव चेक-इन डेटा को एकीकृत करके, हम प्रतिदिन ठंडे कमरों में संग्रहीत प्रत्येक प्रकार की उपज की मात्रा को व्यवस्थित रूप से ट्रैक करते हैं। यह प्रासंगिक डेटा, Eco-Invent के व्यापक LCA डेटाबेस से प्राप्त सहायक मापदंडों के साथ मिलकर, प्रतिदिन संग्रहीत प्रत्येक फसल के लिए जिम्मेदार CO2 उत्सर्जन की सटीक पुन: गणना के लिए उपयोग किया जाता है। परिणामी अंतर्दृष्टि को प्रभाव डैशबोर्ड के माध्यम से निर्यात के लिए उपलब्ध कराया जाता है, जिससे हमारे उपयोगकर्ताओं के पास पारदर्शी और क्रियाशील पर्यावरणीय प्रभाव डेटा उनकी उंगलियों पर होता है।`,
    },
  ],
  [APP_LOCALES.ORIYA]: [
    {
      title: 'କମ୍ପାନୀର ନାମ',
      text: 'କୋଲ୍ଡଟିଭେଟରେ ନୋଟ୍ କରାଯାଇଥିବା କମ୍ପାନୀର ନାମ।',
    },
    {
      title: 'ମୋଟ ଆବକା',
      text: 'କୋଲ୍ଡଟିଭେଟ ଆପ୍ଲିକେସନ୍ ମାଧ୍ୟମରେ ଚେକ୍-ଇନ୍ ହୋଇଥିବା କ୍ରେଟ୍‌ସ ପାଇଁ ସଂଗ୍ରହ ଫୀ ହାସଲ କରାଯାଇଥିବା କମ୍ପାନୀର ମୋଟ ଆବକା।',
    },
    {
      title: 'ମୋଟ କୁଲିଙ୍ଗ କ୍ଷମତା',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ଆପଣଙ୍କର କମ୍ପାନୀ ପାଇଁ ନୋଟ୍ କରାଯାଇଥିବା ସମସ୍ତ କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସର ସଙ୍ଗ୍ରହ କ୍ଷମତା।',
    },
    {
      title: 'କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସର ସଂଖ୍ୟା',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ଆପଣଙ୍କର କମ୍ପାନୀ ପାଇଁ ନୋଟ୍ କରାଯାଇଥିବା ମୋଟ କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସ।',
    },
    {
      title: 'କୁଲିଙ୍ଗ ଇୁନିଟ୍ ର ପ୍ରକାର',
      text: 'ଫାର୍ମ-ଗେଟ୍‌, ବଜାରରେ ବସିଥିବା କିମ୍ବା ରେଫ୍ରିଜରେଟେଡ୍ ଟ୍ରକ୍‌ରେ ଥିବା ମୋଟ କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସର ସଂଖ୍ୟା। ମାନିତା ପ୍ରଦାନକାରୀ କର୍ମଚାରୀ ଦ୍ୱାରା ଆପ୍ଲିକେସନ୍‌ରେ କୁଲିଙ୍ଗ ଇୁନିଟ୍ ତିଆରି କରାଯାଇଛି।',
    },
    {
      title: 'ନୋଟ୍ କରାଯାଇଥିବା କର୍ମଚାରୀଙ୍କର ମୋଟ ସଂଖ୍ୟା',
      text: 'ଆପଣଙ୍କର କମ୍ପାନୀ ସହିତ ସଂଯୋଗ ଥିବା ବ୍ୟବହାରକାରୀଙ୍କର ସଂଖ୍ୟା ଯେଉଁମାନେ ‘ନୋଟ୍ କରାଯାଇଥିବା କର୍ମଚାରୀ’ ଭାବରେ ସାଇନ୍ ଅପ୍ କରିଛନ୍ତି, ଯାହାକି କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସର ଓପରେସନ୍‌କୁ ନିରୀକ୍ଷଣ କରେଥିବା ବ୍ୟବସ୍ଥାପନ ଟୀମ୍‌ର ସଦସ୍ୟମାନେ। ସମସ୍ତ ବ୍ୟବହାରକାରୀଙ୍କୁ ନୋଟ୍ କରାଯାଇଥିବା ସମୟରେ ‘ପୁରୁଷ’, ‘ସ୍ତ୍ରୀ’, କିମ୍ବା ‘ଅନ୍ୟ’ ଭାବରେ ଲିଙ୍ଗ ସୂଚନା ଦିଆଯିବାକୁ କହାଯାଇଛି। ଏହି ସୂଚକ ସେବେ ‘କମ୍ପାନୀ’ ଦୃଶ୍ୟରେ ଉପସ୍ଥିତ, କାରଣ ନୋଟ୍ କରାଯାଇଥିବା କର୍ମଚାରୀମାନେ ଏକେକ କୁଲିଙ୍ଗ ଇୁନିଟ୍ ସହିତ ନୁହେଁ, ବରଂ ସମସ୍ତ କମ୍ପାନୀ ସହିତ ସଂଯୋଗ ରହିଛି।',
    },
    {
      title: 'ଓପରେଟର୍‌ମାନେର ମୋଟ ସଂଖ୍ୟା',
      text: 'ଆପଣଙ୍କର କମ୍ପାନୀ ସହିତ ସଂଯୋଗ ଥିବା ବ୍ୟବହାରକାରୀଙ୍କର ସଂଖ୍ୟା ଯେଉଁମାନେ ‘ଓପରେଟର୍’ ଭାବରେ ସାଇନ୍ ଅପ୍ କରିଛନ୍ତି, ଯାହାକି କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସରେ ଶାରୀରିକ ଭାବରେ ଉପସ୍ଥିତ ଥିବା କର୍ମଚାରୀ ଏବଂ କୁଲିଙ୍ଗ ଗ୍ରାହକମାନେ ସହିତ ସମ୍ପର୍କ ରଖିଥିବା କର୍ମଚାରୀ। ସମସ୍ତ ବ୍ୟବହାରକାରୀଙ୍କୁ ନୋଟ୍ କରାଯାଇଥିବା ସମୟରେ ‘ପୁରୁଷ’, ‘ସ୍ତ୍ରୀ’, କିମ୍ବା ‘ଅନ୍ୟ’ ଭାବରେ ଲିଙ୍ଗ ସୂଚନା ଦିଆଯିବାକୁ କହାଯାଇଛି। ‘ଏଗ୍ରିଗେଟ୍‌ଡ୍’ ଏବଂ ‘ତୁଲନା’ ଦୃଶ୍ୟରେ, କେବଳ ଚୟନ କରାଯାଇଥିବା କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସ ପାଇଁ ଏହି ସଂଖ୍ୟା ଗଣାଯାଇଛି।',
    },
    {
      title: 'ସ୍ୱତନ୍ତ୍ର କୁଲିଙ୍ଗ ବ୍ୟବହାରକାରୀଙ୍କର ମୋଟ ସଂଖ୍ୟା',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ସଂଯୋଗ କରିବା ପରେ କମ୍ପାନୀର ସମସ୍ତ କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସରେ କୁଲିଙ୍ଗ ଗ୍ରାହକମାନେର ସଂଖ୍ୟା। ସମସ୍ତ ବ୍ୟବହାରକାରୀଙ୍କୁ ନୋଟ୍ କରାଯାଇଥିବା ସମୟରେ ‘ପୁରୁଷ’, ‘ସ୍ତ୍ରୀ’, କିମ୍ବା ‘ଅନ୍ୟ’ ଭାବରେ ଲିଙ୍ଗ ସୂଚନା ଦିଆଯିବାକୁ କହାଯାଇଛି। ଏହି ସୂଚକ କେବଳ ‘କମ୍ପାନୀ’ ଦୃଶ୍ୟରେ ଉପସ୍ଥିତ ଅଛି। ‘ଏଗ୍ରିଗେଟ୍‌ଡ୍’ ଏବଂ ‘ତୁଲନା’ ଦୃଶ୍ୟରେ, ଆମେ ପ୍ରତିଟି କୁଲିଙ୍ଗ ଗ୍ରାହକର ସଂଖ୍ୟା ଦର୍ଶାଉଛୁ।',
    },
    {
      title: 'ସକ୍ରିୟ କୁଲିଙ୍ଗ ବ୍ୟବହାରକାରୀଙ୍କର ମୋଟ ସଂଖ୍ୟା',
      text: 'ଚୟନ କରାଯାଇଥିବା ଉତ୍ପାଦର ପ୍ରକାର ଅନୁସାରେ ଏବଂ ସମୟର ଅନୁସାରେ କୁଲିଙ୍ଗ ବ୍ୟବହାରକାରୀଙ୍କର ସଂଖ୍ୟା। ସମସ୍ତ ବ୍ୟବହାରକାରୀଙ୍କୁ ନୋଟ୍ କରାଯାଇଥିବା ସମୟରେ ‘ପୁରୁଷ’, ‘ସ୍ତ୍ରୀ’, କିମ୍ବା ‘ଅନ୍ୟ’ ଭାବରେ ଲିଙ୍ଗ ସୂଚନା ଦିଆଯିବାକୁ କହାଯାଇଛି। ‘କମ୍ପାନୀ’ ଦୃଶ୍ୟରେ, ଆମେ ସକ୍ରିୟ କୁଲିଙ୍ଗ ବ୍ୟବହାରକାରୀଙ୍କର ସଂଖ୍ୟା ଦର୍ଶାଉଛୁ।',
    },
    {
      title: 'କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସର ସମସ୍ତ ପ୍ରକାର',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ନୋଟ୍ କରାଯାଇଥିବା ମୋଟ କୁଲିଙ୍ଗ ଇୁନିଟ୍‌ସ ଏବଂ ସେମାନଙ୍କର ପ୍ରକାର।',
    },
    {
      title: 'କୋଲ୍ଡଟିଭେଟରେ ରିପୋର୍ଟର ସ୍ଥିତି',
      text: 'ଏକ ପ୍ରତିବେଦନ କିମ୍ବା ତ୍ୟାଗର ସ୍ଥିତି ଯାହାକି ଆପଣଙ୍କର କମ୍ପାନୀ ସହିତ ସଂଯୋଗ ରହିଥିବା କୋଲ୍ଡଟିଭେଟ ରେପୋର୍ଟର ସ୍ଥିତିକୁ ଦର୍ଶାଏ।',
    },
    {
      title: 'କୋଲ୍ଡଟିଭେଟରେ ଅଭିବ୍ୟକ୍ତ ପ୍ରଦାନ',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ଆପଣଙ୍କର କମ୍ପାନୀ ପାଇଁ ତିଆରି କରାଯାଇଥିବା ପ୍ରସ୍ତାବର ପ୍ରକାର ଏବଂ ସେହି ପ୍ରସ୍ତାବର ଆବଶ୍ୟକତା।',
    },
    {
      title: 'ମୋଟ ପ୍ରସ୍ତାବ ଆରମ୍ଭ',
      text: 'ଏହି ସୂଚକ ଆପଣଙ୍କର କମ୍ପାନୀ ପାଇଁ ଆପ୍ଲିକେସନ୍‌ରେ ରିପୋର୍ଟ ଆରମ୍ଭ କରାଯିବା ପ୍ରସ୍ତାବର ସଂଖ୍ୟା ଦର୍ଶାଏ।',
    },
    {
      title: 'ସହାୟତା ମେଟ୍ରିକ୍ସ',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ ସହାୟତା ମେଟ୍ରିକ୍ସ ପ୍ରଦାନ କରାଯାଇଛି।',
    },
    {
      title: 'କ୍ରେଟ୍ ପରିମାଣ',
      text: 'କୋଲ୍ଡଟିଭେଟରେ କ୍ରେଟ୍ ପରିମାଣ କିମ୍ବା ସହାୟତା ପ୍ରଦାନ କରାଯିବା କ୍ରେଟ୍ ସହିତ ସମ୍ପର୍କ ରହିଥିବା ଆଲୋଚନା କରାଯାଇଛି।',
    },
    {
      title: 'କମ୍ପାନୀ ତଥ୍ୟ',
      text: 'ଆପ୍ଲିକେସନ୍‌ରେ କମ୍ପାନୀ ପାଇଁ ନୋଟ୍ କରାଯାଇଥିବା ସାଧାରଣ ତଥ୍ୟ ଏବଂ ସେହି ତଥ୍ୟକୁ ତିଆରି କରାଯିବା ତାରିଖ।',
    },
  ],
  [APP_LOCALES.GUJARATI]: [
    {
      title: 'કંપનીનું નામ',
      text: 'કોલ્ડટિવેટમાં નોંધાયેલી કંપનીનું નામ.',
    },
    {
      title: 'કુલ આવક',
      text: 'કોલ્ડટિવેટ એપ્લિકેશનમાં ચેક-ઇન થયેલા ક્રેટ્સ માટે સંગ્રહ ફી વસૂલ કરીને કંપનીની કુલ આવક.',
    },
    {
      title: 'કુલ કૂલિંગ ક્ષમતા',
      text: 'એપ્લિકેશનમાં вашей કંપની માટે નોંધાયેલ તમામ કૂલિંગ યુનિટ્સની સંકલિત ક્ષમતા.',
    },
    {
      title: 'કૂલિંગ યુનિટ્સની સંખ્યા',
      text: 'એપ્લિકેશનમાં вашей કંપની માટે નોંધાયેલ કુલ કૂલિંગ યુનિટ્સ.',
    },
    {
      title: 'કૂલિંગ યુનિટનો પ્રકાર',
      text: 'ફાર્મ-ગેટ, બજાર પર આવેલી અથવા રેફ્રિજરેટેડ ટ્રક પર આવેલા કુલ કૂલિંગ યુનિટ્સની સંખ્યા. માહિતી નોંધાવનાર કર્મચારી દ્વારા આપેલ છે જે એપ્લિકેશનમાં કૂલિંગ યુનિટ બનાવે છે.',
    },
    {
      title: 'નોંધાયેલા કર્મચારીઓની કુલ સંખ્યા',
      text: 'તમારી કંપની સાથે જોડાયેલા વપરાશકર્તાઓની સંખ્યા જેમણે ‘નોંધાયેલ કર્મચારી’ તરીકે સાઇન અપ કર્યું છે, એટલે કે, મેનેજમેન્ટ ટીમના સભ્યો જે કૂલિંગ યુનિટ્સ પર ઓપરેશન્સને દેખરેખ કરે છે. બધા વપરાશકર્તાઓને નોંધણી સમયે ‘પુરુષ’, ‘સ્ત્રી’, અથવા ‘અન્ય’ તરીકે લિંગ જાહેર કરવાનું કહેવામાં આવે છે. આ સંકેત માત્ર ‘કંપની’ દૃશ્યમાં હાજર છે કારણ કે નોંધાયેલા કર્મચારીઓ એક જ કૂલિંગ યુનિટ સાથે નહીં પરંતુ સમગ્ર કંપની સાથે જોડાયેલા હોય છે.',
    },
    {
      title: 'ઓપરેટરોની કુલ સંખ્યા',
      text: 'તમારી કંપની સાથે જોડાયેલા વપરાશકર્તાઓની સંખ્યા જેમણે ‘ઓપરેટર’ તરીકે સાઇન અપ કર્યું છે, એટલે કે, કૂલિંગ યુનિટ્સ પર શારીરિક રીતે હાજર કર્મચારી અને કૂલિંગ ગ્રાહકો સાથે સંપર્કમાં રહેતા કર્મચારી. બધા વપરાશકર્તાઓને નોંધણી વખતે ‘પુરુષ’, ‘સ્ત્રી’, અથવા ‘અન્ય’ તરીકે લિંગ જાહેર કરવાનું કહેવામાં આવે છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, માત્ર પસંદ કરેલ કૂલિંગ યુનિટ્સ માટે ફાળવાયેલા ઓપરેટરોને જ ગણવામાં આવે છે.',
    },
    {
      title: 'અલગ કૂલિંગ વપરાશકર્તાઓની કુલ સંખ્યા',
      text: 'એપ્લિકેશનમાં જોડાવા પછી કંપનીની તમામ કૂલિંગ યુનિટ્સમાં કૂલિંગ ગ્રાહકોની સંખ્યા. બધા વપરાશકર્તાઓને નોંધણી સમયે ‘પુરુષ’, ‘સ્ત્રી’, અથવા ‘અન્ય’ તરીકે લિંગ જાહેર કરવાનું કહેવામાં આવે છે. આ સંકેત માત્ર ‘કંપની’ દૃશ્યમાં હાજર છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, અમે બદલે સક્રિય કૂલિંગ વપરાશકર્તાઓની સંખ્યા બતાવીએ છીએ.',
    },
    {
      title: 'સક્રિય કૂલિંગ વપરાશકર્તાઓની કુલ સંખ્યા',
      text: 'પસંદ કરેલ સમયગાળામાં ઓછામાં ઓછા એક કૂલિંગ યુનિટમાં ચેક-ઇન અથવા ચેક-આઉટ ઓપરેશન કરનારા અલગ વપરાશકર્તાઓની સંખ્યા. લિંગ વિભાજન કૂલિંગ વપરાશકર્તાઓના લિંગથી ગણવામાં આવે છે, જેમણે નોંધણી દરમિયાન જાહેર કર્યું હતું. આ સંકેત માત્ર ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં હાજર છે.',
    },
    {
      title: 'કૂલિંગ વપરાશકર્તાઓનો પ્રકાર',
      text: '‘કૂલિંગ વપરાશકર્તા સર્વેક્ષણ’ ભરતા કૂલિંગ વપરાશકર્તાઓને પુછવામાં આવે છે કે તેઓ પોતાની ઓળખ ‘કૃષક’ અથવા ‘અન્ય નાના વેપારીઓ / વાણિજ્યક / હોલસેલર્સ’ તરીકે કરે છે. આ સંકેત આ પ્રશ્નનો જવાબ આપનારા કૂલિંગ વપરાશકર્તાઓ માટેના તારણ બતાવે છે.',
    },
    {
      title: 'અડક લાભાર્થીઓની કુલ સંખ્યા',
      text: 'અડક લાભાર્થીઓની સંખ્યા કૂલિંગ વપરાશકર્તાઓની કુલ સંખ્યાને કંપની所在 દેશ માટેની સરેરાશ ઘરઘરની આકૃતિ સાથે ગુણાકાર કરીને ગણવામાં આવે છે. ‘કંપની’ દૃશ્યમાં, ‘વિશેષ ક્ષેત્ર કૂલિંગ વપરાશકર્તાઓની કુલ સંખ્યા’નો ઉપયોગ કરવામાં આવે છે, જ્યારે ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યોમાં, ‘સક્રિય કૂલિંગ વપરાશકર્તાઓની કુલ સંખ્યા’નો ઉપયોગ કરવામાં આવે છે. પુરુષ-સ્ત્રી વિભાજન કંપનીના દેશ માટેની સરેરાશ લિંગ રેશિયોનો ઉપયોગ કરીને ગણવામાં આવે છે. સરેરાશ ઘરઘરની આકૃતિ અને લિંગ રેશિયાની માહિતી https://population.un.org/Household/index.html#/countries/ પરથી ખેંચવામાં આવે છે.',
    },
    {
      title: 'ચેક-ઇન કૃષિ વિતરણ (ક્રેટ્સ)',
      text: 'કોલ્ડટિવેટ એપ્લિકેશન દ્વારા દરેક પ્રકારની ખાદ્ય પદાર્થ માટે ચેક-ઇન થયેલા ક્રેટ્સની સંખ્યા. ઉત્પાદનોની સૂચિ ચેક-ઇન થયેલ ક્રેટ્સની સંખ્યાના આધાર પર ક્રમબદ્ધ છે.',
    },
    {
      title: 'ચેક-આઉટ કૃષિ વિતરણ (ક્રેટ્સ)',
      text: 'કોલ્ડટિવેટ એપ્લિકેશન દ્વારા દરેક પ્રકારની ખાદ્ય પદાર્થ માટે ચેક-આઉટ થયેલા ક્રેટ્સની સંખ્યા. ઉત્પાદનોની સૂચિ ચેક-આઉટ થયેલ ક્રેટ્સની સંખ્યાના આધાર પર ક્રમબદ્ધ છે.',
    },
    {
      title: 'ચેક-ઇન કૃષિ વિતરણ (કિ.ગ્રા.)',
      text: 'કોલ્ડટિવેટ એપ્લિકેશન દ્વારા દરેક પ્રકારની ખાદ્ય પદાર્થ માટે ચેક-ઇન થયેલ કુલ માત્રા, કિલોગ્રામમાં. ઉત્પાદનોની સૂચિ ચેક-ઇન થયેલ ક્રેટ્સની સંખ્યાના આધાર પર ક્રમબદ્ધ છે.',
    },
    {
      title: 'ચેક-આઉટ કૃષિ વિતરણ (કિ.ગ્રા.)',
      text: 'કોલ્ડટિવેટ એપ્લિકેશન દ્વારા દરેક પ્રકારની ખાદ્ય પદાર્થ માટે ચેક-આઉટ થયેલ કુલ માત્રા, કિલોગ્રામમાં. ઉત્પાદનોની સૂચિ ચેક-આઉટ થયેલ ક્રેટ્સની સંખ્યાના આધાર પર ક્રમબદ્ધ છે.',
    },
    {
      title: 'કૂલિંગ યુનિટ્સની સરેરાશ_OCCUPANCY',
      text: 'દરેક યુનિટ માટે, દૈનિક સરેરાશ OCCUPANCY ગુણાકારથી ગણવામાં આવે છે, જેમાં યુનિટમાં સંગ્રહિત ક્રેટ્સની સંખ્યા અને યુનિટમાં સંગ્રહિત કરી શકાય તેવા ક્રેટ્સની કુલ સંખ્યા, જે નોંધાયેલ કર્મચારી દ્વારા આલેખિત છે, સરેરાશ લશ્કર છે. આ મૂલ્ય પછી સમગ્ર કંપની અને સમયગાળાની અવધિ માટે બધું મળીને સરેરાશ કરવામાં આવે છે. ‘કંપની’ દૃશ્યમાં, કોલ્ડટિવેટમાં કંપનીની રચનાની તારીખથી તમામ યુનિટ અને દિવસો માનવામાં આવે છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, યુનિટ અને સમયગાળા પર ક્લિક કરીને ‘કૉન્ફિગર’ કરવા માટે સેટ કરી શકાય છે.',
    },
    {
      title: 'કુલ ક્રેટ્સ',
      text: 'એપ્લિકેશન દ્વારા ચેક-ઇન અને ચેક-આઉટ થયેલ કુલ ક્રેટ્સની સંખ્યા. ‘કંપની’ દૃશ્યમાં, કોલ્ડટિવેટમાં કંપનીની રચનાની તારીખથી તમામ યુનિટ અને દિવસો માનવામાં આવે છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, યુનિટ અને સમયગાળા પર ક્લિક કરીને ‘કૉન્ફિગર’ કરવા માટે સેટ કરી શકાય છે.',
    },
    {
      title: 'કુલ માત્રા (કિ.ગ્રા.)',
      text: 'એપ્લિકેશન દ્વારા ચેક-ઇન અને ચેક-આઉટ થયેલ કુલ ઉત્પાદન કિલોગ્રામમાં. કિલોગ્રામ પ્રત્યેક ક્રેટની નોંધણી સમયે નિર્ધારિત છે. ‘કંપની’ દૃશ્યમાં, કોલ્ડટિવેટમાં કંપનીની રચનાની તારીખથી તમામ યુનિટ અને દિવસો માનવામાં આવે છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, યુનિટ અને સમયગાળા પર ક્લિક કરીને ‘કૉન્ફિગર’ કરવા માટે સેટ કરી શકાય છે.',
    },
    {
      title: 'કુલ ઓપરેશન્સ',
      text: 'એપ્લિકેશન દ્વારા નોંધાયેલ કુલ ચેક-ઇન અને ચેક-આઉટ ઓપરેશન્સની સંખ્યા. દરેક ઓપરેશનમાં વિવિધ ખાદ્ય પદાર્થોના અનેક ક્રેટ્સનો ચેક-ઇન અથવા ચેક-આઉટ સમાવેશ થઈ શકે છે. ‘કંપની’ દૃશ્યમાં, કોલ્ડટિવેટમાં કંપનીની રચનાની તારીખથી તમામ યુનિટ અને દિવસો માનવામાં આવે છે. ‘એગ્રેગેટેડ’ અને ‘તુલના’ દૃશ્યમાં, યુનિટ અને સમયગાળા પર ક્લિક કરીને ‘કૉન્ફિગર’ કરવા માટે સેટ કરી શકાય છે.',
    },
    {
      title: 'ખોરાક નષ્ટની વૃદ્ધિ',
      text: 'ખોરાક નષ્ટની વૃદ્ધિ એ દરેક વપરાશકર્તા અને પાક પ્રકાર માટે મહિને ખોરાકની સરેરાશ નષ્ટ/સેવ કરવામાં આવેલા રકમનો વર્ણન કરતી ટકાવારીમાં વ્યક્ત થાય છે. આ મૂલ્યને અંદાજવા માટે, દરેક વપરાશકર્તા અને પાક માટે આધારભૂત નષ્ટની માહિતી (જે સંદર્ભે ક્લાયંટ એફિલિયેટ દ્વારા પ્રાપ્ત કરવામાં આવે છે)ને ખરીદી પછીના નષ્ટની માહિતી સાથે તુલના કરવામાં આવે છે. આધારભૂત માહિતી ‘કૂલિંગ યુઝર સર્વે’માંથી એકત્ર કરવામાં આવે છે, જ્યાં ખેડૂતો અને વેપારીઓને પૂછવામાં આવે છે કે તેઓ મહિનામાં કેટલા ખોરાકનું ઉત્પાદન, વેચાણ અને નષ્ટ કરે છે (ઠંડા સ્ટોરેજ વિના) દરેક પાક માટે. ખેડૂત અને વેપારીઓએ કૂલિંગ યુનિટ્સનો ઉપયોગ કરતાં વખતે, ‘પોસ્ટ-ચેકઆઉટ’ સર્વેની સાતમાથી દરેક પ્રકારની પાક માટે સવાર થાય છે. આ સર્વેમાં, વપરાશકર્તાને ઠંડા સ્ટોરેજ પછી વેચાણ અને નષ્ટ કરવામાં આવેલી માત્રા વિશે પૂછવામાં આવે છે. પોસ્ટ-ચેકઆઉટ સર્વેમાંથી પ્રાપ્ત માહિતી માસિક રીતે જોડાય છે જેથી દરેક વપરાશકર્તા અને પાક પ્રકાર દ્વારા ઉપયોગ કરનાર ઠંડા સ્ટોરેજનો ઉપયોગ કરતી વખતે શું છે તે અંદાજવામાં આવે છે, અને આધારભૂત માહિતી સાથે તુલના કરવામાં આવે છે. વિવિધ પાકો અને દરેક કૂલિંગ યુનિટના વપરાશકર્તાઓ વચ્ચે મળેલી માહિતી સમયગાળાના અને કૂલિંગ યુનિટ્સના આધારે સરેરાશ કરવામાં આવે છે અને અસરકારક ડેશબોર્ડ પર દર્શાવાય છે. ખોરાકની ખોટની વૃદ્ધિ એ ‘પોસ્ટ-ચેકઆઉટ’ સર્વેમાં ખોટ (યાની ઠંડા સ્ટોરેજ દરમિયાન) અને આધારભૂત માહિતીમાં ખોટ (અથવા ઠંડા સ્ટોરેજ પહેલાં) વચ્ચેના ટકાવારીનો ફરક છે.',
    },
    {
      title: 'કૂલિંગ વપરાશકર્તા આવકની વૃદ્ધિ',
      text: 'કૂલિંગ વપરાશકર્તાઓ માટે આવકની વૃદ્ધિ એ કૃષક આવકમાં સરેરાશ ટકાવારીના બદલાવને વર્ણવે છે, જે તે આવકની તુલના કરીને ગણાય છે જે ઠંડા રૂમમાં સંગ્રહિત ઉત્પાદનોને વેચી અને ખેતરના પહેલાના (અથવા આધારભૂત માહિતી) પહેલા વેચી છે. આધારભૂત માહિતી ‘કૂલિંગ યુઝર સર્વે’માંથી એકત્ર કરવામાં આવે છે, જ્યાં ખેડૂત અને વેપારીઓને પૂછીને મળતી માહિતી કે કેટલી ખોરાકની માત્રા અને વેચાણ ભાવ છે જેમાં તેઓ દર અઠવાડિયે એપ્લિકેશન સાથે જોડાય છે, તે ખોટા સ્ટોરેજ પહેલાં છે. જેમને ખેડૂત અને વેપારીઓ કૂલિંગ યુનિટ્સનો ઉપયોગ કરે છે, ‘પોસ્ટ-ચેકઆઉટ’ સર્વેની સાતમાથી દરેક પ્રકારના પાક માટે સવાર થાય છે. આ સર્વેમાં, વપરાશકર્તાને ઠંડા સ્ટોરેજ પછી વેચાણ અને વેચાણ કિંમત વિશે પૂછવામાં આવે છે. પોસ્ટ-ચેકઆઉટ સર્વેમાંથી મળેલ માહિતી માસિક રીતે જોડાય છે જેથી દરેક વપરાશકર્તા અને પાક પ્રકાર દ્વારા ઉપનામના વપરાશકર્તા દ્વારા મેળવવામાં આવેલી કુલ માસિક આવકનો અંદાજ કરવામાં આવે છે, અને આ મૂલ્ય આધારભૂત માહિતી સાથે તુલના કરવામાં આવે છે. વિવિધ પાકો અને દરેક કૂલિંગ યુનિટના વપરાશકર્તાઓ વચ્ચે મળેલી માહિતી સમયગાળાના અને કૂલિંગ યુનિટ્સના આધારે સરેરાશ કરવામાં આવે છે અને અસરકારક ડેશબોર્ડ પર દર્શાવાય છે. આવકની વૃદ્ધિ એ ‘પોસ્ટ-ચેકઆઉટ’ સર્વેમાંથી અંદાજિત સરેરાશ આવક (યાની ઠંડા સ્ટોરેજ દરમિયાન) અને આધારભૂત માહિતી (અથવા ઠંડા સ્ટોરેજ પહેલાં)માંથી અંદાજિત સરેરાશ આવક વચ્ચેનો ટકાવારીનો ફરક છે.',
    },
    {
      title: 'ખોરાક નષ્ટ અને આવક વૃદ્ધિ ગણવામાં આવેલ સર્વેની સંખ્યા',
      text: 'ખોરાક નષ્ટ અને આવક વૃદ્ધિ પરના મેટ્રિક્સ તે સર્વે છે જે કૂલિંગ વપરાશકર્તાઓને પ્રવૃત્ત રીતે એપ્લિકેશન પર પ્રોત્સાહિત કરવામાં આવે છે. આ ટકાવારીઓની ગણતરી માટે સંકલિત કરવામાં આવેલી માહિતીની માત્રા વિશેની છબી મેળવવા માટે, અમે અહીં કૂલિંગ વપરાશકર્તાઓ દ્વારા પૂર્ણ કરવામાં આવેલી કુલ ‘પોસ્ટ-ચેકઆઉટ’ સર્વેની સંખ્યા ગણે છે, કંપનીની રચનાની તારીખથી હાલના મહિને સુધી, વર્તમાન મહિનામાં કંપની માટે પૂર્ણ થનારી મહત્તમ સંખ્યાની સરખામણી કરવામાં આવે છે. પૂર્ણ થનારી મહત્તમ સંખ્યા એ છે જે દરેક કૂલિંગ વપરાશકર્તા માટે નોટિસ કરેલા વિવિધ પાકોની કુલ સંખ્યાનો ઉપયોગ કરીને અંદાજવામાં આવે છે.',
    },
    {
      title: 'CO2 વૃદ્ધિ',
      text: 'અસલવેઇ મિશ્રિત CO2 પ્રવૃત્તિ ડેટા અને લાઇફ સાયકલ એસેસમેન્ટ (LCA) મોડલ્સમાંથી પ્રાપ્ત કરવામાં આવે છે જે Eco-Invent દ્વારા ઉપલબ્ધ છે. અમારી એપ્લિકેશનમાંથી લાઇવ ચેક-ઇન ડેટા સંકલિત કરીને, અમે દરરોજ કૂલિંગ રૂમમાં સંગ્રહિત વિવિધ પ્રકારની ઉત્પાદનોની માત્રા ટ્રેક કરીએ છીએ. આ સંબંધિત માહિતી, Eco-Invent ના વિસ્તૃત LCA ડેટાબેસમાંથી પ્રાપ્ત પુરક પરિમાણો સાથે જોડાય છે, કૂલિંગ રૂમમાં સંગ્રહિત દરેક પાક માટે દરરોજ CO2 ઉત્સર્જનને પુનઃગણવા માટે ઉપયોગ કરવામાં આવે છે. પરિણામની માહિતીને અસરકારક ડેશબોર્ડ દ્વારા એડમિન અને સસ્તી પ્રસ્તુતિ માટે તૈયાર કરવામાં આવે છે, જે અમારાં વપરાશકર્તાઓને પારદર્શક અને કાર્યક્ષમ પર્યાવરણ અસર માહિતી ઉપલબ્ધ કરે છે.',
    },
  ],
  [APP_LOCALES.FRENCH]: [
    {
      title: "Nom de l'entreprise",
      text: "Le nom de l'entreprise tel qu'il est enregistré dans Coldtivate.",
    },
    {
      title: 'Revenu total',
      text: "Le revenu total de l'entreprise généré par la collecte des frais de stockage pour les caisses qui ont été enregistrées dans l'application Coldtivate.",
    },
    {
      title: 'Capacité de refroidissement totale',
      text: "La capacité totale de toutes les unités de refroidissement enregistrées dans l'application pour votre entreprise.",
    },
    {
      title: "Nombre d'unités de refroidissement",
      text: "Le nombre total d'unités de refroidissement enregistrées dans l'application pour votre entreprise.",
    },
    {
      title: "Type d'unité de refroidissement",
      text: "Nombre total d'unités de refroidissement situées à la porte de la ferme, au marché ou dans des camions réfrigérés. Les informations sont insérées par l'employé enregistré qui crée l'unité de refroidissement dans l'application.",
    },
    {
      title: "Nombre total d'employés enregistrés",
      text: "Nombre d'utilisateurs liés à votre entreprise qui se sont inscrits en tant qu'‘Employé enregistré’, c'est-à-dire membres de l'équipe de gestion supervisant les opérations des unités de refroidissement. Tous les utilisateurs qui s'inscrivent sont invités à déclarer leur sexe comme ‘Homme’, ‘Femme’ ou ‘Autre’. Cet indicateur est uniquement présent dans la vue ‘Entreprise’ car les employés enregistrés ne sont pas liés à une seule unité de refroidissement, mais à l'ensemble de l'entreprise.",
    },
    {
      title: "Nombre total d'opérateurs",
      text: "Nombre d'utilisateurs liés à votre entreprise qui se sont inscrits en tant qu‘Opérateurs’, c'est-à-dire employés physiquement présents dans les unités de refroidissement et interagissant avec les clients de refroidissement. Tous les utilisateurs qui s'inscrivent sont invités à déclarer leur sexe comme ‘Homme’, ‘Femme’ ou ‘Autre’. Dans les vues ‘Agrégée’ et ‘Comparaison’, seuls les opérateurs affectés aux unités de refroidissement sélectionnées sont pris en compte.",
    },
    {
      title: "Nombre total d'utilisateurs distincts de refroidissement",
      text: "Nombre de clients de refroidissement à travers toutes les unités de refroidissement d'une entreprise depuis l'inscription dans l'application. Tous les utilisateurs qui s'inscrivent sont invités à déclarer leur sexe comme ‘Homme’, ‘Femme’ ou ‘Autre’. Cet indicateur est uniquement présent dans la vue ‘Entreprise’. Dans les vues ‘Agrégée’ et ‘Comparaison’, nous rapportons plutôt le nombre d'utilisateurs actifs de refroidissement.",
    },
    {
      title: "Nombre total d'utilisateurs actifs de refroidissement",
      text: "Nombre d'utilisateurs distincts qui ont effectué une opération de check-in ou check-out dans au moins une des unités de refroidissement pendant la période sélectionnée. La répartition par sexe est calculée à partir du sexe des utilisateurs de refroidissement, tel que déclaré lors de l'inscription. Cet indicateur est uniquement présent dans les vues ‘Agrégée’ et ‘Comparaison’.",
    },
    {
      title: "Type d'utilisateurs de refroidissement",
      text: "Les utilisateurs de refroidissement qui remplissent le ‘Questionnaire sur les utilisateurs de refroidissement’ sont invités à préciser s'ils se considèrent comme des ‘fermiers’ ou des ‘petits vendeurs / commerçants / grossistes’. Cet indicateur montre les statistiques résumées pour le sous-ensemble d'utilisateurs de refroidissement ayant répondu à cette question dans le questionnaire.",
    },
    {
      title: 'Nombre total de bénéficiaires indirects',
      text: "Le nombre de bénéficiaires indirects est calculé en multipliant le nombre total d'utilisateurs de refroidissement par la taille moyenne des foyers pour le pays où l'entreprise est située. Dans la vue ‘Entreprise’, le ‘Nombre total d'utilisateurs de refroidissement au district’ est utilisé, tandis que dans les vues ‘Agrégée’ et ‘Comparaison’, le ‘Nombre total d'utilisateurs actifs de refroidissement’ est utilisé. La répartition homme-femme est calculée en utilisant le ratio moyen des sexes pour le pays de l'entreprise. Les informations sur la taille moyenne des foyers et le ratio des sexes sont extraites de https://population.un.org/Household/index.html#/countries/.",
    },
    {
      title: "Répartition des cultures à l'enregistrement (caisses)",
      text: "Nombre de caisses qui ont été enregistrées via l'application Coldtivate pour chaque type de produit. La liste des produits est classée par nombre de caisses enregistrées.",
    },
    {
      title: 'Répartition des cultures au retrait (caisses)',
      text: "Nombre de caisses qui ont été retirées via l'application Coldtivate pour chaque type de produit. La liste des produits est classée par nombre de caisses retirées.",
    },
    {
      title: "Répartition des cultures à l'enregistrement (kg)",
      text: "Quantités totales, en kilogrammes, qui ont été enregistrées via l'application Coldtivate pour chaque type de produit. La liste des produits est classée par nombre de caisses enregistrées.",
    },
    {
      title: 'Répartition des cultures au retrait (kg)',
      text: "Quantités totales, en kilogrammes, qui ont été retirées via l'application Coldtivate pour chaque type de produit. La liste des produits est classée par nombre de caisses retirées.",
    },
    {
      title: 'Occupation moyenne des unités de refroidissement',
      text: "Pour chaque unité, l'occupation quotidienne moyenne est calculée comme le nombre de caisses stockées dans l'unité divisé par le nombre total de caisses pouvant être stockées dans l'unité, défini par l'employé enregistré qui crée l'unité de refroidissement dans l'application. Cette valeur est ensuite moyennée à travers toutes les unités pour l'entreprise et la période. Dans la vue ‘Entreprise’, toutes les unités et jours depuis la création de l'entreprise dans Coldtivate sont pris en compte. Dans les vues ‘Agrégée’ et ‘Comparaison’, les unités et la période peuvent être configurées en cliquant sur ‘Configurer’.",
    },
    {
      title: 'Total des caisses',
      text: "Nombre total de caisses qui ont été enregistrées et retirées via l'application. Dans la vue ‘Entreprise’, toutes les unités et jours depuis la création de l'entreprise dans Coldtivate sont pris en compte. Dans les vues ‘Agrégée’ et ‘Comparaison’, les unités et la période peuvent être configurées en cliquant sur ‘Configurer’.",
    },
    {
      title: 'Quantité totale (kg)',
      text: "Kilogrammes totaux de produits qui ont été enregistrés et retirés via l'application. Les kilogrammes par caisse sont définis au moment de l'enregistrement. Dans la vue ‘Entreprise’, toutes les unités et jours depuis la création de l'entreprise dans Coldtivate sont pris en compte. Dans les vues ‘Agrégée’ et ‘Comparaison’, les unités et la période peuvent être configurées en cliquant sur ‘Configurer’.",
    },
    {
      title: 'Total des opérations',
      text: "Nombre total d'opérations d'enregistrement et de retrait qui ont été enregistrées via l'application. Chaque opération peut inclure l'enregistrement ou le retrait de plusieurs caisses de différents produits. Dans la vue ‘Entreprise’, toutes les unités et jours depuis la création de l'entreprise dans Coldtivate sont pris en compte. Dans les vues ‘Agrégée’ et ‘Comparaison’, les unités et la période peuvent être configurées en cliquant sur ‘Configurer’.",
    },
    {
      title: 'Évolution des pertes alimentaires',
      text: "L'évolution des pertes alimentaires est exprimée en pourcentage pour décrire la quantité moyenne de nourriture perdue/économisée par mois pour chaque utilisateur et type de culture. Pour estimer cette valeur, les données de perte de base (c'est-à-dire les données collectées auprès des utilisateurs de refroidissement lors de leur inscription sur l'application) sont comparées aux données de perte après récolte collectées régulièrement à mesure que l'utilisateur stocke des cultures dans l'unité de refroidissement. Les données de base sont collectées via le ‘Questionnaire sur les utilisateurs de refroidissement’, où les agriculteurs et commerçants répondent à des questions sur la quantité de nourriture produite, vendue et perdue par semaine sans stockage au froid pour chaque culture. À mesure que les agriculteurs et commerçants utilisent les unités de refroidissement, des enquêtes ‘Post-retrait’ sont menées chaque semaine pour chaque type de culture que l'utilisateur a stockée dans la pièce. Dans ce questionnaire, l'utilisateur est interrogé sur les quantités vendues et perdues après stockage au froid. Les données des enquêtes post-retrait sont agrégées mensuellement pour estimer le niveau de perte après récolte que chaque utilisateur et type de culture subit en utilisant le stockage au froid, et comparées aux données de base. Les données à travers les cultures et les utilisateurs de chaque unité de refroidissement sont moyennées sur les périodes et unités de refroidissement pour donner les pourcentages affichés sur le Tableau de bord d'impact. L'évolution des pertes alimentaires est la différence en pourcentage entre le pourcentage perdu dans les enquêtes ‘post-retrait’ (c'est-à-dire lors de l'utilisation du refroidissement) et le pourcentage perdu dans les données de base (c'est-à-dire avant stockage au froid).",
    },
    {
      title: 'Évolution des revenus des utilisateurs de refroidissement',
      text: "L'évolution des revenus pour les utilisateurs de refroidissement décrit le changement moyen en pourcentage des revenus des agriculteurs calculé en comparant les revenus générés par la vente de produits stockés dans la chambre froide et par la vente de produits avant que l'agriculteur ne commence à utiliser le stockage au froid (‘données de base’). Les données de base sont collectées via le ‘Questionnaire sur les utilisateurs de refroidissement’, où les agriculteurs et commerçants sont interrogés sur la quantité et le prix de vente des cultures vendues par semaine lors de leur inscription sur l'application, c'est-à-dire avant de commencer à utiliser le stockage au froid. À mesure que les agriculteurs et commerçants utilisent les unités de refroidissement, des enquêtes ‘Post-retrait’ sont menées chaque semaine pour chaque type de culture que l'utilisateur a stockée dans la pièce. Dans ce questionnaire, l'utilisateur est interrogé sur les quantités vendues et le prix de vente après stockage au froid. Les données des enquêtes post-retrait sont agrégées mensuellement pour estimer les revenus mensuels totaux expérimentés par chaque utilisateur et type de culture pendant l'utilisation du stockage au froid, et cette valeur est comparée aux données de base. Les données à travers les cultures et les utilisateurs de chaque unité de refroidissement sont moyennées sur les périodes et unités de refroidissement pour donner les valeurs affichées sur le Tableau de bord d'impact. L'évolution des revenus est la différence en pourcentage entre le revenu moyen estimé à partir des enquêtes ‘post-retrait’ (c'est-à-dire lors de l'utilisation du refroidissement) et le revenu moyen estimé à partir des données de base (c'est-à-dire avant stockage au froid).",
    },
    {
      title:
        "Nombre d'enquêtes utilisées pour calculer l'évolution des pertes alimentaires et des revenus",
      text: "Les indicateurs sur l'évolution des pertes alimentaires et des revenus reposent sur les enquêtes que les utilisateurs de refroidissement sont invités à remplir lorsqu'ils sont actifs sur l'application. Pour avoir un aperçu de la quantité de données agrégées pour calculer ces pourcentages, nous comptons ici le nombre total d'enquêtes ‘Post-retrait’ remplies par les utilisateurs de refroidissement depuis la création de l'entreprise jusqu'au mois en cours, comparé au nombre maximal possible d'enquêtes pouvant être remplies pour l'entreprise au cours du mois actuel. Le nombre maximal d'enquêtes pouvant être remplies est estimé en utilisant le nombre total de cultures distinctes vérifiées pour chaque utilisateur de refroidissement depuis la création de l'entreprise.",
    },
    {
      title: 'Évolution du CO2',
      text: "Le Rapport quotidien des émissions de CO2 présenté sur le Tableau de bord d'impact est méticuleusement dérivé d'une combinaison d'analytique en temps réel du stockage en chambre froide et de modèles d'Évaluation du Cycle de Vie (ACV) robustes fournis par Eco-Invent. En intégrant les données d'enregistrement en temps réel de notre application, nous suivons systématiquement le volume de chaque type de produit stocké dans les chambres froides quotidiennement. Ces données pertinentes, couplées avec des paramètres auxiliaires provenant des bases de données ACV complètes d'Eco-Invent, sont utilisées pour recalculer avec précision les émissions quotidiennes de CO2 attribuables à chaque culture stockée. Les informations résultantes sont ensuite élégamment visualisées et mises à disposition pour exportation via le Tableau de bord d'impact, garantissant que nos utilisateurs disposent de données transparentes et exploitables sur l'impact environnemental à leur portée.",
    },
  ],
  [APP_LOCALES.PORTUGUESE]: [
    {
      title: 'Nome da empresa',
      text: 'O nome da empresa conforme registado na Coldtivate.',
    },
    {
      title: 'Receita total',
      text: 'A receita total da empresa gerada pela cobrança de taxas de armazenamento das caixas registadas na app Coldtivate.',
    },
    {
      title: 'Capacidade total de refrigeração',
      text: 'A capacidade total somada de todas as unidades de refrigeração registadas na aplicação para a sua empresa.',
    },
    {
      title: 'N.º de unidades de refrigeração',
      text: 'O número total de unidades de refrigeração registadas na aplicação para a sua empresa.',
    },
    {
      title: 'Tipo de unidade de refrigeração',
      text: 'Número total de unidades de refrigeração localizadas na exploração agrícola, no mercado ou em camiões frigoríficos. A informação é inserida pelo funcionário registado que cria a unidade de refrigeração na aplicação.',
    },
    {
      title: 'Número total de funcionários registados',
      text: "Número de utilizadores ligados à sua empresa que se inscreveram como 'Funcionário Registado', ou seja, membros da equipa de gestão que supervisionam as operações nas unidades de refrigeração. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Este indicador está presente apenas na vista 'Empresa' porque os funcionários registados não estão ligados a uma única unidade de refrigeração, mas sim a toda a empresa.",
    },
    {
      title: 'Número total de operadores',
      text: "Número de utilizadores ligados à sua empresa que se inscreveram como 'Operadores', ou seja, funcionários presentes fisicamente nas unidades de refrigeração e que interagem com os clientes de refrigeração. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Nas vistas 'Agregado' e 'Comparação', apenas os operadores atribuídos às unidades de refrigeração selecionadas são considerados.",
    },
    {
      title: 'Número total de utilizadores de refrigeração distintos',
      text: "Número de clientes de refrigeração em todas as unidades de refrigeração de uma empresa desde a adesão à aplicação. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Este indicador está presente apenas na vista 'Empresa'. Nas vistas 'Agregado' e 'Comparação', relatamos o número de utilizadores ativos de refrigeração.",
    },
    {
      title: 'Número total de utilizadores de refrigeração ativos',
      text: "Número de utilizadores distintos que realizaram uma operação de check-in ou check-out em pelo menos uma das unidades de refrigeração no período de tempo selecionado. A divisão por género é calculada a partir do género dos utilizadores de refrigeração, conforme declarado durante o registo. Este indicador está presente apenas nas vistas 'Agregado' e 'Comparação'.",
    },
    {
      title: 'Tipo de utilizadores de refrigeração',
      text: "Os utilizadores de refrigeração que preenchem o 'Inquérito ao Utilizador de Refrigeração' são convidados a especificar se se identificam como 'agricultores', ou como 'pequenos vendedores/comerciantes/grossistas'. Este indicador mostra as estatísticas resumidas para o subconjunto de utilizadores de refrigeração que responderam a esta pergunta no inquérito.",
    },
    {
      title: 'Número total de beneficiários indiretos',
      text: "O número de beneficiários indiretos é calculado multiplicando o número total de utilizadores de refrigeração pelo tamanho médio da família para o país onde a empresa está localizada. Na vista 'Empresa', é utilizado o 'Número total de utilizadores de refrigeração do distrito', enquanto nas vistas 'Agregado' e 'Comparação', é utilizado o 'Número total de utilizadores de refrigeração ativos'. A divisão por género masculino-feminino é calculada utilizando a média da razão de género para o país da empresa. A informação sobre o tamanho médio da família e a razão de género são extraídas de https://population.un.org/Household/index.html#/countries/.",
    },
    {
      title: 'Distribuição das colheitas no check-in (caixas)',
      text: 'Número de caixas registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-out (caixas)',
      text: 'Número de caixas registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-in (kg)',
      text: 'Quantidades totais, em quilogramas, registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-out (kg)',
      text: 'Quantidades totais, em quilogramas, registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Ocupação média das unidades de refrigeração',
      text: "Para cada unidade, a ocupação média diária é calculada como o número de caixas armazenadas na unidade dividido pelo número total de caixas que podem ser armazenadas na unidade, que é definido pelo funcionário registado que cria a unidade de refrigeração na aplicação. Este valor é então calculado para todas as unidades da empresa e para o período de tempo. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Caixas totais',
      text: "Número total de caixas registadas na aplicação. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Quantidade total (kg)',
      text: "Quantidade total, em quilogramas, de produtos registados na aplicação. Os quilogramas por caixa são definidos no momento do check-in. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Operações totais',
      text: "Número total de operações de check-in e check-out registadas na aplicação. Cada operação pode incluir o check-in ou check-out de várias caixas de diferentes produtos. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Evolução das perdas alimentares',
      text: "A evolução das perdas alimentares é expressa em percentagem para descrever a quantidade média de alimentos perdidos/salvos por mês para cada utilizador e tipo de produto. Para estimar este valor, os dados de perdas de base (ou seja, os dados recolhidos dos utilizadores de refrigeração quando se registam na aplicação) são comparados com os dados de perdas pós-colheita recolhidos regularmente à medida que o utilizador armazena produtos na unidade de refrigeração. Os dados de base são recolhidos através do 'Inquérito ao Utilizador de Refrigeração', onde os agricultores e comerciantes são questionados sobre a quantidade semanal de alimentos produzidos, vendidos e perdidos que experienciam (sem armazenamento a frio) para cada produto. À medida que os agricultores e comerciantes utilizam as unidades de refrigeração, são realizados inquéritos 'Pós-check-out' semanalmente para cada tipo de produto armazenado. Neste inquérito, o utilizador é questionado sobre as quantidades vendidas e perdidas após o armazenamento a frio. Os dados dos inquéritos pós-check-out são agregados mensalmente para estimar o nível de perda pós-colheita experienciado por cada utilizador e tipo de produto à medida que utilizam o armazenamento a frio, e comparados com a base. Os dados entre produtos e utilizadores de cada unidade de refrigeração são calculados ao longo de períodos de tempo e unidades de refrigeração para produzir as percentagens apresentadas no Impact Dashboard. A evolução das perdas alimentares é a diferença percentual entre a percentagem perdida nos inquéritos 'pós-check-out' (ou seja, enquanto utilizam a refrigeração) e a percentagem perdida na base (ou seja, antes do armazenamento a frio).",
    },
    {
      title: 'Evolução da receita dos utilizadores de refrigeração',
      text: "A evolução da receita para os utilizadores de refrigeração descreve a variação percentual média na receita do agricultor calculada comparando a receita gerada pela venda de produtos armazenados na câmara frigorífica e pela venda de produtos antes do agricultor começar a utilizar o armazenamento a frio (dados de 'base'). Os dados de base são recolhidos através do 'Inquérito ao Utilizador de Refrigeração', onde os agricultores e comerciantes são questionados sobre a quantidade e o preço de venda dos produtos vendidos por semana quando se inscrevem na aplicação, ou seja, antes de começarem a utilizar o armazenamento a frio. À medida que os agricultores e comerciantes utilizam as unidades de refrigeração, são realizados inquéritos 'Pós-check-out' semanalmente para cada tipo de produto armazenado. Neste inquérito, o utilizador é questionado sobre as quantidades vendidas e o preço de venda após o armazenamento a frio. Os dados dos inquéritos pós-check-out são agregados mensalmente para estimar qual é a receita mensal total experienciada por cada utilizador e tipo de produto à medida que utilizam o armazenamento a frio, e este valor é comparado com a base. Os dados entre produtos e utilizadores de cada unidade de refrigeração são calculados ao longo de períodos de tempo e unidades de refrigeração para produzir os valores apresentados no Impact Dashboard. A evolução da receita é a diferença percentual entre a receita média estimada a partir dos inquéritos 'pós-check-out' (ou seja, enquanto utilizam a refrigeração) e a receita média estimada a partir da base (ou seja, antes do armazenamento a frio).",
    },
    {
      title:
        'N.º de inquéritos utilizados para calcular a evolução das perdas alimentares e da receita',
      text: "As métricas sobre perdas alimentares e evolução da receita baseiam-se nos inquéritos que os utilizadores de refrigeração são convidados a preencher enquanto estão ativos na aplicação. Para ter uma ideia da quantidade de dados que está a ser agregada para calcular estas percentagens, aqui contamos o número total de inquéritos 'Pós-check-out' preenchidos pelos utilizadores de refrigeração desde a criação da empresa até ao mês atual, em comparação com o número máximo possível de inquéritos que poderiam ser preenchidos para a empresa no mês atual. O número máximo de inquéritos que poderiam ser preenchidos é estimado utilizando o número total de produtos distintos verificados para cada utilizador de refrigeração desde a criação da empresa.",
    },
    {
      title: 'Evolução do CO2',
      text: 'O Relatório Diário de Emissões de CO2 apresentado no Impact Dashboard é meticulosamente derivado de uma combinação de análises em tempo real do armazenamento da câmara frigorífica e de modelos robustos de Avaliação do Ciclo de Vida (LCA) fornecidos pela Eco-Invent. Ao integrar os dados de check-in ao vivo da nossa aplicação, monitorizamos sistematicamente o volume de cada tipo de produto armazenado nas câmaras frigoríficas diariamente. Estes dados relevantes, juntamente com parâmetros auxiliares extraídos das bases de dados LCA abrangentes da Eco-Invent, são utilizados para recalcular com precisão as emissões diárias de CO2 atribuíveis a cada produto armazenado. Os insights resultantes são então elegantemente visualizados e disponibilizados para exportação através do Impact Dashboard, garantindo que os nossos utilizadores têm à sua disposição dados transparentes e acionáveis sobre o impacto ambiental.',
    },
  ],
};
