import { APP_LOCALES, TranslationLocales } from '#i18n/constants';

type MethodologyEntry = {
  title: string;
  text: string;
};

export const METHODOLOGY_CONTENT: Record<TranslationLocales, MethodologyEntry[]> = {
  [APP_LOCALES.ENGLISH]: [
    {
      title: 'Company name',
      text: 'The name of the company as it is registered in Coldtivate.',
    },
    {
      title: 'Total revenue',
      text: "The company's total revenue generated by collecting storage fees for the crates that have been checked-in in the Coldtivate app.",
    },
    {
      title: 'Total cooling capacity',
      text: 'The summed capacity of all cooling units registered in the app for your company.',
    },
    {
      title: 'No. of cooling units',
      text: 'The total number of cooling units registered in the app for your company.',
    },
    {
      title: 'Cooling unit type',
      text: 'Total number of cooling units that are located at the farm-gate, at the market, or are refrigerated trucks. The information is inserted by the registered employee that creates the cooling unit in the app.',
    },
    {
      title: 'Total number of registered employees',
      text: 'Number of users linked to your company that signed up as ‘Registered Employee’, i.e. members of the management team that are overseeing operations at the cooling units. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. This indicator is only present in the ‘Company’ view because registered employees are not linked to a single cooling unit, but to the whole company.',
    },
    {
      title: 'Total number of operators',
      text: 'Number of users linked to your company that signed up as ‘Operators’, i.e. employees physically present at the cooling units and interacting with cooling customers. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. In the ‘Aggregated’ and ‘Comparison’ views, only the operators assigned to the selected cooling units are considered.',
    },
    {
      title: 'Total number of distinct cooling users',
      text: 'Number of cooling customers across all cooling units of a company since joining the app. All users that register are asked to declare their gender as ‘Male’, ‘Female’, or ‘Other’. This indicator is only present in the ‘Company’ view. In the ‘Aggregated’ and ‘Comparison’ views, we instead report on the number of active cooling users.',
    },
    {
      title: 'Total number of active cooling users',
      text: 'Number of distinct users that have done a check-in or check-out operation in at least one of the cooling units in the selected time period. The gender split is calculated from the gender of the cooling users, as declared during registration. This indicator is only present in the ‘Aggregated’ and ‘Comparison’ views.',
    },
    {
      title: 'Type of cooling users',
      text: 'Cooling users that fill in the ‘Cooling user survey’ are asked to specify whether they identify themselves as ‘farmers’, or as ‘small vendors / traders / wholesalers’. This indicator shows the summary statistics for the subset of cooling users that have answered this question in the survey.',
    },
    {
      title: 'Total number of indirect beneficiaries',
      text: 'The number of indirect beneficiaries is calculated by multiplying the total number of cooling users by the average household size for the country where the company is located. In the ‘Company’ view, the ‘Total number of district cooling users’ is used, whereas in the ‘Aggregated’ and ‘Comparison’ views, the ‘Total number of active cooling users’ is used. The male - female split is calculated using the average gender ratio for the country of the company. The information about the average household size and gender ratio are extracted from https://population.un.org/Household/index.html#/countries/.',
    },
    {
      title: 'Check-in crop distribution (crates)',
      text: 'Number of crates that have been checked-in via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-in crates.',
    },
    {
      title: 'Check-out crop distribution (crates)',
      text: 'Number of crates that have been checked-out via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-out crates.',
    },
    {
      title: 'Check-in crop distribution (kg)',
      text: 'Total quantities, in kilograms, that have been checked-in via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-in crates.',
    },
    {
      title: 'Check-out crop distribution (kg)',
      text: 'Total quantities, in kilograms, that have been checked-out via the Coldtivate app for each type of commodity. The list of commodities is ordered by the number of checked-out crates.',
    },
    {
      title: 'Average occupancy of cooling units',
      text: 'For each unit, the average daily occupancy is calculated as the number of crates stored in the unit divided by the total number of crates that can be stored in the unit, which is defined by the registered employee that creates the cooling unit in the app. This value is then averaged across all units for company and time period. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ views, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total crates',
      text: 'Total number of crates that have been checked-in and checked-out via the app. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total quantity (kg)',
      text: 'Total kilograms of produce that has been checked-in and checked-out via the app. The kilograms per crate are defined at time of check-in. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Total operations',
      text: 'Total number of check-in and check-out operations that have been recorded via the app. Each operation can include the check-in or check-out of multiple crates of different commodities. In the ‘Company’ view, all units and days since company creation in Coldtivate are considered. In the ‘Aggregated’ and ‘Comparison’ view, units and time period can be set up clicking on ‘Configure’.',
    },
    {
      title: 'Food loss evolution',
      text: `Food loss evolution is expressed as a percentage to describe the average amount of food lost/saved per month for each user and crop type. To estimate this value, for each user and crop, baseline loss data (namely data collected from cooling users when they register on the app) is compared to postharvest loss data collected regularly as the user stores crops in the cooling unit. Baseline data is collected from the ‘Cooling User Survey’, where farmers and traders are asked questions about the weekly amount of food produced, sold, and lost that they experience (without cold storage) for each crop. As the farmers and traders use the cooling units, ‘Post-checkout’ surveys are conducted weekly for each type of crop that a user has stored in the room. In this survey, the user is asked about quantities sold and lost after cold storage. Data from post-checkout surveys is aggregated monthly to estimate what is the postharvest loss level experienced by each user and crop type as they use cold storage, and compared to the baseline. Data across crops and users of each cooling unit are averaged over time periods and cooling units to yield the percentages displayed on the Impact Dashboard. The food loss evolution is the percentage difference between the percentage lost in the ‘post-checkout’ surveys (i.e. while utilising cooling) and the percentage lost in baseline (i.e. before cold storage).`,
    },
    {
      title: 'Cooling user revenue evolution',
      text: `The revenue evolution for cooling users describes the average percentage change in the farmer revenue calculated comparing the revenue generated by selling produce stored in the cold room and by selling produce before the farmer starts using cold storage (‘baseline’ data). Baseline data is collected from the ‘Cooling User Survey’, where farmers and traders are asked questions about the amount and selling price of crops sold per week when they join the app, i.e. before they start using cold storage. As the farmers and traders use the cooling units, ‘Post-checkout’ surveys are conducted weekly for each type of crop that a user has stored in the room. In this survey, the user is asked about quantities sold and selling price after cold storage. Data from post-checkout surveys is aggregated monthly to estimate what is the total monthly revenue experienced by each user and crop type as they use cold storage, and this value is compared to the baseline. Data across crops and users of each cooling unit are averaged over time periods and cooling units to yield the values displayed on the Impact Dashboard. The revenue evolution is the percentage difference between the average revenue estimated from the ‘post-checkout’ surveys (i.e. while utilising cooling) and the average revenue estimated from the baseline (i.e. before cold storage).`,
    },
    {
      title: 'No. of surveys used to calculate food loss and revenue evolution',
      text: `The metrics on food loss and revenue evolution rely on the surveys that cooling users are asked to fill in as they are active on the app. To get a glimpse on the amount of data that is being aggregated to calculate these percentages, we count here the total number of ‘Post-checkout’ surveys filled by cooling users since company creation up until the current month, compared with the maximum possible number of surveys that could be filled for the company in the current month. The maximum number of surveys that could be filled is estimated using the total number of distinct crops checked for each cooling user since company creation.`,
    },
    {
      title: 'CO2 evolution',
      text: `The CO2 Emissions Daily Report featured on the Impact Dashboard is meticulously derived from a combination of real-time cold room storage analytics and robust Life Cycle Assessment (LCA) models provided by Eco-Invent. By integrating live check-in data from our application, we systematically track the volume of each type of produce stored in the cold rooms on a daily basis. This pertinent data, coupled with auxiliary parameters sourced from Eco-Invent's comprehensive LCA databases, is utilized to accurately recalculate the daily CO2 emissions attributable to each stored crop. The resultant insights are then elegantly visualized and made available for export via the Impact Dashboard, ensuring that our users have transparent and actionable environmental impact data at their fingertips.`,
    },
  ],
  [APP_LOCALES.HINDI]: [
    {
      title: 'कंपनी का नाम',
      text: 'कंपनी का नाम जैसा कि Coldtivate में पंजीकृत है।',
    },
    {
      title: 'कुल राजस्व',
      text: 'कंपनी का कुल राजस्व जो Coldtivate ऐप में चेक-इन की गई पेटियों के लिए भंडारण शुल्क एकत्र करके उत्पन्न होता है।',
    },
    {
      title: 'कुल शीतलन क्षमता',
      text: 'ऐप में आपकी कंपनी के लिए पंजीकृत सभी शीतलन इकाइयों की कुल क्षमता।',
    },
    {
      title: 'शीतलन इकाइयों की संख्या',
      text: 'ऐप में आपकी कंपनी के लिए पंजीकृत शीतलन इकाइयों की कुल संख्या।',
    },
    {
      title: 'शीतलन इकाई प्रकार',
      text: 'शीतलन इकाइयों की कुल संख्या जो खेत के दरवाजे पर, बाजार में या रेफ्रिजेरेटेड ट्रकों में स्थित हैं। यह जानकारी पंजीकृत कर्मचारी द्वारा डाली जाती है जो ऐप में शीतलन इकाई बनाता है।',
    },
    {
      title: 'कुल पंजीकृत कर्मचारियों की संख्या',
      text: "आपकी कंपनी से जुड़े उपयोगकर्ताओं की संख्या जिन्होंने 'पंजीकृत कर्मचारी' के रूप में साइन अप किया है, अर्थात प्रबंधन टीम के सदस्य जो शीतलन इकाइयों पर संचालन की देखरेख कर रहे हैं। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। यह सूचकांक केवल 'कंपनी' दृश्य में मौजूद है क्योंकि पंजीकृत कर्मचारी किसी एक शीतलन इकाई से नहीं, बल्कि पूरी कंपनी से जुड़े होते हैं।",
    },
    {
      title: 'कुल ऑपरेटरों की संख्या',
      text: "आपकी कंपनी से जुड़े उपयोगकर्ताओं की संख्या जिन्होंने 'ऑपरेटर' के रूप में साइन अप किया है, अर्थात वे कर्मचारी जो शीतलन इकाइयों पर शारीरिक रूप से उपस्थित होते हैं और शीतलन ग्राहकों के साथ बातचीत करते हैं। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। 'एकीकृत' और 'तुलना' दृश्य में, केवल चयनित शीतलन इकाइयों को सौंपे गए ऑपरेटरों को ही माना जाता है।",
    },
    {
      title: 'कुल विशिष्ट शीतलन उपयोगकर्ताओं की संख्या',
      text: "ऐप में शामिल होने के बाद कंपनी की सभी शीतलन इकाइयों में कुल शीतलन ग्राहकों की संख्या। सभी पंजीकृत उपयोगकर्ताओं से उनके लिंग को 'पुरुष', 'महिला' या 'अन्य' के रूप में घोषित करने के लिए कहा जाता है। यह सूचकांक केवल 'कंपनी' दृश्य में मौजूद है। 'एकीकृत' और 'तुलना' दृश्य में, हम सक्रिय शीतलन उपयोगकर्ताओं की संख्या की रिपोर्ट करते हैं।",
    },
    {
      title: 'कुल सक्रिय शीतलन उपयोगकर्ताओं की संख्या',
      text: "चयनित समय अवधि में कम से कम एक शीतलन इकाई में चेक-इन या चेक-आउट संचालन करने वाले विशिष्ट उपयोगकर्ताओं की संख्या। लिंग विभाजन पंजीकरण के समय घोषित शीतलन उपयोगकर्ताओं के लिंग से गणना की जाती है। यह सूचकांक केवल 'एकीकृत' और 'तुलना' दृश्य में मौजूद है।",
    },
    {
      title: 'शीतलन उपयोगकर्ताओं का प्रकार',
      text: "शीतलन उपयोगकर्ता जो 'शीतलन उपयोगकर्ता सर्वेक्षण' भरते हैं उनसे पूछा जाता है कि वे अपने आप को 'किसान' या 'छोटे विक्रेता / व्यापारी / थोक व्यापारी' के रूप में पहचानते हैं या नहीं। यह सूचकांक उन शीतलन उपयोगकर्ताओं के लिए संक्षिप्त सांख्यिकी दर्शाता है जिन्होंने इस प्रश्न का सर्वेक्षण में उत्तर दिया है।",
    },
    {
      title: 'कुल अप्रत्यक्ष लाभार्थियों की संख्या',
      text: "अप्रत्यक्ष लाभार्थियों की संख्या की गणना कुल शीतलन उपयोगकर्ताओं की संख्या को उस देश के औसत परिवार आकार से गुणा करके की जाती है जहां कंपनी स्थित है। 'कंपनी' दृश्य में, 'कुल विशिष्ट शीतलन उपयोगकर्ताओं' का उपयोग किया जाता है, जबकि 'एकीकृत' और 'तुलना' दृश्य में, 'कुल सक्रिय शीतलन उपयोगकर्ताओं' का उपयोग किया जाता है। पुरुष - महिला विभाजन कंपनी के देश के औसत लिंग अनुपात का उपयोग करके गणना की जाती है। औसत परिवार आकार और लिंग अनुपात की जानकारी https://population.un.org/Household/index.html#/countries/ से प्राप्त की जाती है।",
    },
    {
      title: 'चेक-इन फसल वितरण (पेटियाँ)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-इन की गई पेटियों की संख्या। वस्तुओं की सूची चेक-इन की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-आउट फसल वितरण (पेटियाँ)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-आउट की गई पेटियों की संख्या। वस्तुओं की सूची चेक-आउट की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-इन फसल वितरण (किलोग्राम)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-इन की गई कुल मात्रा, किलोग्राम में। वस्तुओं की सूची चेक-इन की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'चेक-आउट फसल वितरण (किलोग्राम)',
      text: 'प्रत्येक प्रकार की वस्तु के लिए Coldtivate ऐप के माध्यम से चेक-आउट की गई कुल मात्रा, किलोग्राम में। वस्तुओं की सूची चेक-आउट की गई पेटियों की संख्या के अनुसार क्रमबद्ध होती है।',
    },
    {
      title: 'शीतलन इकाइयों का औसत अधिभोग',
      text: "प्रत्येक इकाई के लिए, औसत दैनिक अधिभोग की गणना इकाई में संग्रहीत पेटियों की संख्या को इकाई में संग्रहीत की जा सकने वाली कुल पेटियों की संख्या से विभाजित करके की जाती है, जो ऐप में शीतलन इकाई बनाने वाले पंजीकृत कर्मचारी द्वारा परिभाषित होती है। यह मान तब सभी इकाइयों और समय अवधि के लिए कंपनी के लिए औसत निकाला जाता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल पेटियाँ',
      text: "ऐप के माध्यम से चेक-इन और चेक-आउट की गई कुल पेटियों की संख्या। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल मात्रा (किलोग्राम)',
      text: "ऐप के माध्यम से चेक-इन और चेक-आउट की गई कुल उपज के किलोग्राम। चेक-इन के समय पेटी के किलोग्राम को परिभाषित किया जाता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'कुल संचालन',
      text: "ऐप के माध्यम से दर्ज किए गए कुल चेक-इन और चेक-आउट संचालन। प्रत्येक संचालन में विभिन्न वस्तुओं की कई पेटियों का चेक-इन या चेक-आउट शामिल हो सकता है। 'कंपनी' दृश्य में, Coldtivate में कंपनी निर्माण के बाद से सभी इकाइयों और दिनों पर विचार किया जाता है। 'एकीकृत' और 'तुलना' दृश्य में, इकाइयों और समय अवधि को 'कॉन्फ़िगर' पर क्लिक करके सेट किया जा सकता है।",
    },
    {
      title: 'खाद्य हानि विकास',
      text: `खाद्य हानि विकास शीतलन उपयोगकर्ताओं द्वारा शीतलन इकाइयों का उपयोग करने से पहले की तुलना में शीतलन इकाइयों का उपयोग करने के बाद खोई गई फसल की औसत मात्रा का प्रतिशत परिवर्तन दर्शाता है। इसे समय अवधि, शीतलन इकाइयों के सेट, उपयोगकर्ता और फसल प्रकार के लिए प्रति माह खोए/बचाए गए खाद्य की औसत मात्रा को वर्णित किया जा सके। इस मान का अनुमान लगाने के लिए, प्रत्येक उपयोगकर्ता और फसल के लिए, बेसलाइन हानि डेटा (अर्थात् ऐप पर पंजीकरण के समय शीतलन उपयोगकर्ताओं से एकत्रित डेटा) की तुलना नियमित रूप से संग्रहीत फसलों के बाद की हानि डेटा से की जाती है। बेसलाइन डेटा 'शीतलन उपयोगकर्ता सर्वेक्षण' से एकत्रित किया जाता है, जहां किसानों और व्यापारियों से प्रत्येक फसल के लिए उत्पादित, बेची और खोई गई साप्ताहिक मात्रा के बारे में प्रश्न पूछे जाते हैं (बिना ठंडे भंडारण के)। जब किसान और व्यापारी शीतलन इकाइयों का उपयोग करते हैं, तो 'पोस्ट-चेकआउट' सर्वेक्षण प्रत्येक प्रकार की फसल के लिए साप्ताहिक रूप से किया जाता है जिसे उपयोगकर्ता ने कक्ष में संग्रहीत किया है। इस सर्वेक्षण में, उपयोगकर्ता से ठंडे भंडारण के बाद बेची और खोई गई मात्राओं के बारे में पूछा जाता है। पोस्ट-चेकआउट सर्वेक्षणों से डेटा को मासिक रूप से संकलित किया जाता है ताकि यह अनुमान लगाया जा सके कि ठंडे भंडारण का उपयोग करने के दौरान प्रत्येक उपयोगकर्ता और फसल प्रकार द्वारा क्या पोस्टहार्वेस्ट हानि स्तर का अनुभव किया गया है, और इसे बेसलाइन के साथ तुलना की जाती है। प्रत्येक समय अवधि और शीतलन इकाइयों के लिए फसलों और उपयोगकर्ताओं में डेटा का औसत निकालकर प्रभाव डैशबोर्ड पर प्रदर्शित प्रतिशत प्राप्त होते हैं। खाद्य हानि विकास वह प्रतिशत अंतर है जो 'पोस्ट-चेकआउट' सर्वेक्षणों (अर्थात् शीतलन का उपयोग करते समय) में खोए गए प्रतिशत और बेसलाइन (अर्थात् ठंडे भंडारण से पहले) में खोए गए प्रतिशत के बीच है।`,
    },
    {
      title: 'शीतलन उपयोगकर्ता राजस्व विकास',
      text: `शीतलन उपयोगकर्ताओं के लिए राजस्व विकास किसान राजस्व में औसत प्रतिशत परिवर्तन का वर्णन करता है जो ठंडे कमरे में संग्रहीत उत्पाद को बेचने से उत्पन्न राजस्व की तुलना में किया जाता है और किसान ठंडे भंडारण का उपयोग करने से पहले उत्पाद बेचने से उत्पन्न राजस्व ('बेसलाइन' डेटा) का तुलना करता है। बेसलाइन डेटा 'शीतलन उपयोगकर्ता सर्वेक्षण' से एकत्रित किया जाता है, जहां किसानों और व्यापारियों से ऐप में शामिल होने के समय प्रति सप्ताह बेचे जाने वाली फसलों की मात्रा और बिक्री मूल्य के बारे में प्रश्न पूछे जाते हैं, अर्थात् ठंडे भंडारण का उपयोग शुरू करने से पहले। जब किसान और व्यापारी शीतलन इकाइयों का उपयोग करते हैं, तो 'पोस्ट-चेकआउट' सर्वेक्षण प्रत्येक प्रकार की फसल के लिए साप्ताहिक रूप से किया जाता है जिसे उपयोगकर्ता ने कक्ष में संग्रहीत किया है। इस सर्वेक्षण में, उपयोगकर्ता से ठंडे भंडारण के बाद बेची गई मात्राओं और बिक्री मूल्य के बारे में पूछा जाता है। पोस्ट-चेकआउट सर्वेक्षणों से डेटा को मासिक रूप से संकलित किया जाता है ताकि यह अनुमान लगाया जा सके कि ठंडे भंडारण का उपयोग करने के दौरान प्रत्येक उपयोगकर्ता और फसल प्रकार द्वारा क्या मासिक राजस्व का अनुभव किया गया है, और इस मान को बेसलाइन के साथ तुलना की जाती है। प्रत्येक समय अवधि और शीतलन इकाइयों के लिए फसलों और उपयोगकर्ताओं में डेटा का औसत निकालकर प्रभाव डैशबोर्ड पर प्रदर्शित मान प्राप्त होते हैं। राजस्व विकास वह प्रतिशत अंतर है जो 'पोस्ट-चेकआउट' सर्वेक्षणों (अर्थात् शीतलन का उपयोग करते समय) से अनुमानित औसत राजस्व और बेसलाइन (अर्थात् ठंडे भंडारण से पहले) से अनुमानित औसत राजस्व के बीच है।`,
    },
    {
      title: 'खाद्य हानि और राजस्व विकास की गणना के लिए उपयोग किए गए सर्वेक्षणों की संख्या',
      text: `खाद्य हानि और राजस्व विकास पर मेट्रिक्स उन सर्वेक्षणों पर निर्भर करती हैं जिन्हें शीतलन उपयोगकर्ताओं से भरा जाता है क्योंकि वे ऐप पर सक्रिय होते हैं। इन प्रतिशतों की गणना के लिए संकलित किए जा रहे डेटा की झलक पाने के लिए, हम यहां कंपनी निर्माण के बाद से वर्तमान माह तक शीतलन उपयोगकर्ताओं द्वारा भरे गए कुल 'पोस्ट-चेकआउट' सर्वेक्षणों की गणना करते हैं, जिसे वर्तमान माह में कंपनी के लिए भरे जा सकने वाले अधिकतम संभावित सर्वेक्षणों की तुलना में दर्शाते हैं। अधिकतम संभावित सर्वेक्षणों की संख्या का अनुमान प्रत्येक शीतलन उपयोगकर्ता के लिए कंपनी निर्माण के बाद से जांचे गए विशिष्ट फसलों की कुल संख्या का उपयोग करके किया जाता है।`,
    },
    {
      title: 'CO2 विकास',
      text: `प्रभाव डैशबोर्ड पर प्रदर्शित CO2 उत्सर्जन दैनिक रिपोर्ट वास्तविक समय के ठंडे कक्ष भंडारण विश्लेषण और Eco-Invent द्वारा प्रदान किए गए मजबूत जीवन चक्र मूल्यांकन (LCA) मॉडलों के संयोजन से सावधानीपूर्वक व्युत्पन्न की जाती है। हमारे एप्लिकेशन से लाइव चेक-इन डेटा को एकीकृत करके, हम प्रतिदिन ठंडे कमरों में संग्रहीत प्रत्येक प्रकार की उपज की मात्रा को व्यवस्थित रूप से ट्रैक करते हैं। यह प्रासंगिक डेटा, Eco-Invent के व्यापक LCA डेटाबेस से प्राप्त सहायक मापदंडों के साथ मिलकर, प्रतिदिन संग्रहीत प्रत्येक फसल के लिए जिम्मेदार CO2 उत्सर्जन की सटीक पुन: गणना के लिए उपयोग किया जाता है। परिणामी अंतर्दृष्टि को प्रभाव डैशबोर्ड के माध्यम से निर्यात के लिए उपलब्ध कराया जाता है, जिससे हमारे उपयोगकर्ताओं के पास पारदर्शी और क्रियाशील पर्यावरणीय प्रभाव डेटा उनकी उंगलियों पर होता है।`,
    },
  ],
  [APP_LOCALES.ORIYA]: [],
  [APP_LOCALES.GUJARATI]: [],
  [APP_LOCALES.FRENCH]: [],
  [APP_LOCALES.PORTUGUESE]: [
    {
      title: 'Nome da empresa',
      text: 'O nome da empresa conforme registado na Coldtivate.',
    },
    {
      title: 'Receita total',
      text: 'A receita total da empresa gerada pela cobrança de taxas de armazenamento das caixas registadas na app Coldtivate.',
    },
    {
      title: 'Capacidade total de refrigeração',
      text: 'A capacidade total somada de todas as unidades de refrigeração registadas na aplicação para a sua empresa.',
    },
    {
      title: 'N.º de unidades de refrigeração',
      text: 'O número total de unidades de refrigeração registadas na aplicação para a sua empresa.',
    },
    {
      title: 'Tipo de unidade de refrigeração',
      text: 'Número total de unidades de refrigeração localizadas na exploração agrícola, no mercado ou em camiões frigoríficos. A informação é inserida pelo funcionário registado que cria a unidade de refrigeração na aplicação.',
    },
    {
      title: 'Número total de funcionários registados',
      text: "Número de utilizadores ligados à sua empresa que se inscreveram como 'Funcionário Registado', ou seja, membros da equipa de gestão que supervisionam as operações nas unidades de refrigeração. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Este indicador está presente apenas na vista 'Empresa' porque os funcionários registados não estão ligados a uma única unidade de refrigeração, mas sim a toda a empresa.",
    },
    {
      title: 'Número total de operadores',
      text: "Número de utilizadores ligados à sua empresa que se inscreveram como 'Operadores', ou seja, funcionários presentes fisicamente nas unidades de refrigeração e que interagem com os clientes de refrigeração. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Nas vistas 'Agregado' e 'Comparação', apenas os operadores atribuídos às unidades de refrigeração selecionadas são considerados.",
    },
    {
      title: 'Número total de utilizadores de refrigeração distintos',
      text: "Número de clientes de refrigeração em todas as unidades de refrigeração de uma empresa desde a adesão à aplicação. Todos os utilizadores que se registam são convidados a declarar o seu género como 'Masculino', 'Feminino' ou 'Outro'. Este indicador está presente apenas na vista 'Empresa'. Nas vistas 'Agregado' e 'Comparação', relatamos o número de utilizadores ativos de refrigeração.",
    },
    {
      title: 'Número total de utilizadores de refrigeração ativos',
      text: "Número de utilizadores distintos que realizaram uma operação de check-in ou check-out em pelo menos uma das unidades de refrigeração no período de tempo selecionado. A divisão por género é calculada a partir do género dos utilizadores de refrigeração, conforme declarado durante o registo. Este indicador está presente apenas nas vistas 'Agregado' e 'Comparação'.",
    },
    {
      title: 'Tipo de utilizadores de refrigeração',
      text: "Os utilizadores de refrigeração que preenchem o 'Inquérito ao Utilizador de Refrigeração' são convidados a especificar se se identificam como 'agricultores', ou como 'pequenos vendedores/comerciantes/grossistas'. Este indicador mostra as estatísticas resumidas para o subconjunto de utilizadores de refrigeração que responderam a esta pergunta no inquérito.",
    },
    {
      title: 'Número total de beneficiários indiretos',
      text: "O número de beneficiários indiretos é calculado multiplicando o número total de utilizadores de refrigeração pelo tamanho médio da família para o país onde a empresa está localizada. Na vista 'Empresa', é utilizado o 'Número total de utilizadores de refrigeração do distrito', enquanto nas vistas 'Agregado' e 'Comparação', é utilizado o 'Número total de utilizadores de refrigeração ativos'. A divisão por género masculino-feminino é calculada utilizando a média da razão de género para o país da empresa. A informação sobre o tamanho médio da família e a razão de género são extraídas de https://population.un.org/Household/index.html#/countries/.",
    },
    {
      title: 'Distribuição das colheitas no check-in (caixas)',
      text: 'Número de caixas registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-out (caixas)',
      text: 'Número de caixas registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-in (kg)',
      text: 'Quantidades totais, em quilogramas, registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Distribuição das colheitas no check-out (kg)',
      text: 'Quantidades totais, em quilogramas, registadas na aplicação Coldtivate para cada tipo de produto. A lista de produtos é ordenada pelo número de caixas registadas.',
    },
    {
      title: 'Ocupação média das unidades de refrigeração',
      text: "Para cada unidade, a ocupação média diária é calculada como o número de caixas armazenadas na unidade dividido pelo número total de caixas que podem ser armazenadas na unidade, que é definido pelo funcionário registado que cria a unidade de refrigeração na aplicação. Este valor é então calculado para todas as unidades da empresa e para o período de tempo. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Caixas totais',
      text: "Número total de caixas registadas na aplicação. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Quantidade total (kg)',
      text: "Quantidade total, em quilogramas, de produtos registados na aplicação. Os quilogramas por caixa são definidos no momento do check-in. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Operações totais',
      text: "Número total de operações de check-in e check-out registadas na aplicação. Cada operação pode incluir o check-in ou check-out de várias caixas de diferentes produtos. Na vista 'Empresa', são consideradas todas as unidades e dias desde a criação da empresa na Coldtivate. Nas vistas 'Agregado' e 'Comparação', as unidades e o período de tempo podem ser configurados clicando em 'Configurar'.",
    },
    {
      title: 'Evolução das perdas alimentares',
      text: "A evolução das perdas alimentares é expressa em percentagem para descrever a quantidade média de alimentos perdidos/salvos por mês para cada utilizador e tipo de produto. Para estimar este valor, os dados de perdas de base (ou seja, os dados recolhidos dos utilizadores de refrigeração quando se registam na aplicação) são comparados com os dados de perdas pós-colheita recolhidos regularmente à medida que o utilizador armazena produtos na unidade de refrigeração. Os dados de base são recolhidos através do 'Inquérito ao Utilizador de Refrigeração', onde os agricultores e comerciantes são questionados sobre a quantidade semanal de alimentos produzidos, vendidos e perdidos que experienciam (sem armazenamento a frio) para cada produto. À medida que os agricultores e comerciantes utilizam as unidades de refrigeração, são realizados inquéritos 'Pós-check-out' semanalmente para cada tipo de produto armazenado. Neste inquérito, o utilizador é questionado sobre as quantidades vendidas e perdidas após o armazenamento a frio. Os dados dos inquéritos pós-check-out são agregados mensalmente para estimar o nível de perda pós-colheita experienciado por cada utilizador e tipo de produto à medida que utilizam o armazenamento a frio, e comparados com a base. Os dados entre produtos e utilizadores de cada unidade de refrigeração são calculados ao longo de períodos de tempo e unidades de refrigeração para produzir as percentagens apresentadas no Impact Dashboard. A evolução das perdas alimentares é a diferença percentual entre a percentagem perdida nos inquéritos 'pós-check-out' (ou seja, enquanto utilizam a refrigeração) e a percentagem perdida na base (ou seja, antes do armazenamento a frio).",
    },
    {
      title: 'Evolução da receita dos utilizadores de refrigeração',
      text: "A evolução da receita para os utilizadores de refrigeração descreve a variação percentual média na receita do agricultor calculada comparando a receita gerada pela venda de produtos armazenados na câmara frigorífica e pela venda de produtos antes do agricultor começar a utilizar o armazenamento a frio (dados de 'base'). Os dados de base são recolhidos através do 'Inquérito ao Utilizador de Refrigeração', onde os agricultores e comerciantes são questionados sobre a quantidade e o preço de venda dos produtos vendidos por semana quando se inscrevem na aplicação, ou seja, antes de começarem a utilizar o armazenamento a frio. À medida que os agricultores e comerciantes utilizam as unidades de refrigeração, são realizados inquéritos 'Pós-check-out' semanalmente para cada tipo de produto armazenado. Neste inquérito, o utilizador é questionado sobre as quantidades vendidas e o preço de venda após o armazenamento a frio. Os dados dos inquéritos pós-check-out são agregados mensalmente para estimar qual é a receita mensal total experienciada por cada utilizador e tipo de produto à medida que utilizam o armazenamento a frio, e este valor é comparado com a base. Os dados entre produtos e utilizadores de cada unidade de refrigeração são calculados ao longo de períodos de tempo e unidades de refrigeração para produzir os valores apresentados no Impact Dashboard. A evolução da receita é a diferença percentual entre a receita média estimada a partir dos inquéritos 'pós-check-out' (ou seja, enquanto utilizam a refrigeração) e a receita média estimada a partir da base (ou seja, antes do armazenamento a frio).",
    },
    {
      title:
        'N.º de inquéritos utilizados para calcular a evolução das perdas alimentares e da receita',
      text: "As métricas sobre perdas alimentares e evolução da receita baseiam-se nos inquéritos que os utilizadores de refrigeração são convidados a preencher enquanto estão ativos na aplicação. Para ter uma ideia da quantidade de dados que está a ser agregada para calcular estas percentagens, aqui contamos o número total de inquéritos 'Pós-check-out' preenchidos pelos utilizadores de refrigeração desde a criação da empresa até ao mês atual, em comparação com o número máximo possível de inquéritos que poderiam ser preenchidos para a empresa no mês atual. O número máximo de inquéritos que poderiam ser preenchidos é estimado utilizando o número total de produtos distintos verificados para cada utilizador de refrigeração desde a criação da empresa.",
    },
    {
      title: 'Evolução do CO2',
      text: 'O Relatório Diário de Emissões de CO2 apresentado no Impact Dashboard é meticulosamente derivado de uma combinação de análises em tempo real do armazenamento da câmara frigorífica e de modelos robustos de Avaliação do Ciclo de Vida (LCA) fornecidos pela Eco-Invent. Ao integrar os dados de check-in ao vivo da nossa aplicação, monitorizamos sistematicamente o volume de cada tipo de produto armazenado nas câmaras frigoríficas diariamente. Estes dados relevantes, juntamente com parâmetros auxiliares extraídos das bases de dados LCA abrangentes da Eco-Invent, são utilizados para recalcular com precisão as emissões diárias de CO2 atribuíveis a cada produto armazenado. Os insights resultantes são então elegantemente visualizados e disponibilizados para exportação através do Impact Dashboard, garantindo que os nossos utilizadores têm à sua disposição dados transparentes e acionáveis sobre o impacto ambiental.',
    },
  ],
};
