export enum ETutorialSteps {
  INITIAL_STEP = 1,
  OPEN_DRAWER_STEP = 2,
  REPEAT_TUTORIAL_STEP = 3,
  GO_TO_MANAGEMENT_STEP = 4,
  GO_TO_COOLING_USERS_STEP = 5,
  LIST_COOLING_USERS_STEP = 6,
  ADD_COOLING_USER_NAVIGATION_STEP = 7,
  COOLING_USER_MODAL = 8,
}
