import { GetMovementsHistoryResponse } from '#types/api.responses';
import { EInitiatedFor, EPaymentGateway, EPaymentMethod, EPaymentThrough } from '#types/global';

export const MOCKED_USER = {
  birthday: null,
  companies: [35],
  coolingUnits: [65, 64],
  country: 'Portugal',
  id: 163,
  parentName: '',
  user: {
    email: null,
    firstName: 'Test',
    gender: 'ma',
    id: 242,
    language: null,
    lastLogin: '2024-09-04T14:11:21.636000Z',
    lastName: 'User',
    phone: '+351999999999',
    username: '8fcaafbd7e6b4bf686fd713a88b25e',
  },
  userCode: 'JNDMYC8J',
};

export const MOCKED_COOLING_UNIT = {
  canDelete: false,
  capacityInMetricTons: 2,
  capacityInNumberCrates: 40,
  commodityInfos: [
    {
      combinedWeight: 30,
      commodity: 'Apple',
      cratesNumber: 1,
      optimalStorageTemperature: '-1.1-0 °C',
      percentage: 9,
    },
    {
      combinedWeight: 25,
      commodity: 'Banana',
      cratesNumber: 1,
      optimalStorageTemperature: '13-15 °C',
      percentage: 9,
    },
    {
      combinedWeight: 250,
      commodity: 'African star apple',
      cratesNumber: 10,
      optimalStorageTemperature: '15°C',
      percentage: 84,
    },
  ],
  commodityTotal: { totalCrates: 12, totalWeight: 305 },
  commonPricingType: { metric: 'KILOGRAMS', pricingId: 4415, type: 'PERIODICITY', value: 2 },
  coolingUnitType: 'FARM_GATE_STORAGE_ROOM',
  crateHeight: 0,
  crateLength: 0,
  crateWeight: 25,
  crateWidth: 0,
  crops: [
    { active: true, coolingUnitId: 66, cropId: 69, id: 4174, pricing: [Array], pricingId: 4363 },
    { active: true, coolingUnitId: 66, cropId: 1, id: 4175, pricing: [Array], pricingId: 4364 },
    { active: true, coolingUnitId: 66, cropId: 68, id: 4176, pricing: [Array], pricingId: 4365 },
    { active: true, coolingUnitId: 66, cropId: 2, id: 4177, pricing: [Array], pricingId: 4366 },
    { active: true, coolingUnitId: 66, cropId: 13, id: 4178, pricing: [Array], pricingId: 4367 },
    { active: false, coolingUnitId: 66, cropId: 3, id: 4179, pricing: [Array], pricingId: 4368 },
    { active: false, coolingUnitId: 66, cropId: 4, id: 4180, pricing: [Array], pricingId: 4369 },
    { active: true, coolingUnitId: 66, cropId: 6, id: 4181, pricing: [Array], pricingId: 4370 },
    { active: true, coolingUnitId: 66, cropId: 66, id: 4182, pricing: [Array], pricingId: 4371 },
    { active: true, coolingUnitId: 66, cropId: 7, id: 4183, pricing: [Array], pricingId: 4372 },
    { active: true, coolingUnitId: 66, cropId: 18, id: 4184, pricing: [Array], pricingId: 4373 },
    { active: true, coolingUnitId: 66, cropId: 8, id: 4185, pricing: [Array], pricingId: 4374 },
    { active: true, coolingUnitId: 66, cropId: 9, id: 4186, pricing: [Array], pricingId: 4375 },
    { active: true, coolingUnitId: 66, cropId: 5, id: 4187, pricing: [Array], pricingId: 4376 },
    { active: true, coolingUnitId: 66, cropId: 10, id: 4188, pricing: [Array], pricingId: 4377 },
    { active: true, coolingUnitId: 66, cropId: 12, id: 4189, pricing: [Array], pricingId: 4378 },
    { active: true, coolingUnitId: 66, cropId: 14, id: 4190, pricing: [Array], pricingId: 4379 },
    { active: true, coolingUnitId: 66, cropId: 15, id: 4191, pricing: [Array], pricingId: 4380 },
    { active: true, coolingUnitId: 66, cropId: 16, id: 4192, pricing: [Array], pricingId: 4381 },
    { active: true, coolingUnitId: 66, cropId: 76, id: 4193, pricing: [Array], pricingId: 4382 },
    { active: true, coolingUnitId: 66, cropId: 17, id: 4194, pricing: [Array], pricingId: 4383 },
    { active: true, coolingUnitId: 66, cropId: 74, id: 4195, pricing: [Array], pricingId: 4384 },
    { active: true, coolingUnitId: 66, cropId: 19, id: 4196, pricing: [Array], pricingId: 4385 },
    { active: true, coolingUnitId: 66, cropId: 75, id: 4197, pricing: [Array], pricingId: 4386 },
    { active: true, coolingUnitId: 66, cropId: 65, id: 4198, pricing: [Array], pricingId: 4387 },
    { active: true, coolingUnitId: 66, cropId: 20, id: 4199, pricing: [Array], pricingId: 4388 },
    { active: true, coolingUnitId: 66, cropId: 21, id: 4200, pricing: [Array], pricingId: 4389 },
    { active: true, coolingUnitId: 66, cropId: 23, id: 4202, pricing: [Array], pricingId: 4391 },
    { active: true, coolingUnitId: 66, cropId: 24, id: 4203, pricing: [Array], pricingId: 4392 },
    { active: true, coolingUnitId: 66, cropId: 25, id: 4204, pricing: [Array], pricingId: 4393 },
    { active: true, coolingUnitId: 66, cropId: 47, id: 4205, pricing: [Array], pricingId: 4394 },
    { active: true, coolingUnitId: 66, cropId: 26, id: 4206, pricing: [Array], pricingId: 4395 },
    { active: true, coolingUnitId: 66, cropId: 27, id: 4207, pricing: [Array], pricingId: 4396 },
    { active: true, coolingUnitId: 66, cropId: 64, id: 4208, pricing: [Array], pricingId: 4397 },
    { active: true, coolingUnitId: 66, cropId: 36, id: 4209, pricing: [Array], pricingId: 4398 },
    { active: true, coolingUnitId: 66, cropId: 28, id: 4210, pricing: [Array], pricingId: 4399 },
    { active: true, coolingUnitId: 66, cropId: 70, id: 4211, pricing: [Array], pricingId: 4400 },
    { active: true, coolingUnitId: 66, cropId: 29, id: 4212, pricing: [Array], pricingId: 4401 },
    { active: true, coolingUnitId: 66, cropId: 30, id: 4213, pricing: [Array], pricingId: 4402 },
    { active: true, coolingUnitId: 66, cropId: 31, id: 4214, pricing: [Array], pricingId: 4403 },
    { active: true, coolingUnitId: 66, cropId: 73, id: 4215, pricing: [Array], pricingId: 4404 },
    { active: true, coolingUnitId: 66, cropId: 34, id: 4216, pricing: [Array], pricingId: 4405 },
    { active: true, coolingUnitId: 66, cropId: 33, id: 4217, pricing: [Array], pricingId: 4406 },
    { active: true, coolingUnitId: 66, cropId: 32, id: 4219, pricing: [Array], pricingId: 4408 },
    { active: true, coolingUnitId: 66, cropId: 63, id: 4220, pricing: [Array], pricingId: 4409 },
    { active: true, coolingUnitId: 66, cropId: 37, id: 4221, pricing: [Array], pricingId: 4410 },
    { active: true, coolingUnitId: 66, cropId: 38, id: 4222, pricing: [Array], pricingId: 4411 },
    { active: true, coolingUnitId: 66, cropId: 58, id: 4223, pricing: [Array], pricingId: 4412 },
    { active: true, coolingUnitId: 66, cropId: 59, id: 4224, pricing: [Array], pricingId: 4413 },
    { active: true, coolingUnitId: 66, cropId: 60, id: 4225, pricing: [Array], pricingId: 4414 },
    { active: true, coolingUnitId: 66, cropId: 77, id: 4226, pricing: [Array], pricingId: 4415 },
    { active: true, coolingUnitId: 66, cropId: 39, id: 4227, pricing: [Array], pricingId: 4416 },
    { active: true, coolingUnitId: 66, cropId: 40, id: 4228, pricing: [Array], pricingId: 4417 },
    { active: true, coolingUnitId: 66, cropId: 41, id: 4229, pricing: [Array], pricingId: 4418 },
    { active: true, coolingUnitId: 66, cropId: 42, id: 4230, pricing: [Array], pricingId: 4419 },
    { active: true, coolingUnitId: 66, cropId: 43, id: 4231, pricing: [Array], pricingId: 4420 },
    { active: true, coolingUnitId: 66, cropId: 44, id: 4232, pricing: [Array], pricingId: 4421 },
    { active: true, coolingUnitId: 66, cropId: 45, id: 4233, pricing: [Array], pricingId: 4422 },
    { active: true, coolingUnitId: 66, cropId: 46, id: 4234, pricing: [Array], pricingId: 4423 },
    { active: true, coolingUnitId: 66, cropId: 48, id: 4235, pricing: [Array], pricingId: 4424 },
    { active: true, coolingUnitId: 66, cropId: 49, id: 4236, pricing: [Array], pricingId: 4425 },
    { active: true, coolingUnitId: 66, cropId: 50, id: 4237, pricing: [Array], pricingId: 4426 },
    { active: true, coolingUnitId: 66, cropId: 62, id: 4238, pricing: [Array], pricingId: 4427 },
    { active: true, coolingUnitId: 66, cropId: 51, id: 4240, pricing: [Array], pricingId: 4429 },
    { active: true, coolingUnitId: 66, cropId: 52, id: 4241, pricing: [Array], pricingId: 4430 },
    { active: true, coolingUnitId: 66, cropId: 53, id: 4242, pricing: [Array], pricingId: 4431 },
    { active: true, coolingUnitId: 66, cropId: 54, id: 4243, pricing: [Array], pricingId: 4432 },
    { active: true, coolingUnitId: 66, cropId: 72, id: 4244, pricing: [Array], pricingId: 4433 },
    { active: true, coolingUnitId: 66, cropId: 11, id: 4245, pricing: [Array], pricingId: 4434 },
    { active: true, coolingUnitId: 66, cropId: 55, id: 4246, pricing: [Array], pricingId: 4435 },
    { active: true, coolingUnitId: 66, cropId: 56, id: 4247, pricing: [Array], pricingId: 4436 },
    { active: true, coolingUnitId: 66, cropId: 57, id: 4248, pricing: [Array], pricingId: 4437 },
    { active: true, coolingUnitId: 66, cropId: 71, id: 4249, pricing: [Array], pricingId: 4438 },
    { active: true, coolingUnitId: 66, cropId: 22, id: 4201, pricing: [Array], pricingId: 4390 },
    { active: true, coolingUnitId: 66, cropId: 35, id: 4218, pricing: [Array], pricingId: 4407 },
    { active: true, coolingUnitId: 66, cropId: 61, id: 4239, pricing: [Array], pricingId: 4428 },
  ],
  dateCreation: '2024-08-30T11:35:46.890411Z',
  dateLastModified: '2024-09-04T10:44:23.326735Z',
  dateOperatorAssigned: [{ date: '2024-08-30T11:35:46.909727Z', id: 43, operatorId: 244 }],
  editableCheckins: false,
  foodCapacityInMetricTons: 1,
  id: 66,
  lastCheckInDate: '2024-09-04T18:01:21.761669Z',
  latestTemperature: '24.5',
  latestTemperatureTimestamp: '2024-09-30T15:58:50Z',
  location: 48,
  metric: 'KILOGRAMS',
  name: 'Test Unit',
  occupancy: 0,
  occupancyModifiedDate: '2024-09-18T22:53:38.202402Z',
  operators: [244],
  powerOptions: [
    {
      amountRefrigerant: 0,
      batteryCapacity: 0,
      batteryCount: 0,
      batteryMaxCurrent: 0,
      batteryPeakEnergyStorage: 0,
      batteryType: null,
      batteryWeight: 0,
      coolingUnitId: 66,
      dailyRoomWattage: 0,
      electricityStorageSystem: 'none',
      id: 39,
      powerConsumptionInMt: 0,
      powerSource: 'pvpanels',
      powerSourceBiomassPercent: 0,
      powerSourceDieselConsumptionKwh: 0,
      powerSourceDieselPercent: 0,
      powerSourceGridPercent: 0,
      powerSourcePvPercent: 0,
      pvPanelCount: 0,
      pvPanelMaxPower: 0,
      pvPanelSize: 0,
      pvPanelType: '',
      pvPanelWeight: 0,
      refrigerantType: 'other',
      roomInsulator: 0,
      thermalStorageMethod: 'none',
    },
  ],
  public: false,
  roomHeight: 0,
  roomLength: 0,
  roomWeight: 0,
  roomWidth: 0,
  sensor: true,
  sensorError: false,
  sensorList: [
    {
      channelId: '62116',
      dateSensorFirstLinked: '2024-09-04T10:24:48.947116Z',
      field: 'Temperature',
      id: 5,
      machineId: 'GRD2493640',
      type: 'lora',
      username: '6695400a2136d15a7d363542',
    },
  ],
  ubibotSensorChannel: null,
};

export const MOCKED_CHECK_IN_DATA = [
  {
    crop: { id: 69, name: 'African star apple', image: 'crop_images/AfricanStarApple.png' },
    additionalInfo: '',
    crates: [
      { checkOut: null, weight: 30, tag: '', coolingUnitId: 66, isSellable: false },
      { checkOut: null, weight: 25, tag: '', coolingUnitId: 66, isSellable: false },
    ],
    initialGrade: null,
    harvestDate: '-1',
    hasPicture: false,
    price: 0,
  },
];

export const MOCKED_CHECK_OUT_DATA = [
  {
    id: 8811,
    produce: 498,
    coolingUnit: 65,
    weight: 25,
    remainingShelfLife: null,
    plannedDays: null,
    checkOut: null,
    pricing: [{ id: 4295, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
    coolingUnitMetric: 'CRATES',
    checkinDate: '2024-08-27T13:34:52.192763Z',
    name: 'Bitter Leaf',
    cropImage: 'crop_images/BitterLeaf.png',
    movementCode: 'DJDY61',
    currentStorageDays: 34,
    runDt: false,
    qualityDt: -1,
    tag: '',
  },
  {
    id: 8812,
    produce: 498,
    coolingUnit: 65,
    weight: 25,
    remainingShelfLife: null,
    plannedDays: null,
    checkOut: null,
    pricing: [{ id: 4295, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
    coolingUnitMetric: 'CRATES',
    checkinDate: '2024-08-27T13:34:52.192763Z',
    name: 'Bitter Leaf',
    cropImage: 'crop_images/BitterLeaf.png',
    movementCode: 'DJDY61',
    currentStorageDays: 34,
    runDt: false,
    qualityDt: -1,
    tag: '',
  },
  {
    id: 8813,
    produce: 499,
    coolingUnit: 65,
    weight: 25,
    remainingShelfLife: null,
    plannedDays: null,
    checkOut: null,
    pricing: [{ id: 4302, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
    coolingUnitMetric: 'CRATES',
    checkinDate: '2024-08-27T13:38:21.825083Z',
    name: 'Cauliflower',
    cropImage: 'crop_images/cauliflower_dVI5dHi.jpg',
    movementCode: 'INXHZV',
    currentStorageDays: 34,
    runDt: true,
    qualityDt: -1,
    tag: '',
  },
];

export const MOCKED_DASHBOARD_DATA = [
  {
    id: 503,
    cropId: 70,
    cropName: 'Lemon basil',
    cropImage: 'crop_images/lemon_basil.jpg',
    farmer: 'John Doe',
    ownerContact: '+351911111111',
    farmerId: 164,
    minimumRemainingShelfLife: 4,
    plannedDays: null,
    cratesAmount: 4,
    movementCode: 'AQT88U',
    cmpCheckoutCompleted: false,
    cratesCombinedWeight: 100,
    cratesCombinedCost: 12,
    currentStorageDays: 41,
    hasDigitalTwin: false,
    qualityDt: null,
    runDt: false,
    additionalInfo: '',
    checkedInCrates: [
      {
        id: 8822,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19000',
      },
      {
        id: 8823,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19001',
      },
      {
        id: 8824,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19002',
      },
      {
        id: 8825,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19003',
      },
    ],
  },
  {
    id: 504,
    cropId: 70,
    cropName: 'Banana',
    cropImage: 'crop_images/banana.jpg',
    farmer: 'John Doe',
    ownerContact: '+351911111111',
    farmerId: 164,
    minimumRemainingShelfLife: 1,
    plannedDays: null,
    cratesAmount: 4,
    movementCode: 'FQX08A',
    cmpCheckoutCompleted: false,
    cratesCombinedWeight: 100,
    cratesCombinedCost: 12,
    currentStorageDays: 41,
    hasDigitalTwin: false,
    qualityDt: null,
    runDt: false,
    additionalInfo: '',
    checkedInCrates: [
      {
        id: 8822,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19000',
      },
      {
        id: 8823,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19001',
      },
      {
        id: 8824,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19002',
      },
      {
        id: 8825,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19003',
      },
    ],
  },
  {
    id: 505,
    cropId: 70,
    cropName: 'Apple',
    cropImage: 'crop_images/apple.jpg',
    farmer: 'John Doe',
    ownerContact: '+351911111111',
    farmerId: 164,
    minimumRemainingShelfLife: 10,
    plannedDays: null,
    cratesAmount: 4,
    movementCode: 'BDP24P',
    cmpCheckoutCompleted: false,
    cratesCombinedWeight: 100,
    cratesCombinedCost: 12,
    currentStorageDays: 41,
    hasDigitalTwin: false,
    qualityDt: null,
    runDt: false,
    additionalInfo: '',
    checkedInCrates: [
      {
        id: 8822,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19000',
      },
      {
        id: 8823,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19001',
      },
      {
        id: 8824,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19002',
      },
      {
        id: 8825,
        produce: 503,
        coolingUnit: 65,
        weight: 25,
        remainingShelfLife: null,
        plannedDays: null,
        fullyCheckedOut: false,
        pricing: [{ id: 4324, pricingType: 'PERIODICITY', fixedRate: 0, dailyRate: 3 }],
        coolingUnitMetric: 'CRATES',
        checkInDate: '2024-09-03T10:45:57.505824Z',
        name: 'Lemon basil',
        cropImage: 'crop_images/lemon_basil.jpg',
        movementCode: 'AQT88U',
        currentStorageDays: 41,
        runDt: false,
        qualityDt: -1,
        tag: '19003',
      },
    ],
  },
];

export const MOCKED_HISTORY_DATA = [
  {
    id: 1004,
    code: 'MO-#64-CU-#75',
    date: new Date('2024-12-12T11:32:24.674639Z'),
    initiatedFor: EInitiatedFor.MARKETPLACE_ORDER,
    order: {},
    operator: '',
    coolingUnitId: 65,
    checkin: {
      id: 599,
      ownedByUserId: 286,
      ownedOnBehalfOfCompanyId: null,
      ownerName: 'Maria Boyle',
      crates: [
        {
          id: 9210,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 41,
          plannedDays: 0,
          weight: 1,
          initialWeight: 1,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 1,
        },
        {
          id: 9211,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 43,
          plannedDays: 0,
          weight: 4,
          initialWeight: 4,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 1,
        },
      ],
    },
    checkout: {
      id: 464,
      paymentGateway: EPaymentGateway.PAYTACK,
      paymentMethod: EPaymentMethod.CASH,
      paymentThrough: EPaymentThrough.COLDTIVATE,
      crates: [
        {
          id: 9209,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 41,
          plannedDays: 0,
          weight: 2,
          initialWeight: 3,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 1,
          ownedByUserId: 281,
          ownedOnBehalfOfCompanyId: 40,
          ownerName: 'Johnny Ferguson',
        },
        {
          id: 9206,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 43,
          plannedDays: null,
          weight: 21,
          initialWeight: 25,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 8,
          ownedByUserId: 281,
          ownedOnBehalfOfCompanyId: 40,
          ownerName: 'Johnny Ferguson',
        },
      ],
      hasMarketSurvey: [],
      marketSurveyDelay: false,
      calculatedPrice: 160,
      discount: 0,
      totalPrice: 160,
    },
  },
  {
    id: 1005,
    code: 'F2XC56',
    date: new Date('2024-12-11T10:30:24.674639Z'),
    initiatedFor: EInitiatedFor.CHECK_IN,
    order: {},
    operator: '',
    coolingUnitId: 65,
    checkin: {
      id: 599,
      ownedByUserId: 286,
      ownedOnBehalfOfCompanyId: null,
      ownerName: 'Johnny Ferguson',
      crates: [
        {
          id: 9210,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 41,
          plannedDays: 0,
          weight: 1,
          initialWeight: 1,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 1,
        },
        {
          id: 9211,
          cropId: 2,
          crop: {
            id: 2,
            name: 'Banana',
          },
          remainingShelfLife: 43,
          plannedDays: 0,
          weight: 4,
          initialWeight: 4,
          amount: 125,
          tag: '',
          fullyCheckedOut: false,
          daysInStorage: 1,
        },
      ],
    },
    checkout: {} as GetMovementsHistoryResponse[number]['checkout'],
  },
] satisfies GetMovementsHistoryResponse;
